! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : chemuci_Monitor.f90
! Equation file        : chemuci.kpp
! Output root filename : chemuci
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chemuci_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(55) :: SPC_NAMES = (/ &
     'ISOP_VBS                        ','C10H16                          ','E90                             ', & ! index 1 - 3
     'SOAG0                           ','SOAG15                          ','SOAG24                          ', & ! index 4 - 6
     'soa_a1                          ','soa_a2                          ','soa_a3                          ', & ! index 7 - 9
     'H2SO4                           ','SOAG31                          ','SOAG32                          ', & ! index 10 - 12
     'SOAG33                          ','SOAG34                          ','SOAG35                          ', & ! index 13 - 15
     'C2H6                            ','SO2                             ','C3H8                            ', & ! index 16 - 18
     'H2O2                            ','PAN                             ','CH3COCH3                        ', & ! index 19 - 21
     'CH4LNZ                          ','DMS                             ','N2O5                            ', & ! index 22 - 24
     'ISOP                            ','C2H4                            ','HNO3                            ', & ! index 25 - 27
     'HO2NO2                          ','CH3OOH                          ','CO                              ', & ! index 28 - 30
     'C2H5OOH                         ','CH2O                            ','MVKO2                           ', & ! index 31 - 33
     'ROHO2                           ','C2H5O2                          ','ISOPO2                          ', & ! index 34 - 36
     'MVKMACR                         ','CH3CHO                          ','CH3CO3                          ', & ! index 37 - 39
     'O3                              ','HO2                             ','CH3O2                           ', & ! index 40 - 42
     'NO                              ','NO2                             ','NO3                             ', & ! index 43 - 45
     'OH                              ','M                               ','O2                              ', & ! index 46 - 48
     'H2O                             ','H2                              ','prsd_O3                         ', & ! index 49 - 51
     'prsd_NO3                        ','prsd_OH                         ','H                               ', & ! index 52 - 54
     'CH3CO                           ' /) ! index up to 55

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '                 O3 --> O3                                                                          ', & ! index 1
     '                 O2 --> 2 O3                                                                        ', & ! index 2
     '               H2O2 --> 2 OH                                                                        ', & ! index 3
     '               CH2O --> CO + 2 HO2                                                                  ', & ! index 4
     '               CH2O --> CO + H2                                                                     ', & ! index 5
     '             CH3OOH --> CH2O + HO2 + OH                                                             ', & ! index 6
     '            C2H5OOH --> CH3CHO + HO2 + OH                                                           ', & ! index 7
     '                NO2 --> O3 + NO                                                                     ', & ! index 8
     '                NO3 --> O3 + NO2                                                                    ', & ! index 9
     '                NO3 --> NO                                                                          ', & ! index 10
     '               N2O5 --> NO2 + NO3                                                                   ', & ! index 11
     '               N2O5 --> O3 + NO + NO3                                                               ', & ! index 12
     '               HNO3 --> NO2 + OH                                                                    ', & ! index 13
     '             HO2NO2 --> NO3 + OH                                                                    ', & ! index 14
     '             HO2NO2 --> HO2 + NO2                                                                   ', & ! index 15
     '             CH3CHO --> CO + HO2 + CH3O2                                                            ', & ! index 16
     '                PAN --> CH3CO3 + NO2                                                                ', & ! index 17
     '           CH3COCH3 --> 0.33 CO + 0.67 CH3CO3 + 1.33 CH3O2                                          ', & ! index 18
     '            MVKMACR --> 1.5 CO + 2 CH2O + 0.5 HO2 + 0.5 CH3O2                                       ', & ! index 19
     '             soa_a1 -->                                                                             ', & ! index 20
     '             soa_a2 -->                                                                             ', & ! index 21
     '             soa_a3 -->                                                                             ', & ! index 22
     '           O3 + H2O --> 2 OH                                                                        ', & ! index 23
     '            O3 + H2 --> HO2 + OH                                                                    ', & ! index 24
     '        CH4LNZ + O3 --> CH3O2 + OH                                                                  ', & ! index 25
     '            CO + OH --> H                                                                           ', & ! index 26
     '        CO + OH + M --> HO2 + M                                                                     ', & ! index 27
     '            OH + H2 --> HO2 + H2O                                                                   ', & ! index 28
     '        CH4LNZ + OH --> CH3O2 + H2O                                                                 ', & ! index 29
     '          C2H6 + OH --> C2H5O2                                                                      ' /) ! index up to 30
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '          C3H8 + OH --> 0.8 CH3COCH3 + 0.2 CH3CHO + HO2                                             ', & ! index 31
     '      C2H4 + OH + M --> ROHO2                                                                       ', & ! index 32
     '          C2H4 + O3 --> CO + CH2O + 0.5 CH3CHO                                                      ', & ! index 33
     '          ISOP + O3 --> CH2O + MVKMACR + OH                                                         ', & ! index 34
     '          ISOP + OH --> ISOPO2                                                                      ', & ! index 35
     '          CH2O + OH --> CO + HO2 + H2O                                                              ', & ! index 36
     '            O3 + OH --> HO2 + O2                                                                    ', & ! index 37
     '               2 OH --> O3 + H2O                                                                    ', & ! index 38
     '           O3 + HO2 --> OH + 2 O2                                                                   ', & ! index 39
     '           HO2 + OH --> O2 + H2O                                                                    ', & ! index 40
     '          2 HO2 + M --> H2O2 + M                                                                    ', & ! index 41
     '              2 HO2 --> H2O2                                                                        ', & ! index 42
     '           2 OH + M --> H2O2 + M                                                                    ', & ! index 43
     '          H2O2 + OH --> HO2 + H2O                                                                   ', & ! index 44
     '            O3 + NO --> NO2 + O2                                                                    ', & ! index 45
     '           HO2 + NO --> NO2 + OH                                                                    ', & ! index 46
     '           O3 + NO2 --> NO3 + O2                                                                    ', & ! index 47
     '           NO3 + OH --> HO2 + NO2                                                                   ', & ! index 48
     '           NO + NO3 --> 2 NO2                                                                       ', & ! index 49
     '        HO2NO2 + OH --> NO2 + O2 + H2O                                                              ', & ! index 50
     '          HNO3 + OH --> NO3 + H2O                                                                   ', & ! index 51
     '          HNO3 + OH --> NO3 + H2O                                                                   ', & ! index 52
     '       NO2 + OH + M --> HNO3 + M                                                                    ', & ! index 53
     '      HO2 + NO2 + M --> HO2NO2 + M                                                                  ', & ! index 54
     '      NO2 + NO3 + M --> N2O5 + M                                                                    ', & ! index 55
     '   CH3CO3 + NO2 + M --> PAN + M                                                                     ', & ! index 56
     '         HO2NO2 + M --> HO2 + NO2 + M                                                               ', & ! index 57
     '           N2O5 + M --> NO2 + NO3 + M                                                               ', & ! index 58
     '            PAN + M --> CH3CO3 + NO2 + M                                                            ', & ! index 59
     '        HO2 + CH3O2 --> CH3OOH + O2                                                                 ' /) ! index up to 60
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '         CH3O2 + NO --> CH2O + HO2 + NO2                                                            ', & ! index 61
     '            2 CH3O2 --> 2 CH2O + 2 HO2                                                              ', & ! index 62
     '        CH3OOH + OH --> 0.3 CH2O + 0.7 CH3O2 + 0.3 OH                                               ', & ! index 63
     '        C2H5O2 + NO --> CH3CHO + HO2 + NO2                                                          ', & ! index 64
     '           2 C2H5O2 --> 2 CH3CHO + 2 HO2                                                            ', & ! index 65
     '     C2H5O2 + CH3O2 --> CH2O + CH3CHO + 2 HO2                                                       ', & ! index 66
     '       C2H5O2 + HO2 --> C2H5OOH                                                                     ', & ! index 67
     '       C2H5OOH + OH --> C2H5O2                                                                      ', & ! index 68
     '       C2H5OOH + OH --> CH3CHO + OH                                                                 ', & ! index 69
     '        CH3CHO + OH --> 0.5 CO + 0.5 CH3CO3 + 0.5 CH3O2                                             ', & ! index 70
     '       CH3CHO + NO3 --> HNO3 + CH3CO3                                                               ', & ! index 71
     '        CH3CO3 + NO --> CH3O2 + NO2                                                                 ', & ! index 72
     '     CH3CO3 + CH3O2 --> CH2O + HO2 + CH3O2                                                          ', & ! index 73
     '           2 CH3CO3 --> 2 CH3O2                                                                     ', & ! index 74
     '      CH3COCH3 + OH --> CH2O + CH3CO3                                                               ', & ! index 75
     '      CH3COCH3 + OH --> CH2O + CH3CO3                                                               ', & ! index 76
     '         ROHO2 + NO --> CH2O + CH3CHO + NO2                                                         ', & ! index 77
     '        ROHO2 + HO2 --> CH2O + CH3CHO + OH                                                          ', & ! index 78
     '      ROHO2 + CH3O2 --> 2 CH2O + HO2 + CH3CO                                                        ', & ! index 79
     '        ISOPO2 + NO --> CH2O + MVKMACR + NO2                                                        ', & ! index 80
     '       ISOPO2 + HO2 --> 2 CO + C2H5OOH                                                              ', & ! index 81
     '     ISOPO2 + CH3O2 --> 2 CH2O + MVKMACR + 2 HO2                                                    ', & ! index 82
     '       MVKMACR + O3 --> CH2O + 0.5 CH3CO3 + CH3O2                                                   ', & ! index 83
     '       MVKMACR + OH --> MVKO2                                                                       ', & ! index 84
     '         MVKO2 + NO --> CH2O + 0.5 CH3CO3 + NO2                                                     ', & ! index 85
     '        MVKO2 + HO2 --> CO + C2H5OOH                                                                ', & ! index 86
     '                E90 -->                                                                             ', & ! index 87
     '           DMS + OH --> SO2                                                                         ', & ! index 88
     '           DMS + OH --> 0.5 SO2 + 0.5 HO2                                                           ', & ! index 89
     '           SO2 + OH --> H2SO4                                                                       ' /) ! index up to 90
  CHARACTER(LEN=100), PARAMETER, DIMENSION(14) :: EQN_NAMES_3 = (/ &
     '          DMS + NO3 --> SO2 + HNO3                                                                  ', & ! index 91
     '    SOAG0 + prsd_OH --> 1.15 SOAG15                                                                 ', & ! index 92
     '   SOAG15 + prsd_OH --> 1.15 SOAG24                                                                 ', & ! index 93
     '   SOAG24 + prsd_OH --> 0.46 SOAG33 + 0.5 SOAG35                                                    ', & ! index 94
     ' ISOP_VBS + prsd_OH --> 0.00272 SOAG32 + 0.00981 SOAG33 + 0.00218 SOAG34                            ', & ! index 95
     '   C10H16 + prsd_OH --> 0.14986 SOAG32 + 0.0545 SOAG33 + 0.09264 SOAG34                             ', & ! index 96
     ' ISOP_VBS + prsd_O3 --> 0.00327 SOAG33                                                              ', & ! index 97
     '   C10H16 + prsd_O3 --> 0.0436 SOAG31 + 0.01035 SOAG32 + 0.09809 SOAG33 + 0.01635 SOAG34            ', & ! index 98
     'ISOP_VBS + prsd_NO3 --> 0.00027 SOAG32 + 0.0406 SOAG33 + 0.06458 SOAG34                             ', & ! index 99
     '  C10H16 + prsd_NO3 --> 0.17493 SOAG33 + 0.59019 SOAG34                                             ', & ! index 100
     '   SOAG35 + prsd_OH --> 0.46 SOAG34 + 0.5 SOAG35                                                    ', & ! index 101
     '   SOAG34 + prsd_OH --> 0.46 SOAG33 + 0.5 SOAG35                                                    ', & ! index 102
     '   SOAG33 + prsd_OH --> 0.46 SOAG32 + 0.5 SOAG35                                                    ', & ! index 103
     '   SOAG32 + prsd_OH --> 0.46 SOAG31 + 0.5 SOAG35                                                    ' /) ! index up to 104
  CHARACTER(LEN=100), PARAMETER, DIMENSION(104) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3 /)

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE chemuci_Monitor
