! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
! 
! File                 : CBMZ_Function.f90
! Equation file        : CBMZ.kpp
! Output root filename : CBMZ
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE CBMZ_Function

  USE CBMZ_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
  !$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Aggregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(59)
  A(2) = RCT(2)*V(60)
  A(3) = RCT(3)*V(32)
  A(4) = RCT(4)*V(38)
  A(5) = RCT(5)*V(27)
  A(6) = RCT(6)*V(21)
  A(7) = RCT(7)*V(64)
  A(8) = RCT(8)*V(64)
  A(9) = RCT(9)*V(19)
  A(10) = RCT(10)*V(47)
  A(11) = RCT(11)*V(47)
  A(12) = RCT(12)*V(31)
  A(13) = RCT(13)*V(33)
  A(14) = RCT(14)*V(54)
  A(15) = RCT(15)*V(49)
  A(16) = RCT(16)*V(53)
  A(17) = RCT(17)*V(42)
  A(18) = RCT(18)*V(66)
  A(19) = RCT(19)*V(57)
  A(20) = RCT(20)*V(56)
  A(21) = RCT(21)*V(16)*F(2)
  A(22) = RCT(22)*V(16)*F(1)
  A(23) = RCT(23)*V(37)*F(2)
  A(24) = RCT(24)*V(37)*V(64)
  A(25) = RCT(25)*V(37)*V(59)
  A(26) = RCT(26)*V(37)*V(59)
  A(27) = RCT(27)*V(37)*V(63)
  A(28) = RCT(28)*V(63)*V(64)
  A(29) = RCT(29)*V(59)*V(64)
  A(30) = RCT(30)*V(64)*V(67)
  A(31) = RCT(31)*V(64)*V(65)
  A(32) = RCT(32)*V(67)*F(2)
  A(33) = RCT(33)*V(63)*V(67)
  A(34) = RCT(34)*V(59)*V(67)
  A(35) = RCT(35)*V(60)*V(67)
  A(36) = RCT(36)*V(32)*V(67)
  A(37) = RCT(37)*V(38)*V(67)
  A(38) = RCT(38)*V(27)*V(67)
  A(39) = RCT(39)*V(65)*V(67)
  A(40) = RCT(40)*V(19)*V(67)
  A(41) = RCT(41)*V(65)*V(65)
  A(42) = RCT(42)*V(65)*V(65)*F(1)
  A(43) = RCT(43)*V(63)*V(65)
  A(44) = RCT(44)*V(59)*V(65)
  A(45) = RCT(45)*V(59)*V(65)
  A(46) = RCT(46)*V(27)
  A(47) = RCT(47)*V(60)*V(63)
  A(48) = RCT(48)*V(59)*V(60)
  A(49) = RCT(49)*V(59)*V(60)
  A(50) = RCT(50)*V(60)*V(60)
  A(51) = RCT(51)*V(60)*V(65)
  A(52) = RCT(52)*V(21)*F(1)
  A(53) = RCT(53)*V(21)
  A(54) = RCT(54)*V(39)*V(67)
  A(55) = RCT(55)*V(15)*V(67)
  A(56) = RCT(56)*V(23)*V(67)
  A(57) = RCT(57)*V(28)*V(67)
  A(58) = RCT(58)*V(41)*V(67)
  A(59) = RCT(59)*V(47)*V(67)
  A(60) = RCT(60)*V(47)*V(60)
  A(61) = RCT(61)*V(54)*V(67)
  A(62) = RCT(62)*V(54)*V(60)
  A(63) = RCT(63)*V(49)*V(67)
  A(64) = RCT(64)*V(53)*V(67)
  A(65) = RCT(65)*V(53)*V(60)
  A(66) = RCT(66)*V(34)*V(64)
  A(67) = RCT(67)*V(34)*V(67)
  A(68) = RCT(68)*V(45)*V(64)
  A(69) = RCT(69)*V(50)*V(64)
  A(70) = RCT(70)*V(45)*V(67)
  A(71) = RCT(71)*V(50)*V(67)
  A(72) = RCT(72)*V(45)*V(60)
  A(73) = RCT(73)*V(50)*V(60)
  A(74) = RCT(74)*V(20)*V(67)
  A(75) = RCT(75)*V(22)*V(67)
  A(76) = RCT(76)*V(29)*V(63)
  A(77) = RCT(77)*V(36)*V(67)
  A(78) = RCT(78)*V(36)*V(60)
  A(79) = RCT(79)*V(24)*V(59)
  A(80) = RCT(80)*V(42)*V(67)
  A(81) = RCT(81)*V(42)*V(64)
  A(82) = RCT(82)*V(46)*V(67)
  A(83) = RCT(83)*V(46)*V(64)
  A(84) = RCT(84)*V(46)*V(60)
  A(85) = RCT(85)*V(56)*V(67)
  A(86) = RCT(86)*V(56)*V(64)
  A(87) = RCT(87)*V(56)*V(60)
  A(88) = RCT(88)*V(43)*V(63)
  A(89) = RCT(89)*V(40)*V(63)
  A(90) = RCT(90)*V(44)*V(63)
  A(91) = RCT(91)*V(43)*V(65)
  A(92) = RCT(92)*V(40)*V(65)
  A(93) = RCT(93)*V(44)*V(65)
  A(94) = RCT(94)*V(31)*V(67)
  A(95) = RCT(95)*V(33)*V(67)
  A(96) = RCT(96)*V(66)*V(67)
  A(97) = RCT(97)*V(57)*V(67)
  A(98) = RCT(98)*V(58)*V(59)
  A(99) = RCT(99)*V(18)
  A(100) = RCT(100)*V(35)*V(67)
  A(101) = RCT(101)*V(55)*V(63)
  A(102) = RCT(102)*V(52)*V(63)
  A(103) = RCT(103)*V(61)*V(63)
  A(104) = RCT(104)*V(58)*V(63)
  A(105) = RCT(105)*V(62)*V(63)
  A(106) = RCT(106)*V(51)*V(63)
  A(107) = RCT(107)*V(48)*V(63)
  A(108) = RCT(108)*V(55)*V(60)
  A(109) = RCT(109)*V(52)*V(60)
  A(110) = RCT(110)*V(60)*V(61)
  A(111) = RCT(111)*V(58)*V(60)
  A(112) = RCT(112)*V(60)*V(62)
  A(113) = RCT(113)*V(51)*V(60)
  A(114) = RCT(114)*V(48)*V(60)
  A(115) = RCT(115)*V(55)*V(65)
  A(116) = RCT(116)*V(52)*V(65)
  A(117) = RCT(117)*V(61)*V(65)
  A(118) = RCT(118)*V(58)*V(65)
  A(119) = RCT(119)*V(62)*V(65)
  A(120) = RCT(120)*V(51)*V(65)
  A(121) = RCT(121)*V(48)*V(65)
  A(122) = RCT(122)*V(17)*V(67)
  A(123) = RCT(123)*V(30)*V(41)
  A(127) = RCT(127)*V(55)
  A(128) = RCT(128)*V(52)
  A(129) = RCT(129)*V(61)
  A(130) = RCT(130)*V(58)
  A(131) = RCT(131)*V(62)
  A(132) = RCT(132)*V(51)
  A(133) = RCT(133)*V(43)
  A(134) = RCT(134)*V(40)
  A(135) = RCT(135)*V(44)
  A(136) = RCT(136)*V(48)
  A(137) = RCT(137)*V(25)*V(67)
  A(138) = RCT(138)*V(25)*V(60)
  A(139) = RCT(139)*V(25)*V(64)
  A(140) = RCT(140)*V(26)*V(67)
  A(141) = RCT(141)*V(26)*V(60)
  A(142) = RCT(142)*V(26)*V(64)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Aggregate function
  Vdot(1) = A(55)
  Vdot(2) = 0
  Vdot(3) = 0
  Vdot(4) = 0.52*A(66)+0.22*A(68)
  Vdot(5) = 0.09*A(68)+0.16*A(69)+0.39*A(83)+0.46*A(86)+0.4*A(118)
  Vdot(6) = 0.039*A(74)+0.039*A(75)+0.039*A(77)+0.039*A(78)
  Vdot(7) = 0.108*A(74)+0.108*A(75)+0.108*A(77)+0.108*A(78)
  Vdot(8) = 0.012*A(58)
  Vdot(9) = 0.008*A(68)+0.008*A(69)+0.008*A(70)+0.008*A(71)+0.008*A(72)+0.008*A(73)
  Vdot(10) = 0.0064*A(137)+0.022*A(139)
  Vdot(11) = 0.055*A(137)+0.19*A(139)
  Vdot(12) = 0.037*A(140)+0.13*A(142)
  Vdot(13) = 0.056*A(140)+0.19*A(142)
  Vdot(14) = A(121)+A(123)+A(136)
  Vdot(15) = -A(55)
  Vdot(16) = A(8)-A(21)-A(22)
  Vdot(17) = -A(122)
  Vdot(18) = A(98)-A(99)
  Vdot(19) = -A(9)-A(40)+A(41)+A(42)
  Vdot(20) = -A(74)
  Vdot(21) = -A(6)+A(49)-A(52)-A(53)
  Vdot(22) = -A(75)
  Vdot(23) = -A(56)+0.06*A(68)+0.08*A(69)
  Vdot(24) = 0.4*A(77)+A(78)-A(79)
  Vdot(25) = -A(137)-A(138)-A(139)
  Vdot(26) = -A(140)-A(141)-A(142)
  Vdot(27) = -A(5)-A(38)+A(44)-A(46)
  Vdot(28) = -A(57)+0.01*A(68)+0.01*A(69)+0.2*A(128)
  Vdot(29) = 0.8*A(74)+0.45*A(75)-A(76)
  Vdot(30) = 1.98*A(18)+1.98*A(19)+1.06*A(68)+2.26*A(69)+A(70)+2.23*A(71)+0.42*A(96)+1.68*A(103)+A(106)+1.98*A(110)&
               &+A(113)-A(123)+1.25*A(129)+A(132)
  Vdot(31) = -A(12)-A(94)+A(115)
  Vdot(32) = -A(3)+A(33)-A(36)+A(45)
  Vdot(33) = -A(13)-A(95)+A(116)
  Vdot(34) = -A(66)-A(67)
  Vdot(35) = 0.03*A(68)+0.04*A(69)-A(100)+0.34*A(127)
  Vdot(36) = 0.12*A(74)+0.05*A(75)-A(77)-A(78)
  Vdot(37) = A(1)+0.89*A(2)+A(7)+A(21)-A(23)-A(24)-A(25)-A(26)-A(27)
  Vdot(38) = -A(4)+A(34)-A(37)+0.3*A(51)+2*A(52)+A(60)+A(62)+A(65)+A(78)+0.07*A(87)
  Vdot(39) = A(10)+A(11)+A(14)+A(16)+A(17)+0.33*A(20)-A(54)+A(59)+A(60)+A(65)+0.24*A(66)+0.31*A(68)+0.3*A(69)+2*A(80)&
               &+0.69*A(81)+0.07*A(83)+0.16*A(86)+0.64*A(87)+0.59*A(90)
  Vdot(40) = A(84)-A(89)-A(92)-A(134)
  Vdot(41) = -A(58)+1.1*A(75)+1.86*A(87)+0.18*A(88)+1.6*A(89)+2*A(92)-A(123)+2*A(134)
  Vdot(42) = -A(17)+0.95*A(76)+0.3*A(77)-A(80)-A(81)
  Vdot(43) = A(82)-A(88)-A(91)-A(133)
  Vdot(44) = 0.5*A(85)-A(90)-A(93)-A(135)
  Vdot(45) = -A(68)-A(70)-A(72)
  Vdot(46) = -A(82)-A(83)-A(84)
  Vdot(47) = -A(10)-A(11)+A(12)+0.2*A(20)-A(59)-A(60)+A(66)+1.56*A(67)+0.57*A(68)+A(70)+A(80)+0.7*A(81)+0.6*A(83)+0.15&
               &*A(86)+0.28*A(87)+0.63*A(88)+0.25*A(90)+0.3*A(94)+A(100)+A(101)+A(105)+0.5*A(106)+A(108)+A(112)+0.5*A(113)&
               &+0.66*A(127)+0.7*A(131)+0.5*A(132)
  Vdot(48) = 0.4*A(18)+0.41*A(19)+A(64)+A(67)+A(70)+A(71)+0.08*A(74)+0.5*A(75)+0.6*A(77)+A(80)+0.03*A(81)+0.08*A(82)+0.2&
               &*A(83)+0.2*A(85)+0.07*A(86)+0.93*A(87)+0.34*A(103)-A(107)+0.4*A(110)-A(114)-A(121)+0.24*A(129)-A(136)
  Vdot(49) = -A(15)+0.74*A(18)+0.74*A(19)+0.03*A(20)-A(63)+0.07*A(69)+0.23*A(71)+0.09*A(86)+0.63*A(90)+0.62*A(103)+0.74&
               &*A(110)+0.57*A(129)+0.15*A(131)+0.5*A(135)
  Vdot(50) = -A(69)-A(71)-A(73)
  Vdot(51) = A(72)+A(73)+A(97)-A(106)-A(113)-A(120)-A(132)
  Vdot(52) = 0.1*A(18)+0.1*A(19)+A(57)+0.06*A(68)+0.05*A(69)+0.7*A(95)-A(102)+0.08*A(103)-A(109)+0.1*A(110)-A(116)&
               &-A(128)+0.06*A(129)
  Vdot(53) = -A(16)-A(64)-A(65)+0.04*A(68)+0.07*A(69)+0.8*A(75)+0.2*A(81)+0.85*A(86)+0.34*A(90)+0.19*A(96)+0.15*A(131)
  Vdot(54) = A(13)-A(14)+0.3*A(18)+0.3*A(19)+0.07*A(20)-A(61)-A(62)+0.22*A(67)+0.47*A(68)+1.03*A(69)+A(70)+1.77*A(71)&
               &+0.03*A(81)+0.15*A(83)+0.02*A(86)+0.28*A(87)+0.8*A(89)+0.55*A(90)+0.3*A(95)+0.04*A(96)+A(102)+0.25*A(103)&
               &+0.5*A(106)+A(109)+0.3*A(110)+0.5*A(113)+A(122)+0.8*A(128)+0.21*A(129)+0.5*A(132)+A(134)+0.5*A(135)
  Vdot(55) = A(14)+A(15)+0.7*A(20)+A(56)+0.07*A(68)+0.1*A(69)+0.05*A(86)+0.7*A(94)-A(101)+A(104)-A(108)+A(111)-A(115)&
               &-A(127)+A(130)
  Vdot(56) = -A(20)+0.65*A(83)-A(85)-A(86)-A(87)+0.91*A(88)+0.2*A(89)+A(133)
  Vdot(57) = -A(19)+0.05*A(76)+A(79)+0.93*A(87)+0.09*A(88)+0.8*A(89)+A(92)-A(97)+0.16*A(103)+0.5*A(106)+0.5*A(113)&
               &+A(120)+0.5*A(132)+A(134)
  Vdot(58) = A(15)+A(16)+A(17)+0.97*A(20)+A(61)+A(62)+A(64)+A(65)+0.13*A(68)+0.19*A(69)+A(80)+0.62*A(81)+0.2*A(83)+0.5&
               &*A(85)+0.11*A(86)+0.07*A(87)-A(98)+A(99)-A(104)+A(105)-A(111)+A(112)-A(118)-A(130)+0.7*A(131)
  Vdot(59) = -A(1)+0.89*A(2)+A(4)+A(5)+A(6)+A(19)-A(25)-A(26)+A(27)+A(28)-A(29)-A(34)+A(35)+A(36)+A(38)+A(43)-A(44)&
               &-A(45)+A(46)+2*A(47)-A(49)+2*A(50)+0.7*A(51)+A(53)+0.95*A(76)-A(79)+0.91*A(88)+1.2*A(89)+A(90)-A(98)+A(99)&
               &+A(101)+A(102)+0.84*A(103)+A(104)+A(105)+1.5*A(106)+A(107)+A(108)+A(109)+A(110)+A(111)+A(112)+1.5*A(113)&
               &+A(114)+0.5*A(132)
  Vdot(60) = -A(2)+A(6)+A(26)+A(29)-A(35)+A(37)-A(47)-A(48)-A(49)-2*A(50)-A(51)+A(53)-A(60)-A(62)-A(65)-A(72)-A(73)&
               &-A(78)-A(84)-A(87)-A(108)-A(109)-A(110)-A(111)-A(112)-A(113)-A(114)-A(138)-A(141)
  Vdot(61) = A(58)+0.03*A(68)+0.09*A(69)+0.77*A(96)-A(103)-A(110)-A(117)-A(129)
  Vdot(62) = A(63)+0.11*A(69)-A(105)-A(112)-A(119)-A(131)
  Vdot(63) = A(1)+0.11*A(2)+A(3)+A(25)-A(27)-A(28)-A(33)-A(43)-A(47)+A(48)-A(76)-A(88)-A(89)-A(90)-A(101)-A(102)-A(103)&
               &-A(104)-A(105)-A(106)-A(107)
  Vdot(64) = -A(7)-A(8)+A(23)-A(24)-A(28)-A(29)-A(30)-A(31)-A(66)-A(68)-A(69)-A(81)-A(83)-A(86)+0.4*A(118)-A(139)-A(142)
  Vdot(65) = A(5)+2*A(10)+A(12)+A(13)+A(14)+A(16)+A(17)+0.9*A(18)+0.9*A(19)+0.33*A(20)+A(30)-A(31)+A(32)+A(35)-A(39)&
               &+A(40)-2*A(41)-2*A(42)-A(43)-A(44)-A(45)+A(46)-A(51)+A(54)+A(55)+A(59)+A(60)+0.22*A(66)+A(67)+0.26*A(68)&
               &+0.22*A(69)+A(70)+A(71)+0.2*A(74)+0.55*A(75)+0.95*A(76)+0.6*A(77)+2*A(80)+0.76*A(81)+0.07*A(83)+0.1*A(86)&
               &+0.93*A(87)+0.91*A(88)+0.8*A(89)+A(90)-A(91)-A(92)-A(93)+A(100)+A(101)+A(102)+0.76*A(103)+0.5*A(106)+A(108)&
               &+A(109)+0.9*A(110)+0.5*A(113)-A(115)-A(116)-A(117)-A(118)-A(119)-A(120)-A(121)+A(122)+0.32*A(127)+0.6*A(128)&
               &+0.54*A(129)
  Vdot(66) = -A(18)+A(91)+A(93)-A(96)+A(117)+A(119)
  Vdot(67) = A(3)+A(4)+2*A(9)+A(12)+A(13)+A(18)+2*A(22)-A(30)+A(31)-A(32)-A(33)-A(34)-A(35)-A(36)-A(37)-A(38)-A(39)&
               &-A(40)+A(43)+0.7*A(51)-A(54)-A(55)-A(56)-A(57)-A(58)-A(59)-A(61)-A(63)-A(64)+0.12*A(66)-A(67)+0.33*A(68)+0.6&
               &*A(69)-A(70)-A(71)-A(74)-A(75)-A(77)-A(80)+0.08*A(81)-A(82)+0.27*A(83)-A(85)+0.27*A(86)-0.7*A(94)-0.7*A(95)&
               &-0.77*A(96)-A(97)-A(100)-A(122)-A(137)-A(140)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun_SPLIT - time derivatives of variables - Split form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      P_VAR     - Production term
!      D_VAR     - Destruction term
!      Aout      - Optional argument to return equation rate constants
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun_SPLIT ( V, F, RCT, Vdot, P_VAR, D_VAR, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
! P_VAR - Production term
  REAL(kind=dp) :: P_VAR(NVAR)
! D_VAR - Destruction term
  REAL(kind=dp) :: D_VAR(NVAR)
! Aout - Optional argument to return equation rate constants
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)


! Computation of equation rates
  A(1) = RCT(1)*V(59)
  A(2) = RCT(2)*V(60)
  A(3) = RCT(3)*V(32)
  A(4) = RCT(4)*V(38)
  A(5) = RCT(5)*V(27)
  A(6) = RCT(6)*V(21)
  A(7) = RCT(7)*V(64)
  A(8) = RCT(8)*V(64)
  A(9) = RCT(9)*V(19)
  A(10) = RCT(10)*V(47)
  A(11) = RCT(11)*V(47)
  A(12) = RCT(12)*V(31)
  A(13) = RCT(13)*V(33)
  A(14) = RCT(14)*V(54)
  A(15) = RCT(15)*V(49)
  A(16) = RCT(16)*V(53)
  A(17) = RCT(17)*V(42)
  A(18) = RCT(18)*V(66)
  A(19) = RCT(19)*V(57)
  A(20) = RCT(20)*V(56)
  A(21) = RCT(21)*V(16)*F(2)
  A(22) = RCT(22)*V(16)*F(1)
  A(23) = RCT(23)*V(37)*F(2)
  A(25) = RCT(25)*V(37)*V(59)
  A(26) = RCT(26)*V(37)*V(59)
  A(27) = RCT(27)*V(37)*V(63)
  A(28) = RCT(28)*V(63)*V(64)
  A(29) = RCT(29)*V(59)*V(64)
  A(30) = RCT(30)*V(64)*V(67)
  A(31) = RCT(31)*V(64)*V(65)
  A(32) = RCT(32)*V(67)*F(2)
  A(33) = RCT(33)*V(63)*V(67)
  A(34) = RCT(34)*V(59)*V(67)
  A(35) = RCT(35)*V(60)*V(67)
  A(36) = RCT(36)*V(32)*V(67)
  A(37) = RCT(37)*V(38)*V(67)
  A(38) = RCT(38)*V(27)*V(67)
  A(40) = RCT(40)*V(19)*V(67)
  A(41) = RCT(41)*V(65)*V(65)
  A(42) = RCT(42)*V(65)*V(65)*F(1)
  A(43) = RCT(43)*V(63)*V(65)
  A(44) = RCT(44)*V(59)*V(65)
  A(45) = RCT(45)*V(59)*V(65)
  A(46) = RCT(46)*V(27)
  A(47) = RCT(47)*V(60)*V(63)
  A(48) = RCT(48)*V(59)*V(60)
  A(49) = RCT(49)*V(59)*V(60)
  A(50) = RCT(50)*V(60)*V(60)
  A(51) = RCT(51)*V(60)*V(65)
  A(52) = RCT(52)*V(21)*F(1)
  A(53) = RCT(53)*V(21)
  A(54) = RCT(54)*V(39)*V(67)
  A(55) = RCT(55)*V(15)*V(67)
  A(56) = RCT(56)*V(23)*V(67)
  A(57) = RCT(57)*V(28)*V(67)
  A(58) = RCT(58)*V(41)*V(67)
  A(59) = RCT(59)*V(47)*V(67)
  A(60) = RCT(60)*V(47)*V(60)
  A(61) = RCT(61)*V(54)*V(67)
  A(62) = RCT(62)*V(54)*V(60)
  A(63) = RCT(63)*V(49)*V(67)
  A(64) = RCT(64)*V(53)*V(67)
  A(65) = RCT(65)*V(53)*V(60)
  A(66) = RCT(66)*V(34)*V(64)
  A(67) = RCT(67)*V(34)*V(67)
  A(68) = RCT(68)*V(45)*V(64)
  A(69) = RCT(69)*V(50)*V(64)
  A(70) = RCT(70)*V(45)*V(67)
  A(71) = RCT(71)*V(50)*V(67)
  A(72) = RCT(72)*V(45)*V(60)
  A(73) = RCT(73)*V(50)*V(60)
  A(74) = RCT(74)*V(20)*V(67)
  A(75) = RCT(75)*V(22)*V(67)
  A(76) = RCT(76)*V(29)*V(63)
  A(77) = RCT(77)*V(36)*V(67)
  A(78) = RCT(78)*V(36)*V(60)
  A(79) = RCT(79)*V(24)*V(59)
  A(80) = RCT(80)*V(42)*V(67)
  A(81) = RCT(81)*V(42)*V(64)
  A(82) = RCT(82)*V(46)*V(67)
  A(83) = RCT(83)*V(46)*V(64)
  A(84) = RCT(84)*V(46)*V(60)
  A(85) = RCT(85)*V(56)*V(67)
  A(86) = RCT(86)*V(56)*V(64)
  A(87) = RCT(87)*V(56)*V(60)
  A(88) = RCT(88)*V(43)*V(63)
  A(89) = RCT(89)*V(40)*V(63)
  A(90) = RCT(90)*V(44)*V(63)
  A(91) = RCT(91)*V(43)*V(65)
  A(92) = RCT(92)*V(40)*V(65)
  A(93) = RCT(93)*V(44)*V(65)
  A(94) = RCT(94)*V(31)*V(67)
  A(95) = RCT(95)*V(33)*V(67)
  A(96) = RCT(96)*V(66)*V(67)
  A(97) = RCT(97)*V(57)*V(67)
  A(98) = RCT(98)*V(58)*V(59)
  A(99) = RCT(99)*V(18)
  A(100) = RCT(100)*V(35)*V(67)
  A(101) = RCT(101)*V(55)*V(63)
  A(102) = RCT(102)*V(52)*V(63)
  A(103) = RCT(103)*V(61)*V(63)
  A(104) = RCT(104)*V(58)*V(63)
  A(105) = RCT(105)*V(62)*V(63)
  A(106) = RCT(106)*V(51)*V(63)
  A(107) = RCT(107)*V(48)*V(63)
  A(108) = RCT(108)*V(55)*V(60)
  A(109) = RCT(109)*V(52)*V(60)
  A(110) = RCT(110)*V(60)*V(61)
  A(111) = RCT(111)*V(58)*V(60)
  A(112) = RCT(112)*V(60)*V(62)
  A(113) = RCT(113)*V(51)*V(60)
  A(114) = RCT(114)*V(48)*V(60)
  A(115) = RCT(115)*V(55)*V(65)
  A(116) = RCT(116)*V(52)*V(65)
  A(117) = RCT(117)*V(61)*V(65)
  A(118) = RCT(118)*V(58)*V(65)
  A(119) = RCT(119)*V(62)*V(65)
  A(120) = RCT(120)*V(51)*V(65)
  A(121) = RCT(121)*V(48)*V(65)
  A(122) = RCT(122)*V(17)*V(67)
  A(123) = RCT(123)*V(30)*V(41)
  A(124) = V(2)
  A(125) = V(3)
  A(126) = V(1)
  A(127) = RCT(127)*V(55)
  A(128) = RCT(128)*V(52)
  A(129) = RCT(129)*V(61)
  A(130) = RCT(130)*V(58)
  A(131) = RCT(131)*V(62)
  A(132) = RCT(132)*V(51)
  A(133) = RCT(133)*V(43)
  A(134) = RCT(134)*V(40)
  A(135) = RCT(135)*V(44)
  A(136) = RCT(136)*V(48)
  A(137) = RCT(137)*V(25)*V(67)
  A(139) = RCT(139)*V(25)*V(64)
  A(140) = RCT(140)*V(26)*V(67)
  A(142) = RCT(142)*V(26)*V(64)

  !### Use Aout to return equation rates
  IF ( PRESENT( Aout ) ) Aout = A

! Production function
  P_VAR(1) = A(55)+A(126)
  P_VAR(2) = A(124)
  P_VAR(3) = A(125)
  P_VAR(4) = 0.52*A(66)+0.22*A(68)
  P_VAR(5) = 0.09*A(68)+0.16*A(69)+0.39*A(83)+0.46*A(86)+0.4*A(118)
  P_VAR(6) = 0.039*A(74)+0.039*A(75)+0.039*A(77)+0.039*A(78)
  P_VAR(7) = 0.108*A(74)+0.108*A(75)+0.108*A(77)+0.108*A(78)
  P_VAR(8) = 0.012*A(58)
  P_VAR(9) = 0.008*A(68)+0.008*A(69)+0.008*A(70)+0.008*A(71)+0.008*A(72)+0.008*A(73)
  P_VAR(10) = 0.0064*A(137)+0.022*A(139)
  P_VAR(11) = 0.055*A(137)+0.19*A(139)
  P_VAR(12) = 0.037*A(140)+0.13*A(142)
  P_VAR(13) = 0.056*A(140)+0.19*A(142)
  P_VAR(14) = A(121)+A(123)+A(136)
  P_VAR(15) = 0
  P_VAR(16) = A(8)
  P_VAR(17) = 0
  P_VAR(18) = A(98)
  P_VAR(19) = A(41)+A(42)
  P_VAR(20) = 0
  P_VAR(21) = A(49)
  P_VAR(22) = 0
  P_VAR(23) = 0.06*A(68)+0.08*A(69)
  P_VAR(24) = 0.4*A(77)+A(78)
  P_VAR(25) = 0
  P_VAR(26) = 0
  P_VAR(27) = A(44)
  P_VAR(28) = 0.01*A(68)+0.01*A(69)+0.2*A(128)
  P_VAR(29) = 0.8*A(74)+0.45*A(75)
  P_VAR(30) = 1.98*A(18)+1.98*A(19)+1.06*A(68)+2.26*A(69)+A(70)+2.23*A(71)+0.42*A(96)+1.68*A(103)+A(106)+1.98*A(110)&
                &+A(113)+1.25*A(129)+A(132)
  P_VAR(31) = A(115)
  P_VAR(32) = A(33)+A(45)
  P_VAR(33) = A(116)
  P_VAR(34) = 0
  P_VAR(35) = 0.03*A(68)+0.04*A(69)+0.34*A(127)
  P_VAR(36) = 0.12*A(74)+0.05*A(75)
  P_VAR(37) = A(1)+0.89*A(2)+A(7)+A(21)
  P_VAR(38) = A(34)+0.3*A(51)+2*A(52)+A(60)+A(62)+A(65)+A(78)+0.07*A(87)
  P_VAR(39) = A(10)+A(11)+A(14)+A(16)+A(17)+0.33*A(20)+A(59)+A(60)+A(65)+0.24*A(66)+0.31*A(68)+0.3*A(69)+2*A(80)+0.69&
                &*A(81)+0.07*A(83)+0.16*A(86)+0.64*A(87)+0.59*A(90)
  P_VAR(40) = A(84)
  P_VAR(41) = 1.1*A(75)+1.86*A(87)+0.18*A(88)+1.6*A(89)+2*A(92)+2*A(134)
  P_VAR(42) = 0.95*A(76)+0.3*A(77)
  P_VAR(43) = A(82)
  P_VAR(44) = 0.5*A(85)
  P_VAR(45) = 0
  P_VAR(46) = 0
  P_VAR(47) = A(12)+0.2*A(20)+A(66)+1.56*A(67)+0.57*A(68)+A(70)+A(80)+0.7*A(81)+0.6*A(83)+0.15*A(86)+0.28*A(87)+0.63&
                &*A(88)+0.25*A(90)+0.3*A(94)+A(100)+A(101)+A(105)+0.5*A(106)+A(108)+A(112)+0.5*A(113)+0.66*A(127)+0.7*A(131)&
                &+0.5*A(132)
  P_VAR(48) = 0.4*A(18)+0.41*A(19)+A(64)+A(67)+A(70)+A(71)+0.08*A(74)+0.5*A(75)+0.6*A(77)+A(80)+0.03*A(81)+0.08*A(82)&
                &+0.2*A(83)+0.2*A(85)+0.07*A(86)+0.93*A(87)+0.34*A(103)+0.4*A(110)+0.24*A(129)
  P_VAR(49) = 0.74*A(18)+0.74*A(19)+0.03*A(20)+0.07*A(69)+0.23*A(71)+0.09*A(86)+0.63*A(90)+0.62*A(103)+0.74*A(110)+0.57&
                &*A(129)+0.15*A(131)+0.5*A(135)
  P_VAR(50) = 0
  P_VAR(51) = A(72)+A(73)+A(97)
  P_VAR(52) = 0.1*A(18)+0.1*A(19)+A(57)+0.06*A(68)+0.05*A(69)+0.7*A(95)+0.08*A(103)+0.1*A(110)+0.06*A(129)
  P_VAR(53) = 0.04*A(68)+0.07*A(69)+0.8*A(75)+0.2*A(81)+0.85*A(86)+0.34*A(90)+0.19*A(96)+0.15*A(131)
  P_VAR(54) = A(13)+0.3*A(18)+0.3*A(19)+0.07*A(20)+0.22*A(67)+0.47*A(68)+1.03*A(69)+A(70)+1.77*A(71)+0.03*A(81)+0.15&
                &*A(83)+0.02*A(86)+0.28*A(87)+0.8*A(89)+0.55*A(90)+0.3*A(95)+0.04*A(96)+A(102)+0.25*A(103)+0.5*A(106)+A(109)&
                &+0.3*A(110)+0.5*A(113)+A(122)+0.8*A(128)+0.21*A(129)+0.5*A(132)+A(134)+0.5*A(135)
  P_VAR(55) = A(14)+A(15)+0.7*A(20)+A(56)+0.07*A(68)+0.1*A(69)+0.05*A(86)+0.7*A(94)+A(104)+A(111)+A(130)
  P_VAR(56) = 0.65*A(83)+0.91*A(88)+0.2*A(89)+A(133)
  P_VAR(57) = 0.05*A(76)+A(79)+0.93*A(87)+0.09*A(88)+0.8*A(89)+A(92)+0.16*A(103)+0.5*A(106)+0.5*A(113)+A(120)+0.5*A(132)&
                &+A(134)
  P_VAR(58) = A(15)+A(16)+A(17)+0.97*A(20)+A(61)+A(62)+A(64)+A(65)+0.13*A(68)+0.19*A(69)+A(80)+0.62*A(81)+0.2*A(83)+0.5&
                &*A(85)+0.11*A(86)+0.07*A(87)+A(99)+A(105)+A(112)+0.7*A(131)
  P_VAR(59) = 0.89*A(2)+A(4)+A(5)+A(6)+A(19)+A(27)+A(28)+A(35)+A(36)+A(38)+A(43)+A(46)+2*A(47)+A(48)+2*A(50)+0.7*A(51)&
                &+A(53)+0.95*A(76)+0.91*A(88)+1.2*A(89)+A(90)+A(99)+A(101)+A(102)+0.84*A(103)+A(104)+A(105)+1.5*A(106)&
                &+A(107)+A(108)+A(109)+A(110)+A(111)+A(112)+1.5*A(113)+A(114)+0.5*A(132)
  P_VAR(60) = A(6)+A(26)+A(29)+A(37)+A(53)
  P_VAR(61) = A(58)+0.03*A(68)+0.09*A(69)+0.77*A(96)
  P_VAR(62) = A(63)+0.11*A(69)
  P_VAR(63) = A(1)+0.11*A(2)+A(3)+A(25)+A(48)
  P_VAR(64) = A(23)+0.4*A(118)
  P_VAR(65) = A(5)+2*A(10)+A(12)+A(13)+A(14)+A(16)+A(17)+0.9*A(18)+0.9*A(19)+0.33*A(20)+A(30)+A(32)+A(35)+A(40)+A(46)&
                &+A(54)+A(55)+A(59)+A(60)+0.22*A(66)+A(67)+0.26*A(68)+0.22*A(69)+A(70)+A(71)+0.2*A(74)+0.55*A(75)+0.95*A(76)&
                &+0.6*A(77)+2*A(80)+0.76*A(81)+0.07*A(83)+0.1*A(86)+0.93*A(87)+0.91*A(88)+0.8*A(89)+A(90)+A(100)+A(101)&
                &+A(102)+0.76*A(103)+0.5*A(106)+A(108)+A(109)+0.9*A(110)+0.5*A(113)+A(122)+0.32*A(127)+0.6*A(128)+0.54&
                &*A(129)
  P_VAR(66) = A(91)+A(93)+A(117)+A(119)
  P_VAR(67) = A(3)+A(4)+2*A(9)+A(12)+A(13)+A(18)+2*A(22)+A(31)+A(43)+0.7*A(51)+0.12*A(66)+0.33*A(68)+0.6*A(69)+0.08&
                &*A(81)+0.27*A(83)+0.27*A(86)+0.3*A(94)+0.3*A(95)+0.23*A(96)

! Destruction function
  D_VAR(1) = 1
  D_VAR(2) = 1
  D_VAR(3) = 1
  D_VAR(4) = 0
  D_VAR(5) = 0
  D_VAR(6) = 0
  D_VAR(7) = 0
  D_VAR(8) = 0
  D_VAR(9) = 0
  D_VAR(10) = 0
  D_VAR(11) = 0
  D_VAR(12) = 0
  D_VAR(13) = 0
  D_VAR(14) = 0
  D_VAR(15) = RCT(55)*V(67)
  D_VAR(16) = RCT(21)*F(2)+RCT(22)*F(1)
  D_VAR(17) = RCT(122)*V(67)
  D_VAR(18) = RCT(99)
  D_VAR(19) = RCT(9)+RCT(40)*V(67)
  D_VAR(20) = RCT(74)*V(67)
  D_VAR(21) = RCT(6)+RCT(52)*F(1)+RCT(53)
  D_VAR(22) = RCT(75)*V(67)
  D_VAR(23) = RCT(56)*V(67)
  D_VAR(24) = RCT(79)*V(59)
  D_VAR(25) = RCT(137)*V(67)+RCT(138)*V(60)+RCT(139)*V(64)
  D_VAR(26) = RCT(140)*V(67)+RCT(141)*V(60)+RCT(142)*V(64)
  D_VAR(27) = RCT(5)+RCT(38)*V(67)+RCT(46)
  D_VAR(28) = RCT(57)*V(67)
  D_VAR(29) = RCT(76)*V(63)
  D_VAR(30) = RCT(123)*V(41)
  D_VAR(31) = RCT(12)+RCT(94)*V(67)
  D_VAR(32) = RCT(3)+RCT(36)*V(67)
  D_VAR(33) = RCT(13)+RCT(95)*V(67)
  D_VAR(34) = RCT(66)*V(64)+RCT(67)*V(67)
  D_VAR(35) = RCT(100)*V(67)
  D_VAR(36) = RCT(77)*V(67)+RCT(78)*V(60)
  D_VAR(37) = RCT(23)*F(2)+RCT(24)*V(64)+RCT(25)*V(59)+RCT(26)*V(59)+RCT(27)*V(63)
  D_VAR(38) = RCT(4)+RCT(37)*V(67)
  D_VAR(39) = RCT(54)*V(67)
  D_VAR(40) = RCT(89)*V(63)+RCT(92)*V(65)+RCT(134)
  D_VAR(41) = RCT(58)*V(67)+RCT(123)*V(30)
  D_VAR(42) = RCT(17)+RCT(80)*V(67)+RCT(81)*V(64)
  D_VAR(43) = RCT(88)*V(63)+RCT(91)*V(65)+RCT(133)
  D_VAR(44) = RCT(90)*V(63)+RCT(93)*V(65)+RCT(135)
  D_VAR(45) = RCT(68)*V(64)+RCT(70)*V(67)+RCT(72)*V(60)
  D_VAR(46) = RCT(82)*V(67)+RCT(83)*V(64)+RCT(84)*V(60)
  D_VAR(47) = RCT(10)+RCT(11)+RCT(59)*V(67)+RCT(60)*V(60)
  D_VAR(48) = RCT(107)*V(63)+RCT(114)*V(60)+RCT(121)*V(65)+RCT(136)
  D_VAR(49) = RCT(15)+RCT(63)*V(67)
  D_VAR(50) = RCT(69)*V(64)+RCT(71)*V(67)+RCT(73)*V(60)
  D_VAR(51) = RCT(106)*V(63)+RCT(113)*V(60)+RCT(120)*V(65)+RCT(132)
  D_VAR(52) = RCT(102)*V(63)+RCT(109)*V(60)+RCT(116)*V(65)+RCT(128)
  D_VAR(53) = RCT(16)+RCT(64)*V(67)+RCT(65)*V(60)
  D_VAR(54) = RCT(14)+RCT(61)*V(67)+RCT(62)*V(60)
  D_VAR(55) = RCT(101)*V(63)+RCT(108)*V(60)+RCT(115)*V(65)+RCT(127)
  D_VAR(56) = RCT(20)+RCT(85)*V(67)+RCT(86)*V(64)+RCT(87)*V(60)
  D_VAR(57) = RCT(19)+RCT(97)*V(67)
  D_VAR(58) = RCT(98)*V(59)+RCT(104)*V(63)+RCT(111)*V(60)+RCT(118)*V(65)+RCT(130)
  D_VAR(59) = RCT(1)+RCT(25)*V(37)+RCT(26)*V(37)+RCT(29)*V(64)+RCT(34)*V(67)+RCT(44)*V(65)+RCT(45)*V(65)+RCT(48)*V(60)&
                &+RCT(49)*V(60)+RCT(79)*V(24)+RCT(98)*V(58)
  D_VAR(60) = RCT(2)+RCT(35)*V(67)+RCT(47)*V(63)+RCT(48)*V(59)+RCT(49)*V(59)+RCT(50)*2*V(60)+RCT(51)*V(65)+RCT(60)*V(47)&
                &+RCT(62)*V(54)+RCT(65)*V(53)+RCT(72)*V(45)+RCT(73)*V(50)+RCT(78)*V(36)+RCT(84)*V(46)+RCT(87)*V(56)+RCT(108)&
                &*V(55)+RCT(109)*V(52)+RCT(110)*V(61)+RCT(111)*V(58)+RCT(112)*V(62)+RCT(113)*V(51)+RCT(114)*V(48)+RCT(138)&
                &*V(25)+RCT(141)*V(26)
  D_VAR(61) = RCT(103)*V(63)+RCT(110)*V(60)+RCT(117)*V(65)+RCT(129)
  D_VAR(62) = RCT(105)*V(63)+RCT(112)*V(60)+RCT(119)*V(65)+RCT(131)
  D_VAR(63) = RCT(27)*V(37)+RCT(28)*V(64)+RCT(33)*V(67)+RCT(43)*V(65)+RCT(47)*V(60)+RCT(76)*V(29)+RCT(88)*V(43)+RCT(89)&
                &*V(40)+RCT(90)*V(44)+RCT(101)*V(55)+RCT(102)*V(52)+RCT(103)*V(61)+RCT(104)*V(58)+RCT(105)*V(62)+RCT(106)&
                &*V(51)+RCT(107)*V(48)
  D_VAR(64) = RCT(7)+RCT(8)+RCT(24)*V(37)+RCT(28)*V(63)+RCT(29)*V(59)+RCT(30)*V(67)+RCT(31)*V(65)+RCT(66)*V(34)+RCT(68)&
                &*V(45)+RCT(69)*V(50)+RCT(81)*V(42)+RCT(83)*V(46)+RCT(86)*V(56)+RCT(139)*V(25)+RCT(142)*V(26)
  D_VAR(65) = RCT(31)*V(64)+RCT(39)*V(67)+RCT(41)*2*V(65)+RCT(42)*2*V(65)*F(1)+RCT(43)*V(63)+RCT(44)*V(59)+RCT(45)*V(59)&
                &+RCT(51)*V(60)+RCT(91)*V(43)+RCT(92)*V(40)+RCT(93)*V(44)+RCT(115)*V(55)+RCT(116)*V(52)+RCT(117)*V(61)&
                &+RCT(118)*V(58)+RCT(119)*V(62)+RCT(120)*V(51)+RCT(121)*V(48)
  D_VAR(66) = RCT(18)+RCT(96)*V(67)
  D_VAR(67) = RCT(30)*V(64)+RCT(32)*F(2)+RCT(33)*V(63)+RCT(34)*V(59)+RCT(35)*V(60)+RCT(36)*V(32)+RCT(37)*V(38)+RCT(38)&
                &*V(27)+RCT(39)*V(65)+RCT(40)*V(19)+RCT(54)*V(39)+RCT(55)*V(15)+RCT(56)*V(23)+RCT(57)*V(28)+RCT(58)*V(41)&
                &+RCT(59)*V(47)+RCT(61)*V(54)+RCT(63)*V(49)+RCT(64)*V(53)+RCT(67)*V(34)+RCT(70)*V(45)+RCT(71)*V(50)+RCT(74)&
                &*V(20)+RCT(75)*V(22)+RCT(77)*V(36)+RCT(80)*V(42)+RCT(82)*V(46)+RCT(85)*V(56)+RCT(94)*V(31)+RCT(95)*V(33)&
                &+RCT(96)*V(66)+RCT(97)*V(57)+RCT(100)*V(35)+RCT(122)*V(17)+RCT(137)*V(25)+RCT(140)*V(26)

  Vdot = P_VAR - D_VAR*V
      
END SUBROUTINE Fun_SPLIT

! End of Fun_SPLIT function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! CalcStoichNum - calculate stoichiometric numbers
!   Arguments :
!      StoichNum - Stoichiometric numbers
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE CalcStoichNum ( StoichNum )

! StoichNum - Stoichiometric numbers
  REAL(kind=dp) :: StoichNum(NVAR,NREACT)

  StoichNum(:,:) = 0.
  StoichNum(1,55) = 1
  StoichNum(4,66) = 0.52
  StoichNum(4,68) = 0.22
  StoichNum(5,68) = 0.09
  StoichNum(5,69) = 0.16
  StoichNum(5,83) = 0.39
  StoichNum(5,86) = 0.46
  StoichNum(5,118) = 0.4
  StoichNum(6,74) = 0.039
  StoichNum(6,75) = 0.039
  StoichNum(6,77) = 0.039
  StoichNum(6,78) = 0.039
  StoichNum(7,74) = 0.108
  StoichNum(7,75) = 0.108
  StoichNum(7,77) = 0.108
  StoichNum(7,78) = 0.108
  StoichNum(8,58) = 0.012
  StoichNum(9,68) = 0.008
  StoichNum(9,69) = 0.008
  StoichNum(9,70) = 0.008
  StoichNum(9,71) = 0.008
  StoichNum(9,72) = 0.008
  StoichNum(9,73) = 0.008
  StoichNum(10,137) = 0.0064
  StoichNum(10,139) = 0.022
  StoichNum(11,137) = 0.055
  StoichNum(11,139) = 0.19
  StoichNum(12,140) = 0.037
  StoichNum(12,142) = 0.13
  StoichNum(13,140) = 0.056
  StoichNum(13,142) = 0.19
  StoichNum(14,121) = 1
  StoichNum(14,123) = 1
  StoichNum(14,136) = 1
  StoichNum(15,55) = -1
  StoichNum(16,8) = 1
  StoichNum(16,21) = -1
  StoichNum(16,22) = -1
  StoichNum(17,122) = -1
  StoichNum(18,98) = 1
  StoichNum(18,99) = -1
  StoichNum(19,9) = -1
  StoichNum(19,40) = -1
  StoichNum(19,41) = 1
  StoichNum(19,42) = 1
  StoichNum(20,74) = -1
  StoichNum(21,6) = -1
  StoichNum(21,49) = 1
  StoichNum(21,52) = -1
  StoichNum(21,53) = -1
  StoichNum(22,75) = -1
  StoichNum(23,56) = -1
  StoichNum(23,68) = 0.06
  StoichNum(23,69) = 0.08
  StoichNum(24,77) = 0.4
  StoichNum(24,78) = 1
  StoichNum(24,79) = -1
  StoichNum(25,137) = -1
  StoichNum(25,138) = -1
  StoichNum(25,139) = -1
  StoichNum(26,140) = -1
  StoichNum(26,141) = -1
  StoichNum(26,142) = -1
  StoichNum(27,5) = -1
  StoichNum(27,38) = -1
  StoichNum(27,44) = 1
  StoichNum(27,46) = -1
  StoichNum(28,57) = -1
  StoichNum(28,68) = 0.01
  StoichNum(28,69) = 0.01
  StoichNum(28,128) = 0.2
  StoichNum(29,74) = 0.8
  StoichNum(29,75) = 0.45
  StoichNum(29,76) = -1
  StoichNum(30,18) = 1.98
  StoichNum(30,19) = 1.98
  StoichNum(30,68) = 1.06
  StoichNum(30,69) = 2.26
  StoichNum(30,70) = 1
  StoichNum(30,71) = 2.23
  StoichNum(30,96) = 0.42
  StoichNum(30,103) = 1.68
  StoichNum(30,106) = 1
  StoichNum(30,110) = 1.98
  StoichNum(30,113) = 1
  StoichNum(30,123) = -1
  StoichNum(30,129) = 1.25
  StoichNum(30,132) = 1
  StoichNum(31,12) = -1
  StoichNum(31,94) = -1
  StoichNum(31,115) = 1
  StoichNum(32,3) = -1
  StoichNum(32,33) = 1
  StoichNum(32,36) = -1
  StoichNum(32,45) = 1
  StoichNum(33,13) = -1
  StoichNum(33,95) = -1
  StoichNum(33,116) = 1
  StoichNum(34,66) = -1
  StoichNum(34,67) = -1
  StoichNum(35,68) = 0.03
  StoichNum(35,69) = 0.04
  StoichNum(35,100) = -1
  StoichNum(35,127) = 0.34
  StoichNum(36,74) = 0.12
  StoichNum(36,75) = 0.05
  StoichNum(36,77) = -1
  StoichNum(36,78) = -1
  StoichNum(37,1) = 1
  StoichNum(37,2) = 0.89
  StoichNum(37,7) = 1
  StoichNum(37,21) = 1
  StoichNum(37,23) = -1
  StoichNum(37,24) = -1
  StoichNum(37,25) = -1
  StoichNum(37,26) = -1
  StoichNum(37,27) = -1
  StoichNum(38,4) = -1
  StoichNum(38,34) = 1
  StoichNum(38,37) = -1
  StoichNum(38,51) = 0.3
  StoichNum(38,52) = 2
  StoichNum(38,60) = 1
  StoichNum(38,62) = 1
  StoichNum(38,65) = 1
  StoichNum(38,78) = 1
  StoichNum(38,87) = 0.07
  StoichNum(39,10) = 1
  StoichNum(39,11) = 1
  StoichNum(39,14) = 1
  StoichNum(39,16) = 1
  StoichNum(39,17) = 1
  StoichNum(39,20) = 0.33
  StoichNum(39,54) = -1
  StoichNum(39,59) = 1
  StoichNum(39,60) = 1
  StoichNum(39,65) = 1
  StoichNum(39,66) = 0.24
  StoichNum(39,68) = 0.31
  StoichNum(39,69) = 0.3
  StoichNum(39,80) = 2
  StoichNum(39,81) = 0.69
  StoichNum(39,83) = 0.07
  StoichNum(39,86) = 0.16
  StoichNum(39,87) = 0.64
  StoichNum(39,90) = 0.59
  StoichNum(40,84) = 1
  StoichNum(40,89) = -1
  StoichNum(40,92) = -1
  StoichNum(40,134) = -1
  StoichNum(41,58) = -1
  StoichNum(41,75) = 1.1
  StoichNum(41,87) = 1.86
  StoichNum(41,88) = 0.18
  StoichNum(41,89) = 1.6
  StoichNum(41,92) = 2
  StoichNum(41,123) = -1
  StoichNum(41,134) = 2
  StoichNum(42,17) = -1
  StoichNum(42,76) = 0.95
  StoichNum(42,77) = 0.3
  StoichNum(42,80) = -1
  StoichNum(42,81) = -1
  StoichNum(43,82) = 1
  StoichNum(43,88) = -1
  StoichNum(43,91) = -1
  StoichNum(43,133) = -1
  StoichNum(44,85) = 0.5
  StoichNum(44,90) = -1
  StoichNum(44,93) = -1
  StoichNum(44,135) = -1
  StoichNum(45,68) = -1
  StoichNum(45,70) = -1
  StoichNum(45,72) = -1
  StoichNum(46,82) = -1
  StoichNum(46,83) = -1
  StoichNum(46,84) = -1
  StoichNum(47,10) = -1
  StoichNum(47,11) = -1
  StoichNum(47,12) = 1
  StoichNum(47,20) = 0.2
  StoichNum(47,59) = -1
  StoichNum(47,60) = -1
  StoichNum(47,66) = 1
  StoichNum(47,67) = 1.56
  StoichNum(47,68) = 0.57
  StoichNum(47,70) = 1
  StoichNum(47,80) = 1
  StoichNum(47,81) = 0.7
  StoichNum(47,83) = 0.6
  StoichNum(47,86) = 0.15
  StoichNum(47,87) = 0.28
  StoichNum(47,88) = 0.63
  StoichNum(47,90) = 0.25
  StoichNum(47,94) = 0.3
  StoichNum(47,100) = 1
  StoichNum(47,101) = 1
  StoichNum(47,105) = 1
  StoichNum(47,106) = 0.5
  StoichNum(47,108) = 1
  StoichNum(47,112) = 1
  StoichNum(47,113) = 0.5
  StoichNum(47,127) = 0.66
  StoichNum(47,131) = 0.7
  StoichNum(47,132) = 0.5
  StoichNum(48,18) = 0.4
  StoichNum(48,19) = 0.41
  StoichNum(48,64) = 1
  StoichNum(48,67) = 1
  StoichNum(48,70) = 1
  StoichNum(48,71) = 1
  StoichNum(48,74) = 0.08
  StoichNum(48,75) = 0.5
  StoichNum(48,77) = 0.6
  StoichNum(48,80) = 1
  StoichNum(48,81) = 0.03
  StoichNum(48,82) = 0.08
  StoichNum(48,83) = 0.2
  StoichNum(48,85) = 0.2
  StoichNum(48,86) = 0.07
  StoichNum(48,87) = 0.93
  StoichNum(48,103) = 0.34
  StoichNum(48,107) = -1
  StoichNum(48,110) = 0.4
  StoichNum(48,114) = -1
  StoichNum(48,121) = -1
  StoichNum(48,129) = 0.24
  StoichNum(48,136) = -1
  StoichNum(49,15) = -1
  StoichNum(49,18) = 0.74
  StoichNum(49,19) = 0.74
  StoichNum(49,20) = 0.03
  StoichNum(49,63) = -1
  StoichNum(49,69) = 0.07
  StoichNum(49,71) = 0.23
  StoichNum(49,86) = 0.09
  StoichNum(49,90) = 0.63
  StoichNum(49,103) = 0.62
  StoichNum(49,110) = 0.74
  StoichNum(49,129) = 0.57
  StoichNum(49,131) = 0.15
  StoichNum(49,135) = 0.5
  StoichNum(50,69) = -1
  StoichNum(50,71) = -1
  StoichNum(50,73) = -1
  StoichNum(51,72) = 1
  StoichNum(51,73) = 1
  StoichNum(51,97) = 1
  StoichNum(51,106) = -1
  StoichNum(51,113) = -1
  StoichNum(51,120) = -1
  StoichNum(51,132) = -1
  StoichNum(52,18) = 0.1
  StoichNum(52,19) = 0.1
  StoichNum(52,57) = 1
  StoichNum(52,68) = 0.06
  StoichNum(52,69) = 0.05
  StoichNum(52,95) = 0.7
  StoichNum(52,102) = -1
  StoichNum(52,103) = 0.08
  StoichNum(52,109) = -1
  StoichNum(52,110) = 0.1
  StoichNum(52,116) = -1
  StoichNum(52,128) = -1
  StoichNum(52,129) = 0.06
  StoichNum(53,16) = -1
  StoichNum(53,64) = -1
  StoichNum(53,65) = -1
  StoichNum(53,68) = 0.04
  StoichNum(53,69) = 0.07
  StoichNum(53,75) = 0.8
  StoichNum(53,81) = 0.2
  StoichNum(53,86) = 0.85
  StoichNum(53,90) = 0.34
  StoichNum(53,96) = 0.19
  StoichNum(53,131) = 0.15
  StoichNum(54,13) = 1
  StoichNum(54,14) = -1
  StoichNum(54,18) = 0.3
  StoichNum(54,19) = 0.3
  StoichNum(54,20) = 0.07
  StoichNum(54,61) = -1
  StoichNum(54,62) = -1
  StoichNum(54,67) = 0.22
  StoichNum(54,68) = 0.47
  StoichNum(54,69) = 1.03
  StoichNum(54,70) = 1
  StoichNum(54,71) = 1.77
  StoichNum(54,81) = 0.03
  StoichNum(54,83) = 0.15
  StoichNum(54,86) = 0.02
  StoichNum(54,87) = 0.28
  StoichNum(54,89) = 0.8
  StoichNum(54,90) = 0.55
  StoichNum(54,95) = 0.3
  StoichNum(54,96) = 0.04
  StoichNum(54,102) = 1
  StoichNum(54,103) = 0.25
  StoichNum(54,106) = 0.5
  StoichNum(54,109) = 1
  StoichNum(54,110) = 0.3
  StoichNum(54,113) = 0.5
  StoichNum(54,122) = 1
  StoichNum(54,128) = 0.8
  StoichNum(54,129) = 0.21
  StoichNum(54,132) = 0.5
  StoichNum(54,134) = 1
  StoichNum(54,135) = 0.5
  StoichNum(55,14) = 1
  StoichNum(55,15) = 1
  StoichNum(55,20) = 0.7
  StoichNum(55,56) = 1
  StoichNum(55,68) = 0.07
  StoichNum(55,69) = 0.1
  StoichNum(55,86) = 0.05
  StoichNum(55,94) = 0.7
  StoichNum(55,101) = -1
  StoichNum(55,104) = 1
  StoichNum(55,108) = -1
  StoichNum(55,111) = 1
  StoichNum(55,115) = -1
  StoichNum(55,127) = -1
  StoichNum(55,130) = 1
  StoichNum(56,20) = -1
  StoichNum(56,83) = 0.65
  StoichNum(56,85) = -1
  StoichNum(56,86) = -1
  StoichNum(56,87) = -1
  StoichNum(56,88) = 0.91
  StoichNum(56,89) = 0.2
  StoichNum(56,133) = 1
  StoichNum(57,19) = -1
  StoichNum(57,76) = 0.05
  StoichNum(57,79) = 1
  StoichNum(57,87) = 0.93
  StoichNum(57,88) = 0.09
  StoichNum(57,89) = 0.8
  StoichNum(57,92) = 1
  StoichNum(57,97) = -1
  StoichNum(57,103) = 0.16
  StoichNum(57,106) = 0.5
  StoichNum(57,113) = 0.5
  StoichNum(57,120) = 1
  StoichNum(57,132) = 0.5
  StoichNum(57,134) = 1
  StoichNum(58,15) = 1
  StoichNum(58,16) = 1
  StoichNum(58,17) = 1
  StoichNum(58,20) = 0.97
  StoichNum(58,61) = 1
  StoichNum(58,62) = 1
  StoichNum(58,64) = 1
  StoichNum(58,65) = 1
  StoichNum(58,68) = 0.13
  StoichNum(58,69) = 0.19
  StoichNum(58,80) = 1
  StoichNum(58,81) = 0.62
  StoichNum(58,83) = 0.2
  StoichNum(58,85) = 0.5
  StoichNum(58,86) = 0.11
  StoichNum(58,87) = 0.07
  StoichNum(58,98) = -1
  StoichNum(58,99) = 1
  StoichNum(58,104) = -1
  StoichNum(58,105) = 1
  StoichNum(58,111) = -1
  StoichNum(58,112) = 1
  StoichNum(58,118) = -1
  StoichNum(58,130) = -1
  StoichNum(58,131) = 0.7
  StoichNum(59,1) = -1
  StoichNum(59,2) = 0.89
  StoichNum(59,4) = 1
  StoichNum(59,5) = 1
  StoichNum(59,6) = 1
  StoichNum(59,19) = 1
  StoichNum(59,25) = -1
  StoichNum(59,26) = -1
  StoichNum(59,27) = 1
  StoichNum(59,28) = 1
  StoichNum(59,29) = -1
  StoichNum(59,34) = -1
  StoichNum(59,35) = 1
  StoichNum(59,36) = 1
  StoichNum(59,38) = 1
  StoichNum(59,43) = 1
  StoichNum(59,44) = -1
  StoichNum(59,45) = -1
  StoichNum(59,46) = 1
  StoichNum(59,47) = 2
  StoichNum(59,49) = -1
  StoichNum(59,50) = 2
  StoichNum(59,51) = 0.7
  StoichNum(59,53) = 1
  StoichNum(59,76) = 0.95
  StoichNum(59,79) = -1
  StoichNum(59,88) = 0.91
  StoichNum(59,89) = 1.2
  StoichNum(59,90) = 1
  StoichNum(59,98) = -1
  StoichNum(59,99) = 1
  StoichNum(59,101) = 1
  StoichNum(59,102) = 1
  StoichNum(59,103) = 0.84
  StoichNum(59,104) = 1
  StoichNum(59,105) = 1
  StoichNum(59,106) = 1.5
  StoichNum(59,107) = 1
  StoichNum(59,108) = 1
  StoichNum(59,109) = 1
  StoichNum(59,110) = 1
  StoichNum(59,111) = 1
  StoichNum(59,112) = 1
  StoichNum(59,113) = 1.5
  StoichNum(59,114) = 1
  StoichNum(59,132) = 0.5
  StoichNum(60,2) = -1
  StoichNum(60,6) = 1
  StoichNum(60,26) = 1
  StoichNum(60,29) = 1
  StoichNum(60,35) = -1
  StoichNum(60,37) = 1
  StoichNum(60,47) = -1
  StoichNum(60,48) = -1
  StoichNum(60,49) = -1
  StoichNum(60,50) = -2
  StoichNum(60,51) = -1
  StoichNum(60,53) = 1
  StoichNum(60,60) = -1
  StoichNum(60,62) = -1
  StoichNum(60,65) = -1
  StoichNum(60,72) = -1
  StoichNum(60,73) = -1
  StoichNum(60,78) = -1
  StoichNum(60,84) = -1
  StoichNum(60,87) = -1
  StoichNum(60,108) = -1
  StoichNum(60,109) = -1
  StoichNum(60,110) = -1
  StoichNum(60,111) = -1
  StoichNum(60,112) = -1
  StoichNum(60,113) = -1
  StoichNum(60,114) = -1
  StoichNum(60,138) = -1
  StoichNum(60,141) = -1
  StoichNum(61,58) = 1
  StoichNum(61,68) = 0.03
  StoichNum(61,69) = 0.09
  StoichNum(61,96) = 0.77
  StoichNum(61,103) = -1
  StoichNum(61,110) = -1
  StoichNum(61,117) = -1
  StoichNum(61,129) = -1
  StoichNum(62,63) = 1
  StoichNum(62,69) = 0.11
  StoichNum(62,105) = -1
  StoichNum(62,112) = -1
  StoichNum(62,119) = -1
  StoichNum(62,131) = -1
  StoichNum(63,1) = 1
  StoichNum(63,2) = 0.11
  StoichNum(63,3) = 1
  StoichNum(63,25) = 1
  StoichNum(63,27) = -1
  StoichNum(63,28) = -1
  StoichNum(63,33) = -1
  StoichNum(63,43) = -1
  StoichNum(63,47) = -1
  StoichNum(63,48) = 1
  StoichNum(63,76) = -1
  StoichNum(63,88) = -1
  StoichNum(63,89) = -1
  StoichNum(63,90) = -1
  StoichNum(63,101) = -1
  StoichNum(63,102) = -1
  StoichNum(63,103) = -1
  StoichNum(63,104) = -1
  StoichNum(63,105) = -1
  StoichNum(63,106) = -1
  StoichNum(63,107) = -1
  StoichNum(64,7) = -1
  StoichNum(64,8) = -1
  StoichNum(64,23) = 1
  StoichNum(64,24) = -1
  StoichNum(64,28) = -1
  StoichNum(64,29) = -1
  StoichNum(64,30) = -1
  StoichNum(64,31) = -1
  StoichNum(64,66) = -1
  StoichNum(64,68) = -1
  StoichNum(64,69) = -1
  StoichNum(64,81) = -1
  StoichNum(64,83) = -1
  StoichNum(64,86) = -1
  StoichNum(64,118) = 0.4
  StoichNum(64,139) = -1
  StoichNum(64,142) = -1
  StoichNum(65,5) = 1
  StoichNum(65,10) = 2
  StoichNum(65,12) = 1
  StoichNum(65,13) = 1
  StoichNum(65,14) = 1
  StoichNum(65,16) = 1
  StoichNum(65,17) = 1
  StoichNum(65,18) = 0.9
  StoichNum(65,19) = 0.9
  StoichNum(65,20) = 0.33
  StoichNum(65,30) = 1
  StoichNum(65,31) = -1
  StoichNum(65,32) = 1
  StoichNum(65,35) = 1
  StoichNum(65,39) = -1
  StoichNum(65,40) = 1
  StoichNum(65,41) = -2
  StoichNum(65,42) = -2
  StoichNum(65,43) = -1
  StoichNum(65,44) = -1
  StoichNum(65,45) = -1
  StoichNum(65,46) = 1
  StoichNum(65,51) = -1
  StoichNum(65,54) = 1
  StoichNum(65,55) = 1
  StoichNum(65,59) = 1
  StoichNum(65,60) = 1
  StoichNum(65,66) = 0.22
  StoichNum(65,67) = 1
  StoichNum(65,68) = 0.26
  StoichNum(65,69) = 0.22
  StoichNum(65,70) = 1
  StoichNum(65,71) = 1
  StoichNum(65,74) = 0.2
  StoichNum(65,75) = 0.55
  StoichNum(65,76) = 0.95
  StoichNum(65,77) = 0.6
  StoichNum(65,80) = 2
  StoichNum(65,81) = 0.76
  StoichNum(65,83) = 0.07
  StoichNum(65,86) = 0.1
  StoichNum(65,87) = 0.93
  StoichNum(65,88) = 0.91
  StoichNum(65,89) = 0.8
  StoichNum(65,90) = 1
  StoichNum(65,91) = -1
  StoichNum(65,92) = -1
  StoichNum(65,93) = -1
  StoichNum(65,100) = 1
  StoichNum(65,101) = 1
  StoichNum(65,102) = 1
  StoichNum(65,103) = 0.76
  StoichNum(65,106) = 0.5
  StoichNum(65,108) = 1
  StoichNum(65,109) = 1
  StoichNum(65,110) = 0.9
  StoichNum(65,113) = 0.5
  StoichNum(65,115) = -1
  StoichNum(65,116) = -1
  StoichNum(65,117) = -1
  StoichNum(65,118) = -1
  StoichNum(65,119) = -1
  StoichNum(65,120) = -1
  StoichNum(65,121) = -1
  StoichNum(65,122) = 1
  StoichNum(65,127) = 0.32
  StoichNum(65,128) = 0.6
  StoichNum(65,129) = 0.54
  StoichNum(66,18) = -1
  StoichNum(66,91) = 1
  StoichNum(66,93) = 1
  StoichNum(66,96) = -1
  StoichNum(66,117) = 1
  StoichNum(66,119) = 1
  StoichNum(67,3) = 1
  StoichNum(67,4) = 1
  StoichNum(67,9) = 2
  StoichNum(67,12) = 1
  StoichNum(67,13) = 1
  StoichNum(67,18) = 1
  StoichNum(67,22) = 2
  StoichNum(67,30) = -1
  StoichNum(67,31) = 1
  StoichNum(67,32) = -1
  StoichNum(67,33) = -1
  StoichNum(67,34) = -1
  StoichNum(67,35) = -1
  StoichNum(67,36) = -1
  StoichNum(67,37) = -1
  StoichNum(67,38) = -1
  StoichNum(67,39) = -1
  StoichNum(67,40) = -1
  StoichNum(67,43) = 1
  StoichNum(67,51) = 0.7
  StoichNum(67,54) = -1
  StoichNum(67,55) = -1
  StoichNum(67,56) = -1
  StoichNum(67,57) = -1
  StoichNum(67,58) = -1
  StoichNum(67,59) = -1
  StoichNum(67,61) = -1
  StoichNum(67,63) = -1
  StoichNum(67,64) = -1
  StoichNum(67,66) = 0.12
  StoichNum(67,67) = -1
  StoichNum(67,68) = 0.33
  StoichNum(67,69) = 0.6
  StoichNum(67,70) = -1
  StoichNum(67,71) = -1
  StoichNum(67,74) = -1
  StoichNum(67,75) = -1
  StoichNum(67,77) = -1
  StoichNum(67,80) = -1
  StoichNum(67,81) = 0.08
  StoichNum(67,82) = -1
  StoichNum(67,83) = 0.27
  StoichNum(67,85) = -1
  StoichNum(67,86) = 0.27
  StoichNum(67,94) = -0.7
  StoichNum(67,95) = -0.7
  StoichNum(67,96) = -0.77
  StoichNum(67,97) = -1
  StoichNum(67,100) = -1
  StoichNum(67,122) = -1
  StoichNum(67,137) = -1
  StoichNum(67,140) = -1
      
END SUBROUTINE CalcStoichNum

! End of CalcStoichNum function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE CBMZ_Function

