! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : mech_Monitor.f90
! Equation file        : mech.kpp
! Output root filename : mech
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE mech_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'DUMMY                           ','NOCl                            ','BrNO                            ', & ! index 1 - 3
     'OBrO                            ','CH3Cl                           ','CO2                             ', & ! index 4 - 6
     'SULF                            ','ClONO                           ','CH3                             ', & ! index 7 - 9
     'HCO                             ','ClOO                            ','CCl3                            ', & ! index 10 - 12
     'C2H5O                           ','C2H4O2                          ','CH2CCl3                         ', & ! index 13 - 15
     'CH3SCH2                         ','CH2Br                           ','BrOO                            ', & ! index 16 - 18
     'CH32SBr                         ','CH3SOCH3                        ','CHBr2                           ', & ! index 19 - 21
     'CHBrCl                          ','H                               ','CBr3                            ', & ! index 22 - 24
     'CH3CCl2                         ','CH2Cl                           ','CHCl3                           ', & ! index 25 - 27
     'SO2                             ','CH3CCl3                         ','ISHP                            ', & ! index 28 - 30
     'C2H5O2                          ','CCl4                            ','CH2Br2                          ', & ! index 31 - 33
     'CHBr3                           ','CH2BrCl                         ','NO3Aer                          ', & ! index 34 - 36
     'HC8                             ','ACE                             ','HC5                             ', & ! index 37 - 39
     'MAHP                            ','NALD                            ','O1D                             ', & ! index 40 - 42
     'CH3Br                           ','ETEG                            ','HONO                            ', & ! index 43 - 45
     'BrNO2                           ','HNO4                            ','BAL2                            ', & ! index 46 - 48
     'TR2                             ','XYO                             ','XYM                             ', & ! index 49 - 51
     'XYP                             ','CH3SCH3                         ','MCT                             ', & ! index 52 - 54
     'XY2                             ','XYO2                            ','PPN                             ', & ! index 55 - 57
     'MPAN                            ','ClNO2                           ','ETH                             ', & ! index 58 - 60
     'HC3                             ','EOH                             ','TOL                             ', & ! index 61 - 63
     'OP1                             ','PHEN                            ','Br2                             ', & ! index 64 - 66
     'ISON                            ','ORA1                            ','CHO                             ', & ! index 67 - 69
     'PAA                             ','HBr                             ','ClETEP                          ', & ! index 70 - 72
     'BrCl                            ','API                             ','PAN                             ', & ! index 73 - 75
     'MCTO                            ','H2O2                            ','BAL1                            ', & ! index 76 - 78
     'OClO                            ','Cl2                             ','N2O5                            ', & ! index 79 - 81
     'HOBr                            ','LIM                             ','BALP                            ', & ! index 82 - 84
     'BrONO2                          ','ISO                             ','CO                              ', & ! index 85 - 87
     'EPX                             ','DIEN                            ','ETE                             ' /) ! index up to 90
  CHARACTER(LEN=32), PARAMETER, DIMENSION(83) :: SPC_NAMES_1 = (/ &
     'ClONO2                          ','TLP1                            ','XYL1                            ', & ! index 91 - 93
     'OLT                             ','MEK                             ','ACT                             ', & ! index 94 - 96
     'HNO3                            ','HKET                            ','ROH                             ', & ! index 97 - 99
     'BEN                             ','ORAP                            ','HOCl                            ', & ! index 100 - 102
     'KET                             ','XYOP                            ','ADCN                            ', & ! index 103 - 105
     'BALD                            ','MVK                             ','ETEP                            ', & ! index 106 - 108
     'BENP                            ','PER2                            ','MCP                             ', & ! index 109 - 111
     'TOLP                            ','PER1                            ','ADDC                            ', & ! index 112 - 114
     'MCTP                            ','GLY                             ','HC8P                            ', & ! index 115 - 117
     'HCl                             ','XYLP                            ','CSL                             ', & ! index 118 - 120
     'LIMP                            ','UALP                            ','MVKP                            ', & ! index 121 - 123
     'MGLY                            ','DCB3                            ','MACR                            ', & ! index 124 - 126
     'ISOP                            ','MACP                            ','MOH                             ', & ! index 127 - 129
     'BrAer                           ','OLNN                            ','APIP                            ', & ! index 130 - 132
     'ONIT                            ','OLTP                            ','UALD                            ', & ! index 133 - 135
     'RCO3                            ','ClO                             ','BrO                             ', & ! index 136 - 138
     'Br                              ','DCB2                            ','OP2                             ', & ! index 139 - 141
     'HC5P                            ','OLI                             ','OLIP                            ', & ! index 142 - 144
     'OLND                            ','DCB1                            ','ACTP                            ', & ! index 145 - 147
     'MEKP                            ','XO2                             ','ACD                             ', & ! index 148 - 150
     'HCHO                            ','ClAer                           ','O3P                             ', & ! index 151 - 153
     'NO                              ','O3                              ','MO2                             ', & ! index 154 - 156
     'KETP                            ','ALD                             ','HO                              ', & ! index 157 - 159
     'ORA2                            ','ETHP                            ','NO2                             ', & ! index 160 - 162
     'NO3                             ','HO2                             ','HC3P                            ', & ! index 163 - 165
     'ACO3                            ','Cl                              ','O2                              ', & ! index 166 - 168
     'AIR                             ','H2                              ','CH4                             ', & ! index 169 - 171
     'N2                              ','H2O                             ' /) ! index up to 173
  CHARACTER(LEN=32), PARAMETER, DIMENSION(173) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, PARAMETER, DIMENSION(173) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, & ! index 1 - 12
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, & ! index 13 - 24
      25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, & ! index 25 - 36
      37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, & ! index 37 - 48
      49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, & ! index 49 - 60
      61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, & ! index 61 - 72
      73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, & ! index 73 - 84
      85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, & ! index 85 - 96
      97, 98, 99,100,101,102,103,104,105,106,107,108, & ! index 97 - 108
     109,110,111,112,113,114,115,116,117,118,119,120, & ! index 109 - 120
     121,122,123,124,125,126,127,128,129,130,131,132, & ! index 121 - 132
     133,134,135,136,137,138,139,140,141,142,143,144, & ! index 133 - 144
     145,146,147,148,149,150,151,152,153,154,155,156, & ! index 145 - 156
     157,158,159,160,161,162,163,164,165,166,167,168, & ! index 157 - 168
     169,170,171,172,173 /) ! index up to 173

  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '            O3 --> O3P + O2                                                                         ', & ! index 1
     '            O3 --> O1D + O2                                                                         ', & ! index 2
     '          H2O2 --> 2 HO                                                                             ', & ! index 3
     '           NO2 --> O3P + NO                                                                         ', & ! index 4
     '           NO3 --> NO + O2                                                                          ', & ! index 5
     '           NO3 --> O3P + NO2                                                                        ', & ! index 6
     '          HONO --> NO + HO                                                                          ', & ! index 7
     '          HNO3 --> HO + NO2                                                                         ', & ! index 8
     '          HNO4 --> 0.2 HO + 0.8 NO2 + 0.2 NO3 + 0.8 HO2                                             ', & ! index 9
     '          HCHO --> CO + H2                                                                          ', & ! index 10
     '          HCHO --> CO + 2 HO2                                                                       ', & ! index 11
     '           ACD --> CO + MO2 + HO2                                                                   ', & ! index 12
     '           ALD --> CO + ETHP + HO2                                                                  ', & ! index 13
     '           ACT --> MO2 + ACO3                                                                       ', & ! index 14
     '          UALD --> 1.22 CO + 0.216 KET + 0.35 HCHO + 0.434 ALD + 1.22 HO2 + 0.784 ACO3              ', & ! index 15
     '           MEK --> 0.5 MO2 + 0.5 ETHP + ACO3                                                        ', & ! index 16
     '           KET --> ETHP + ACO3                                                                      ', & ! index 17
     '          HKET --> HCHO + HO2 + ACO3                                                                ', & ! index 18
     '          MACR --> 0.67 CO + 0.33 MACP + 0.34 XO2 + 0.67 HCHO + 0.34 HO + 0.66 HO2 + 0.67 ACO3      ', & ! index 19
     '           MVK --> 0.7 CO + 0.3 MACP + 0.7 UALD + 0.3 MO2                                           ', & ! index 20
     '           GLY --> 2 CO + H2                                                                        ', & ! index 21
     '           GLY --> CO + HCHO                                                                        ', & ! index 22
     '           GLY --> 2 CO + 2 HO2                                                                     ', & ! index 23
     '          MGLY --> CO + HO2 + ACO3                                                                  ', & ! index 24
     '          DCB1 --> CO + 0.5 GLY + 0.5 MGLY + 0.2 XO2 + 1.5 HO2 + 0.25 ACO3                          ', & ! index 25
     '          DCB2 --> CO + 0.5 GLY + 0.5 MGLY + 0.2 XO2 + 1.5 HO2 + 0.25 ACO3                          ', & ! index 26
     '          BALD --> CHO + CO + HO2                                                                   ', & ! index 27
     '           OP1 --> HCHO + HO + HO2                                                                  ', & ! index 28
     '           OP2 --> ALD + HO + HO2                                                                   ', & ! index 29
     '           PAA --> MO2 + HO                                                                         ' /) ! index up to 30
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '          ONIT --> 0.8 KET + 0.2 ALD + NO2 + HO2                                                    ', & ! index 31
     '           PAN --> NO2 + ACO3                                                                       ', & ! index 32
     '           PAN --> CO2 + MO2 + NO3                                                                  ', & ! index 33
     '       O3 + HO --> HO2 + O2                                                                         ', & ! index 34
     '      O3 + HO2 --> HO + 2 O2                                                                        ', & ! index 35
     '       NO + O3 --> NO2 + O2                                                                         ', & ! index 36
     '      O3 + NO2 --> NO3 + O2                                                                         ', & ! index 37
     '      O3P + O2 --> O3                                                                               ', & ! index 38
     '      O3P + O3 --> 2 O2                                                                             ', & ! index 39
     '      O1D + O2 --> O3P + O2                                                                         ', & ! index 40
     '      O1D + N2 --> O3P + N2                                                                         ', & ! index 41
     '     O1D + H2O --> 2 HO                                                                             ', & ! index 42
     '       HO + H2 --> HO2 + H2O                                                                        ', & ! index 43
     '      HO + HO2 --> O2 + H2O                                                                         ', & ! index 44
     '         2 HO2 --> H2O2 + O2                                                                        ', & ! index 45
     '   2 HO2 + H2O --> H2O2 + O2 + H2O                                                                  ', & ! index 46
     '     H2O2 + HO --> HO2 + H2O                                                                        ', & ! index 47
     '      O3P + NO --> NO2                                                                              ', & ! index 48
     '       NO + HO --> HONO                                                                             ', & ! index 49
     '      NO + HO2 --> HO + NO2                                                                         ', & ! index 50
     '      NO + HO2 --> HNO3                                                                             ', & ! index 51
     '     2 NO + O2 --> 2 NO2                                                                            ', & ! index 52
     '     HONO + HO --> NO2 + H2O                                                                        ', & ! index 53
     '     O3P + NO2 --> NO + O2                                                                          ', & ! index 54
     '     O3P + NO2 --> NO3                                                                              ', & ! index 55
     '      HO + NO2 --> HNO3                                                                             ', & ! index 56
     '     HNO3 + HO --> NO3 + H2O                                                                        ', & ! index 57
     '      HO + NO3 --> NO2 + HO2                                                                        ', & ! index 58
     '     NO3 + HO2 --> 0.3 HNO3 + 0.7 HO + 0.7 NO2                                                      ', & ! index 59
     '      NO + NO3 --> 2 NO2                                                                            ' /) ! index up to 60
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '     NO2 + NO3 --> NO + NO2 + O2                                                                    ', & ! index 61
     '         2 NO3 --> 2 NO2 + O2                                                                       ', & ! index 62
     '     NO2 + NO3 --> N2O5                                                                             ', & ! index 63
     '          N2O5 --> NO2 + NO3                                                                        ', & ! index 64
     '    N2O5 + H2O --> 2 HNO3                                                                           ', & ! index 65
     '     NO2 + HO2 --> HNO4                                                                             ', & ! index 66
     '          HNO4 --> NO2 + HO2                                                                        ', & ! index 67
     '     HNO4 + HO --> NO2 + O2 + H2O                                                                   ', & ! index 68
     '      SO2 + HO --> SULF + HO2                                                                       ', & ! index 69
     '       CO + HO --> CO2 + HO2                                                                        ', & ! index 70
     '      HO + CH4 --> MO2 + H2O                                                                        ', & ! index 71
     '      ETH + HO --> ETHP + H2O                                                                       ', & ! index 72
     '      HC3 + HO --> HC3P + H2O                                                                       ', & ! index 73
     '      HC5 + HO --> HC5P + H2O                                                                       ', & ! index 74
     '      HC8 + HO --> 0.024 HKET + 0.951 HC8P + 0.025 ALD + 0.049 HO2 + H2O                            ', & ! index 75
     '      ETE + HO --> ETEP                                                                             ', & ! index 76
     '      OLT + HO --> OLTP                                                                             ', & ! index 77
     '      OLI + HO --> OLIP                                                                             ', & ! index 78
     '     DIEN + HO --> OLIP                                                                             ', & ! index 79
     '      ACE + HO --> 0.35 ORA1 + 0.35 CO + 0.65 GLY + 0.65 HO + 0.35 HO2                              ', & ! index 80
     '      BEN + HO --> 0.53 PHEN + 0.118 EPX + 0.352 BENP + 0.648 HO2                                   ', & ! index 81
     '      TOL + HO --> 0.763 TR2 + 0.06 TLP1 + 0.177 CSL + 0.177 HO2                                    ', & ! index 82
     '      XYM + HO --> 0.763 XY2 + 0.06 XYL1 + 0.117 CSL + 0.177 HO2                                    ', & ! index 83
     '      XYP + HO --> 0.763 XY2 + 0.06 XYL1 + 0.117 CSL + 0.177 HO2                                    ', & ! index 84
     '      XYO + HO --> 0.763 XYO2 + 0.06 XYL1 + 0.177 CSL + 0.177 HO2                                   ', & ! index 85
     '      ISO + HO --> ISOP                                                                             ', & ! index 86
     '      API + HO --> APIP                                                                             ', & ! index 87
     '      LIM + HO --> LIMP                                                                             ', & ! index 88
     '     HCHO + HO --> CO + HO2 + H2O                                                                   ', & ! index 89
     '      ACD + HO --> ACO3 + H2O                                                                       ' /) ! index up to 90
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '      ALD + HO --> RCO3 + H2O                                                                       ', & ! index 91
     '      ACT + HO --> ACTP + H2O                                                                       ', & ! index 92
     '      MEK + HO --> MEKP + H2O                                                                       ', & ! index 93
     '      KET + HO --> KETP + H2O                                                                       ', & ! index 94
     '     HKET + HO --> MGLY + HO2 + H2O                                                                 ', & ! index 95
     '     MACR + HO --> 0.43 MCP + 0.57 MACP                                                             ', & ! index 96
     '      MVK + HO --> MVKP                                                                             ', & ! index 97
     '     UALD + HO --> 0.687 UALP + 0.313 ACO3                                                          ', & ! index 98
     '      GLY + HO --> 2 CO + HO2 + H2O                                                                 ', & ! index 99
     '     MGLY + HO --> CO + ACO3 + H2O                                                                  ', & ! index 100
     '     DCB1 + HO --> 0.33 CO + 0.78 KET + 0.1 GLY + 0.01 MGLY + 0.4 ALD + 0.52 HO2                    ', & ! index 101
     '     DCB2 + HO --> 0.33 CO + 0.13 MEK + 0.1 GLY + 0.01 MGLY + 0.78 OP2 + 0.52 HO2                   ', & ! index 102
     '     DCB3 + HO --> 0.11 CO + 0.27 GLY + 0.01 MGLY + 0.21 MACP + 0.79 OP2 + 0.56 HO2                 ', & ! index 103
     '     BALD + HO --> BALP + H2O                                                                       ', & ! index 104
     '     PHEN + HO --> 0.73 MCT + 0.07 CHO + 0.2 ADDC + 0.73 HO2                                        ', & ! index 105
     '      CSL + HO --> 0.73 MCT + 0.07 CHO + 0.2 ADDC + 0.73 HO2                                        ', & ! index 106
     '      EPX + HO --> CO + XO2 + ALD + HO2                                                             ', & ! index 107
     '      MCT + HO --> MCTO                                                                             ', & ! index 108
     '      MOH + HO --> HCHO + HO2                                                                       ', & ! index 109
     '      EOH + HO --> ACD + HO2                                                                        ', & ! index 110
     '      ROH + HO --> 0.184 ACD + 0.719 ALD + HO2                                                      ', & ! index 111
     '     ETEG + HO --> ALD + HO2                                                                        ', & ! index 112
     '      OP1 + HO --> 0.35 HCHO + 0.65 MO2 + 0.35 HO                                                   ', & ! index 113
     '      OP2 + HO --> 0.41 KET + 0.07 XO2 + 0.08 ALD + 0.01 HO + 0.44 HC3P                             ', & ! index 114
     '     ISHP + HO --> MACR + HO                                                                        ', & ! index 115
     '     MAHP + HO --> MACP                                                                             ', & ! index 116
     '     ORA1 + HO --> CO2 + HO2                                                                        ', & ! index 117
     '     HO + ORA2 --> 0.64 CO2 + 0.36 ORAP + 0.64 MO2                                                  ', & ! index 118
     '      PAA + HO --> 0.35 XO2 + 0.35 HCHO + 0.35 HO + 0.65 ACO3                                       ', & ! index 119
     '      PAN + HO --> XO2 + HCHO + NO3 + H2O                                                           ' /) ! index up to 120
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '      PPN + HO --> XO2 + HCHO + NO3 + H2O                                                           ', & ! index 121
     '     MPAN + HO --> HKET + NO2                                                                       ', & ! index 122
     '     ONIT + HO --> NO2 + HC3P + H2O                                                                 ', & ! index 123
     '     NALD + HO --> HKET + XO2 + NO2                                                                 ', & ! index 124
     '     ISON + HO --> NALD + 0.07 HKET + 0.07 HCHO                                                     ', & ! index 125
     '      ETE + O3 --> 0.37 ORA1 + 0.43 CO + HCHO + 0.08 HO + 0.15 HO2 + 0.13 H2                        ', & ! index 126
     '      OLT + O3 --> 0.006 HC5 + 0.02 ETH + 0.015 HC3 + 0.03 ORA1 + 0.068 H2O2 + 0.43 CO + 0.0... etc.', & ! index 127
     '      OLI + O3 --> 0.01 ETH + 0.01 HC3 + 0.026 H2O2 + 0.37 CO + 0.11 ACT + 0.044 HKET + 0.01... etc.', & ! index 128
     '     DIEN + O3 --> 0.15 ORA1 + 0.001 H2O2 + 0.36 CO + 0.35 OLT + 0.39 MACR + 0.13 XO2 + 0.9 ... etc.', & ! index 129
     '      ISO + O3 --> 0.28 ORA1 + 0.09 H2O2 + 0.14 CO + 0.153 OLT + 0.189 MVK + 0.461 MACR + 0.... etc.', & ! index 130
     '      API + O3 --> 0.02 H2O2 + 0.14 CO + 0.53 KET + 0.42 KETP + 0.65 ALD + 0.85 HO + 0.2 ETH... etc.', & ! index 131
     '      LIM + O3 --> 0.01 ORA1 + 0.02 H2O2 + 0.14 CO + 0.46 OLT + 0.79 MACR + 0.04 HCHO + 0.42... etc.', & ! index 132
     '     MACR + O3 --> 0.45 ORA1 + 0.22 CO + 0.5 MGLY + 0.19 HO + 0.14 HO2 + 0.1 ACO3                   ', & ! index 133
     '      MVK + O3 --> 0.07 ORA1 + 0.56 CO + 0.54 MGLY + 0.01 XO2 + 0.1 HCHO + 0.1 ALD + 0.16 HO... etc.', & ! index 134
     '     UALD + O3 --> 0.044 ORA1 + 0.243 CO + 0.028 KET + 0.491 GLY + 0.003 MGLY + 0.1 XO2 + 0.... etc.', & ! index 135
     '     DCB1 + O3 --> 0.5 CO2 + 1.5 CO + 0.05 GLY + 0.08 MGLY + 0.6 RCO3 + 0.65 OP2 + 0.6 XO2 +... etc.', & ! index 136
     '     DCB2 + O3 --> 0.5 CO2 + 1.5 CO + 0.05 GLY + 0.08 MGLY + 0.6 RCO3 + 0.65 OP2 + 0.7 DCB1 ... etc.', & ! index 137
     '     DCB3 + O3 --> 0.5 CO2 + 0.25 ORA1 + 0.11 PAA + 1.5 CO + 0.48 GLY + 0.7 DCB1 + 0.05 HO +... etc.', & ! index 138
     '      EPX + O3 --> 0.5 CO2 + 1.5 CO + 0.85 BALD + GLY + 0.05 HO + 1.5 HO2                           ', & ! index 139
     '     MCTO + O3 --> MCTP                                                                             ', & ! index 140
     '     ETE + NO3 --> 0.8 OLNN + 0.2 OLND                                                              ', & ! index 141
     '     OLT + NO3 --> 0.43 OLNN + 0.57 OLND                                                            ', & ! index 142
     '     OLI + NO3 --> 0.11 OLNN + 0.89 OLND                                                            ', & ! index 143
     '    DIEN + NO3 --> 0.9 MACR + 0.9 OLNN + 0.1 OLND                                                   ', & ! index 144
     '     ISO + NO3 --> ISON                                                                             ', & ! index 145
     '     API + NO3 --> 0.1 OLNN + 0.9 OLND                                                              ', & ! index 146
     '     LIM + NO3 --> 0.71 OLNN + 0.29 OLND                                                            ', & ! index 147
     '    HCHO + NO3 --> CO + HNO3 + HO2                                                                  ', & ! index 148
     '     ACD + NO3 --> HNO3 + ACO3                                                                      ', & ! index 149
     '     ALD + NO3 --> HNO3 + RCO3                                                                      ' /) ! index up to 150
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     '    MACR + NO3 --> 0.32 HNO3 + 0.68 MGLY + 0.32 MACP + 0.68 XO2 + 0.68 HCHO + 0.68 NO2              ', & ! index 151
     '    UALD + NO3 --> 0.668 CO + ONIT + XO2 + 0.332 HCHO + 0.332 ALD + HO2                             ', & ! index 152
     '     GLY + NO3 --> 2 CO + HNO3 + HO2                                                                ', & ! index 153
     '    MGLY + NO3 --> CO + HNO3 + ACO3                                                                 ', & ! index 154
     '    PHEN + NO3 --> 0.4 CHO + 0.5 HNO3 + 0.5 ADCN + 0.1 ADDC                                         ', & ! index 155
     '     CSL + NO3 --> 0.4 CHO + 0.5 HNO3 + 0.5 ADCN + 0.1 ADDC                                         ', & ! index 156
     '     EPX + NO3 --> 0.5 CO2 + 1.5 CO + 0.5 HNO3 + GLY + 0.5 HO + 0.5 NO2 + 1.5 HO2                   ', & ! index 157
     '     MCT + NO3 --> MCTO + HNO3                                                                      ', & ! index 158
     '    MPAN + NO3 --> MACP + NO2                                                                       ', & ! index 159
     '           TR2 --> 0.28 EPX + 0.28 TOLP + 0.15 PER1 + 0.01 CSL + 0.28 DCB2 + 0.28 HO + 0.29 HO2     ', & ! index 160
     '          TOLP --> 0.5 PER1 + 0.01 CSL + 0.49 DCB2 + 0.49 HO + 0.01 HO2                             ', & ! index 161
     '           XY2 --> 0.84 EPX + 0.15 PER2 + 0.308 XYLP + 0.01 CSL + 0.25 RCO3 + 0.224 DCB2 + 0... etc.', & ! index 162
     '          XYLP --> 0.5 PER2 + 0.01 CSL + 0.49 DCB2 + 0.39 HO + 0.01 HO2                             ', & ! index 163
     '          XYO2 --> 0.84 EPX + 0.15 PER2 + 0.308 XYLP + 0.01 CSL + 0.25 RCO3 + 0.224 DCB2 + 0... etc.', & ! index 164
     '          XYOP --> 0.5 PER2 + 0.01 CSL + 0.49 DCB2 + 0.39 HO + 0.01 HO2                             ', & ! index 165
     '    NO2 + ACO3 --> PAN                                                                              ', & ! index 166
     '           PAN --> DUMMY + NO2 + ACO3                                                               ', & ! index 167
     '    RCO3 + NO2 --> PPN                                                                              ', & ! index 168
     '           PPN --> RCO3 + NO2                                                                       ', & ! index 169
     '    MACP + NO2 --> MPAN                                                                             ', & ! index 170
     '          MPAN --> MACP + NO2                                                                       ', & ! index 171
     '      NO + MO2 --> HCHO + NO2 + HO2                                                                 ', & ! index 172
     '     NO + ETHP --> ACD + NO2 + HO2                                                                  ', & ! index 173
     '     NO + HC3P --> 0.042 MEK + 0.165 ACT + 0.065 ONIT + 0.089 XO2 + 0.504 ACD + 0.131 MO2 + ... etc.', & ! index 174
     '     HC5P + NO --> 0.033 MEK + 0.217 ACT + 0.272 HKET + 0.039 KET + 0.136 ONIT + 0.235 XO2 +... etc.', & ! index 175
     '     HC8P + NO --> 0.642 KET + 0.261 ONIT + 0.416 XO2 + 0.15 ALD + 0.133 ETHP + 0.739 NO2 + ... etc.', & ! index 176
     '     ETEP + NO --> 1.6 HCHO + 0.2 ALD + NO2 + HO2                                                   ', & ! index 177
     '     OLTP + NO --> 0.13 MEK + 0.06 ACT + 0.03 ONIT + 0.012 ACD + 0.78 HCHO + 0.44 ALD + 0.97... etc.', & ! index 178
     '     OLIP + NO --> 0.2 ACT + 0.02 HKET + 0.09 KET + 0.05 ONIT + 0.81 ACD + 0.68 ALD + 0.95 N... etc.', & ! index 179
     '     BENP + NO --> 0.918 GLY + 0.459 DCB3 + 0.082 ONIT + 0.459 DCB2 + 0.918 NO2 + 0.918 HO2         ' /) ! index up to 180
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     '     TLP1 + NO --> BALD + NO2                                                                       ', & ! index 181
     '     TOLP + NO --> 0.05 ONIT + 0.95 DCB2 + 0.95 NO2 + 0.95 HO2                                      ', & ! index 182
     '     PER1 + NO --> 0.5 BALD + 0.5 MGLY + 0.05 ONIT + 0.5 DCB1 + 0.95 NO2 + 0.5 HO2                  ', & ! index 183
     '     XYL1 + NO --> BALD + NO2                                                                       ', & ! index 184
     '     XYLP + NO --> 0.95 DCB3 + 0.05 ONIT + 0.95 NO2 + 0.95 HO2                                      ', & ! index 185
     '     PER2 + NO --> 0.95 MGLY + 1.05 DCB3 + 0.05 ONIT + 0.95 DCB1 + 0.95 NO2 + 0.95 HO2              ', & ! index 186
     '     XYOP + NO --> 0.35 GLY + 0.6 MGLY + 0.177 DCB3 + 0.05 ONIT + 0.073 DCB2 + 0.7 DCB1 + 0.... etc.', & ! index 187
     '     ISOP + NO --> 0.12 ISON + 0.029 HKET + 0.44 MVK + 0.021 GLY + 0.28 MACR + 0.2 HCHO + 0.... etc.', & ! index 188
     '     APIP + NO --> 0.07 ORA1 + 0.11 ACT + 0.44 KET + 0.18 ONIT + 0.23 HCHO + 0.43 ALD + 0.82... etc.', & ! index 189
     '     LIMP + NO --> 0.07 ORA1 + 0.68 UALD + 0.05 OLI + 0.43 HCHO + NO2 + HO2                         ', & ! index 190
     '     NO + ACO3 --> MO2 + NO2                                                                        ', & ! index 191
     '     RCO3 + NO --> ETHP + NO2                                                                       ', & ! index 192
     '     ACTP + NO --> HCHO + NO2 + ACO3                                                                ', & ! index 193
     '     MEKP + NO --> 0.67 DCB1 + 0.33 HCHO + NO2 + 0.67 HO2                                           ', & ! index 194
     '     NO + KETP --> 0.54 MGLY + 0.16 XO2 + 0.46 ALD + NO2 + 0.77 HO2 + 0.23 ACO3                     ', & ! index 195
     '     MACP + NO --> 0.25 CO + 0.25 HKET + 0.5 MGLY + 0.75 HCHO + NO2 + 0.75 HO2 + 0.25 ACO3          ', & ! index 196
     '      MCP + NO --> HKET + 0.5 HCHO + NO2 + 0.5 HO2                                                  ', & ! index 197
     '     MVKP + NO --> 0.3 MGLY + 0.7 XO2 + 0.3 HCHO + 0.7 ALD + NO2 + 0.3 HO2 + 0.7 ACO3               ', & ! index 198
     '     UALP + NO --> 0.61 CO + 0.7 KET + 0.18 GLY + 0.21 MGLY + 0.03 HCHO + 0.27 ALD + NO2 + HO2      ', & ! index 199
     '     BALP + NO --> BAL1 + NO2                                                                       ', & ! index 200
     '     BAL1 + NO --> BAL2 + NO2                                                                       ', & ! index 201
     '     ADDC + NO --> 0.32 HKET + 0.68 GLY + 0.68 OP2 + NO2 + HO2                                      ', & ! index 202
     '     MCTP + NO --> MCTO + NO2                                                                       ', & ! index 203
     '     ORAP + NO --> GLY + NO2 + HO2                                                                  ', & ! index 204
     '     OLNN + NO --> ONIT + NO2 + HO2                                                                 ', & ! index 205
     '     OLND + NO --> 0.464 KET + 0.287 HCHO + 1.24 ALD + 2 NO2                                        ', & ! index 206
     '     ADCN + NO --> GLY + OP2 + 2 NO2                                                                ', & ! index 207
     '      XO2 + NO --> NO2                                                                              ', & ! index 208
     '    BAL2 + NO2 --> ONIT                                                                             ', & ! index 209
     '     CHO + NO2 --> ONIT                                                                             ' /) ! index up to 210
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '    MCTO + NO2 --> ONIT                                                                             ', & ! index 211
     '     MO2 + HO2 --> OP1                                                                              ', & ! index 212
     '    ETHP + HO2 --> OP2                                                                              ', & ! index 213
     '    HO2 + HC3P --> OP2                                                                              ', & ! index 214
     '    HC5P + HO2 --> OP2                                                                              ', & ! index 215
     '    HC8P + HO2 --> OP2                                                                              ', & ! index 216
     '    ETEP + HO2 --> OP2                                                                              ', & ! index 217
     '    OLTP + HO2 --> OP2                                                                              ', & ! index 218
     '    OLIP + HO2 --> OP2                                                                              ', & ! index 219
     '    BENP + HO2 --> OP2                                                                              ', & ! index 220
     '    TLP1 + HO2 --> OP2                                                                              ', & ! index 221
     '    TOLP + HO2 --> OP2                                                                              ', & ! index 222
     '    PER1 + HO2 --> OP2                                                                              ', & ! index 223
     '    XYL1 + HO2 --> OP2                                                                              ', & ! index 224
     '    XYLP + HO2 --> OP2                                                                              ', & ! index 225
     '    PER2 + HO2 --> OP2                                                                              ', & ! index 226
     '    XYOP + HO2 --> OP2                                                                              ', & ! index 227
     '    ISOP + HO2 --> ISHP                                                                             ', & ! index 228
     '    APIP + HO2 --> OP2                                                                              ', & ! index 229
     '    LIMP + HO2 --> OP2                                                                              ', & ! index 230
     '    HO2 + ACO3 --> 0.44 CO2 + 0.41 PAA + 0.44 MO2 + 0.44 HO + 0.15 ORA2                             ', & ! index 231
     '    RCO3 + HO2 --> 0.44 CO2 + 0.41 PAA + 0.44 HO + 0.15 ORA2 + 0.44 ETHP                            ', & ! index 232
     '    ACTP + HO2 --> 0.85 OP2 + 0.15 HCHO + 0.15 HO + 0.15 ACO3                                       ', & ! index 233
     '    MEKP + HO2 --> OP2                                                                              ', & ! index 234
     '    KETP + HO2 --> OP2                                                                              ', & ! index 235
     '    MACP + HO2 --> MAHP                                                                             ', & ! index 236
     '     MCP + HO2 --> MAHP                                                                             ', & ! index 237
     '    MVKP + HO2 --> OP2                                                                              ', & ! index 238
     '    UALP + HO2 --> OP2                                                                              ', & ! index 239
     '    ADDC + HO2 --> OP2                                                                              ' /) ! index up to 240
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_8 = (/ &
     '     CHO + HO2 --> CSL                                                                              ', & ! index 241
     '    MCTP + HO2 --> OP2                                                                              ', & ! index 242
     '    ORAP + HO2 --> ONIT                                                                             ', & ! index 243
     '    OLNN + HO2 --> ONIT                                                                             ', & ! index 244
     '    OLND + HO2 --> ONIT                                                                             ', & ! index 245
     '    ADCN + HO2 --> OP2                                                                              ', & ! index 246
     '     XO2 + HO2 --> OP2                                                                              ', & ! index 247
     '         2 MO2 --> 0.63 MOH + 1.37 HCHO + 0.74 HO2                                                  ', & ! index 248
     '    MO2 + ETHP --> 0.25 EOH + 0.25 MOH + 0.75 ACD + 0.75 HCHO + HO2                                 ', & ! index 249
     '    MO2 + HC3P --> 0.25 ROH + 0.497 KET + 0.05 GLY + 0.25 MOH + 0.026 XO2 + 0.827 HCHO + 0.0... etc.', & ! index 250
     '    HC5P + MO2 --> 0.25 ROH + 0.618 KET + 0.25 MOH + 0.191 XO2 + 0.777 HCHO + 0.018 MO2 + 0.... etc.', & ! index 251
     '    HC8P + MO2 --> 0.25 ROH + 0.652 KET + 0.25 MOH + 0.281 XO2 + 0.75 HCHO + 0.197 ALD + 0.0... etc.', & ! index 252
     '    ETEP + MO2 --> 0.25 ETEG + 0.25 MOH + 1.95 HCHO + 0.15 ALD + HO2                                ', & ! index 253
     '    OLTP + MO2 --> 0.25 ROH + 0.045 KET + 0.25 MOH + 1.5 HCHO + 0.705 ALD + HO2                     ', & ! index 254
     '    OLIP + MO2 --> 0.25 ROH + 0.218 KET + 0.25 MOH + 0.75 HCHO + 1.28 ALD + HO2                     ', & ! index 255
     '    BENP + MO2 --> 0.6 GLY + 0.459 DCB3 + 0.459 DCB2 + HCHO + 1.6 HO2                               ', & ! index 256
     '    TLP1 + MO2 --> BALD + HCHO + HO2                                                                ', & ! index 257
     '    TOLP + MO2 --> 0.271 GLY + DCB2 + HCHO + 2 HO2                                                  ', & ! index 258
     '    PER1 + MO2 --> MGLY + DCB1 + HCHO + 2 HO2                                                       ', & ! index 259
     '    XYL1 + MO2 --> BALD + HCHO + HO2                                                                ', & ! index 260
     '    XYLP + MO2 --> DCB2 + HCHO + 2 HO2                                                              ', & ! index 261
     '    PER2 + MO2 --> MGLY + 1.05 DCB3 + DCB1 + HCHO + 2 HO2                                           ', & ! index 262
     '    XYOP + MO2 --> 0.368 GLY + 0.632 MGLY + 0.186 DCB3 + 0.077 DCB2 + 0.737 DCB1 + HCHO + 2 HO2     ', & ! index 263
     '    ISOP + MO2 --> 0.016 HKET + 0.25 ROH + 0.25 MVK + 0.018 GLY + 0.159 MACR + 0.25 MOH + 1.... etc.', & ! index 264
     '    APIP + MO2 --> 0.25 ROH + 0.75 KET + 0.25 MOH + 0.75 HCHO + 0.75 ALD + HO2                      ', & ! index 265
     '    LIMP + MO2 --> 0.25 ROH + 0.308 MACR + 0.25 MOH + 0.192 OLI + 1.04 HCHO + HO2                   ', & ! index 266
     '    MO2 + ACO3 --> 0.4 CO2 + HCHO + 0.9 MO2 + 0.1 ORA2 + 0.9 HO2                                    ', & ! index 267
     '    RCO3 + MO2 --> 0.4 CO2 + HCHO + 0.9 MO2 + 0.1 ORA2 + 0.9 HO2                                    ', & ! index 268
     '    ACTP + MO2 --> 0.25 ROH + 0.25 MOH + 1.5 HCHO + 0.125 ORA2 + 0.5 HO2 + 0.5 ACO3                 ', & ! index 269
     '    MEKP + MO2 --> 0.25 ROH + 0.25 MOH + 0.334 DCB1 + HCHO + 0.834 HO2                              ' /) ! index up to 270
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_9 = (/ &
     '    MO2 + KETP --> 0.25 ROH + 0.25 MOH + 0.5 DCB1 + 0.75 HCHO + HO2                                 ', & ! index 271
     '    MACP + MO2 --> 0.5 CO + 0.25 ROH + 0.25 MOH + 1.66 HCHO + 0.25 MO2 + 0.067 ORA2 + 0.5 HO... etc.', & ! index 272
     '     MCP + MO2 --> 0.5 HKET + 0.25 ROH + 0.25 MOH + 1.5 HCHO + NO2 + HO2                            ', & ! index 273
     '    MVKP + MO2 --> 0.25 ROH + 0.5 MGLY + 0.25 MOH + 1.16 XO2 + 1.5 HCHO + 1.75 ALD + 0.292 O... etc.', & ! index 274
     '    UALP + MO2 --> 0.305 CO + 0.25 ROH + 0.525 KET + 0.135 GLY + 0.105 MGLY + 0.25 MOH + 0.7... etc.', & ! index 275
     '    BALP + MO2 --> BAL1 + HCHO + HO2                                                                ', & ! index 276
     '    BAL1 + MO2 --> BAL2 + HCHO + HO2                                                                ', & ! index 277
     '    ADDC + MO2 --> 0.32 HKET + 0.68 GLY + 0.68 OP2 + HCHO + 2 HO2                                   ', & ! index 278
     '    MCTP + MO2 --> MCTO + HCHO + HO2                                                                ', & ! index 279
     '    ORAP + MO2 --> GLY + HCHO + HO2                                                                 ', & ! index 280
     '    OLNN + MO2 --> ONIT + HCHO + 2 HO2                                                              ', & ! index 281
     '    OLND + MO2 --> 0.25 ROH + 0.348 KET + 0.25 MOH + 0.5 ONIT + 0.965 HCHO + 0.93 ALD + 0.5 ... etc.', & ! index 282
     '    ADCN + MO2 --> 0.7 GLY + 0.3 ONIT + 0.7 OP2 + HCHO + 0.7 NO2 + HO2                              ', & ! index 283
     '     XO2 + MO2 --> HCHO + HO2                                                                       ', & ! index 284
     '   ETHP + ACO3 --> ACD + 0.5 MO2 + 0.5 ORA2 + 0.5 HO2                                               ', & ! index 285
     '   HC3P + ACO3 --> 0.662 KET + 0.067 GLY + 0.026 XO2 + 0.13 HCHO + 0.58 MO2 + 0.273 ALD + 0.... etc.', & ! index 286
     '   HC5P + ACO3 --> 0.824 KET + 0.191 XO2 + 0.042 HCHO + 0.518 MO2 + 0.381 ALD + 0.5 ORA2 + 0... etc.', & ! index 287
     '   HC8P + ACO3 --> 0.642 KET + 0.208 XO2 + 0.5 MO2 + 0.217 ALD + 0.495 ORA2 + 0.067 ETHP + 0.303 HO2', & ! index 288
     '   ETEP + ACO3 --> 1.6 HCHO + 0.5 MO2 + 0.2 ALD + 0.5 ORA2 + 0.5 HO2                                ', & ! index 289
     '   OLTP + ACO3 --> 0.06 KET + HCHO + 0.5 MO2 + 0.94 ALD + 0.5 ORA2 + 0.5 HO2                        ', & ! index 290
     '   OLIP + ACO3 --> 0.29 KET + 0.5 MO2 + 1.71 ALD + 0.5 ORA2 + 0.5 HO2                               ', & ! index 291
     '   BENP + ACO3 --> 0.6 GLY + 0.458 DCB3 + 0.459 DCB2 + MO2 + 0.6 HO2                                ', & ! index 292
     '   TLP1 + ACO3 --> BALD + MO2                                                                       ', & ! index 293
     '   TOLP + ACO3 --> DCB2 + MO2 + HO2                                                                 ', & ! index 294
     '   PER1 + ACO3 --> MGLY + DCB1 + MO2 + HO2                                                          ', & ! index 295
     '   XYL1 + ACO3 --> BALD + MO2                                                                       ', & ! index 296
     '   XYLP + ACO3 --> DCB2 + MO2 + HO2                                                                 ', & ! index 297
     '   PER2 + ACO3 --> MGLY + 1.05 DCB3 + DCB1 + MO2 + HO2                                              ', & ! index 298
     '   XYOP + ACO3 --> 0.368 GLY + 0.632 MGLY + 0.186 DCB3 + 0.077 DCB2 + 0.737 DCB1 + MO2 + HO2        ', & ! index 299
     '   ISOP + ACO3 --> 0.033 HKET + 0.25 MVK + 0.024 GLY + 0.159 MACR + 0.75 HCHO + 0.5 MO2 + 0.... etc.' /) ! index up to 300
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_10 = (/ &
     '   APIP + ACO3 --> KET + 0.5 MO2 + ALD + ORA2 + 0.5 HO2                                             ', & ! index 301
     '   LIMP + ACO3 --> 0.308 MACR + 0.192 OLI + 0.385 HCHO + 0.5 MO2 + 0.5 ORA2 + 0.5 HO2               ', & ! index 302
     '        2 ACO3 --> 2 CO2 + 2 MO2                                                                    ', & ! index 303
     '   RCO3 + ACO3 --> 2 CO2 + MO2 + ETHP                                                               ', & ! index 304
     '   ACTP + ACO3 --> HCHO + 0.5 MO2 + 0.75 ORA2 + 0.5 ACO3                                            ', & ! index 305
     '   MEKP + ACO3 --> 0.334 DCB1 + 0.33 HCHO + 0.5 MO2 + 0.5 ORA2 + 0.33 HO2                           ', & ! index 306
     '   KETP + ACO3 --> 0.5 DCB1 + 0.5 MO2 + 0.5 ORA2 + 0.5 HO2                                          ', & ! index 307
     '   MACP + ACO3 --> 0.167 CO + 0.167 HKET + 0.33 MGLY + HCHO + 0.5 MO2 + 0.583 ORA2 + 0.5 HO2... etc.', & ! index 308
     '    MCP + ACO3 --> 0.5 HKET + HCHO + 0.5 MO2 + 0.5 ORA2 + NO2 + 0.5 HO2                             ', & ! index 309
     '   MVKP + ACO3 --> 0.5 MGLY + 1.16 XO2 + HCHO + 0.5 MO2 + 2.3 ALD + 1.083 ORA2 + 0.5 HO2 + 1.16 ACO3', & ! index 310
     '   UALP + ACO3 --> 0.5 CO + 0.7 KET + 0.18 GLY + 0.105 MGLY + 0.03 HCHO + 0.5 MO2 + 0.27 ALD... etc.', & ! index 311
     '   BALP + ACO3 --> BAL1 + MO2                                                                       ', & ! index 312
     '   BAL1 + ACO3 --> BAL2 + MO2                                                                       ', & ! index 313
     '   ADDC + ACO3 --> 0.32 HKET + 0.68 GLY + 0.68 OP2 + MO2 + 2 HO2                                    ', & ! index 314
     '   MCTP + ACO3 --> MCTO + MO2 + HO2                                                                 ', & ! index 315
     '   ORAP + ACO3 --> GLY + MO2                                                                        ', & ! index 316
     '   OLNN + ACO3 --> ONIT + MO2 + HO2                                                                 ', & ! index 317
     '   OLND + ACO3 --> 0.464 KET + 0.287 HCHO + 0.5 MO2 + 1.24 ALD + 0.5 ORA2 + NO2                     ', & ! index 318
     '   ADCN + ACO3 --> 0.7 GLY + 0.3 ONIT + 0.7 OP2 + MO2 + 0.7 NO2 + HO2                               ', & ! index 319
     '    XO2 + ACO3 --> MO2                                                                              ', & ! index 320
     '     MO2 + NO3 --> HCHO + NO2 + HO2                                                                 ', & ! index 321
     '    ETHP + NO3 --> ACD + NO2 + HO2                                                                  ', & ! index 322
     '    NO3 + HC3P --> 0.075 MEK + 0.095 ACT + 0.092 XO2 + 0.519 ACD + 0.14 MO2 + 0.147 ALD + 0.... etc.', & ! index 323
     '    HC5P + NO3 --> 0.063 MEK + 0.247 ACT + 0.275 HKET + 0.06 KET + 0.485 XO2 + 0.048 ACD + 0... etc.', & ! index 324
     '    HC8P + NO3 --> 0.869 KET + 0.563 XO2 + 0.203 ALD + 0.18 ETHP + NO2 + 0.82 HO2                   ', & ! index 325
     '    ETEP + NO3 --> 1.6 HCHO + 0.2 ALD + NO2 + HO2                                                   ', & ! index 326
     '    OLTP + NO3 --> 0.18 MEK + 0.09 ACT + 0.02 ACD + 0.79 HCHO + 0.47 ALD + NO2 + 0.79 HO2           ', & ! index 327
     '    OLIP + NO3 --> 0.2 ACT + 0.04 HKET + 0.11 KET + 0.85 ACD + 0.72 ALD + NO2 + 0.86 HO2            ', & ! index 328
     '    BENP + NO3 --> GLY + 0.5 DCB3 + 0.5 DCB2 + NO2 + HO2                                            ', & ! index 329
     '    TLP1 + NO3 --> BALD + NO2                                                                       ' /) ! index up to 330
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_11 = (/ &
     '    TOLP + NO3 --> DCB2 + NO2 + HO2                                                                 ', & ! index 331
     '    PER1 + NO3 --> 0.5 BALD + 0.5 MGLY + 0.5 DCB1 + NO2 + 0.5 HO2                                   ', & ! index 332
     '    XYL1 + NO3 --> BALD + NO2                                                                       ', & ! index 333
     '    XYLP + NO3 --> DCB3 + NO2 + HO2                                                                 ', & ! index 334
     '    PER2 + NO3 --> MGLY + 1.05 DCB3 + DCB1 + NO2 + HO2                                              ', & ! index 335
     '    XYOP + NO3 --> 0.368 GLY + 0.632 MGLY + 0.186 DCB3 + 0.077 DCB2 + 0.737 DCB1 + NO2 + HO2        ', & ! index 336
     '    ISOP + NO3 --> 0.033 HKET + 0.5 MVK + 0.024 GLY + 0.318 MACR + 0.75 HCHO + 0.031 ALD + NO2 + HO2', & ! index 337
     '    APIP + NO3 --> KET + ALD + NO2 + HO2                                                            ', & ! index 338
     '    LIMP + NO3 --> 0.615 MACR + 0.385 OLI + 0.385 HCHO + NO2 + HO2                                  ', & ! index 339
     '    NO3 + ACO3 --> MO2 + NO2                                                                        ', & ! index 340
     '    RCO3 + NO3 --> ETHP + NO2                                                                       ', & ! index 341
     '    ACTP + NO3 --> HCHO + NO2 + ACO3                                                                ', & ! index 342
     '    MEKP + NO3 --> 0.67 DCB1 + 0.33 HCHO + NO2 + 0.67 HO2                                           ', & ! index 343
     '    KETP + NO3 --> DCB1 + NO2 + HO2                                                                 ', & ! index 344
     '    MACP + NO3 --> 0.33 CO + 0.33 HKET + 0.667 MGLY + HCHO + NO2 + HO2 + 0.33 ACO3                  ', & ! index 345
     '     MCP + NO3 --> HKET + HCHO + NO2 + HO2                                                          ', & ! index 346
     '    MVKP + NO3 --> MGLY + 0.7 XO2 + 0.3 HCHO + 0.7 ALD + NO2 + 0.3 HO2 + 0.7 ACO3                   ', & ! index 347
     '    UALP + NO3 --> 0.61 CO + 0.7 KET + 0.18 GLY + 0.21 MGLY + 0.03 HCHO + 0.27 ALD + NO2 + HO2      ', & ! index 348
     '    BALP + NO3 --> BAL1 + NO2                                                                       ', & ! index 349
     '    BAL1 + NO3 --> BAL2 + NO2                                                                       ', & ! index 350
     '    ADDC + NO3 --> 0.32 HKET + 0.68 GLY + 0.68 OP2 + NO2 + HO2                                      ', & ! index 351
     '    MCTP + NO3 --> MCTO + NO2                                                                       ', & ! index 352
     '    ORAP + NO3 --> GLY + NO2 + HO2                                                                  ', & ! index 353
     '    OLNN + NO3 --> ONIT + NO2 + HO2                                                                 ', & ! index 354
     '    OLND + NO3 --> 0.464 KET + 0.287 HCHO + 1.24 ALD + 2 NO2                                        ', & ! index 355
     '    ADCN + NO3 --> GLY + OP2 + 2 NO2                                                                ', & ! index 356
     '     XO2 + NO3 --> NO2                                                                              ', & ! index 357
     '        2 RCO3 --> 2 CO2 + 2 ETHP                                                                   ', & ! index 358
     '        2 OLNN --> 2 ONIT + HO2                                                                     ', & ! index 359
     '   OLNN + OLND --> 0.149 KET + 1.5 ONIT + 0.202 HCHO + 0.64 ALD + 0.5 NO2 + 0.5 HO2                 ' /) ! index up to 360
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_12 = (/ &
     '        2 OLND --> 0.285 KET + ONIT + 0.504 HCHO + 1.21 ALD + NO2                                   ', & ! index 361
     '         2 XO2 --> DUMMY                                                                            ', & ! index 362
     '    RCO3 + XO2 --> CO2 + ETHP                                                                       ', & ! index 363
     '          OClO --> ClO + O3                                                                         ', & ! index 364
     '           Cl2 --> 2 Cl                                                                             ', & ! index 365
     '          HOCl --> HO + Cl                                                                          ', & ! index 366
     '         ClNO2 --> NO2 + Cl                                                                         ', & ! index 367
     '        ClONO2 --> NO3 + Cl                                                                         ', & ! index 368
     '        ClONO2 --> ClO + NO2                                                                        ', & ! index 369
     '           ClO --> O3P + Cl                                                                         ', & ! index 370
     '       O3 + Cl --> ClO + O2                                                                         ', & ! index 371
     '      HO2 + Cl --> HCl + O2                                                                         ', & ! index 372
     '      HO2 + Cl --> ClO + HO                                                                         ', & ! index 373
     '     H2O2 + Cl --> HCl + HO2                                                                        ', & ! index 374
     '      NO2 + Cl --> ClONO                                                                            ', & ! index 375
     '      NO2 + Cl --> ClNO2                                                                            ', & ! index 376
     '      NO3 + Cl --> ClO + NO2                                                                        ', & ! index 377
     '      Cl + CH4 --> HCl + MO2                                                                        ', & ! index 378
     '     HCHO + Cl --> HCO + HCl                                                                        ', & ! index 379
     '   ClONO2 + Cl --> Cl2 + NO3                                                                        ', & ! index 380
     '      ClO + HO --> HO2 + Cl                                                                         ', & ! index 381
     '      ClO + HO --> HCl + O2                                                                         ', & ! index 382
     '     ClO + HO2 --> HOCl + O2                                                                        ', & ! index 383
     '      ClO + NO --> NO2 + Cl                                                                         ', & ! index 384
     '     ClO + NO2 --> ClONO2                                                                           ', & ! index 385
     '         2 ClO --> Cl2 + O2                                                                         ', & ! index 386
     '         2 ClO --> OClO + Cl                                                                        ', & ! index 387
     '         2 ClO --> ClOO + Cl                                                                        ', & ! index 388
     '     OClO + NO --> ClO + NO2                                                                        ', & ! index 389
     '     HOCl + HO --> ClO + H2O                                                                        ' /) ! index up to 390
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_13 = (/ &
     '      HCl + HO --> Cl + H2O                                                                         ', & ! index 391
     '    ClNO2 + HO --> HOCl + NO2                                                                       ', & ! index 392
     '      Cl2 + HO --> HOCl + Cl                                                                        ', & ! index 393
     '     HOCl + Cl --> Cl2 + HO                                                                         ', & ! index 394
     '     ClO + NO3 --> OClO + NO2                                                                       ', & ! index 395
     '     ClO + NO3 --> ClOO + NO2                                                                       ', & ! index 396
     '     HCl + O3P --> HO + Cl                                                                          ', & ! index 397
     '    HOCl + O3P --> ClO + HO                                                                         ', & ! index 398
     '    CHCl3 + HO --> CCl3 + H2O                                                                       ', & ! index 399
     '   C2H5O2 + Cl --> C2H5O + ClO                                                                      ', & ! index 400
     '   C2H5O2 + Cl --> C2H4O2 + HCl                                                                     ', & ! index 401
     '     OClO + Cl --> 2 ClO                                                                            ', & ! index 402
     '     OClO + HO --> HOCl + O2                                                                        ', & ! index 403
     '     ClO + O3P --> Cl + O2                                                                          ', & ! index 404
     '       Cl + H2 --> H + HCl                                                                          ', & ! index 405
     '  ClONO2 + O3P --> ClO + NO3                                                                        ', & ! index 406
     '    CCl4 + O1D --> CCl3 + ClO                                                                       ', & ! index 407
     '  CH3CCl3 + HO --> CH2CCl3 + H2O                                                                    ', & ! index 408
     '  CH3SCH3 + Cl --> CH3SCH2 + HCl                                                                    ', & ! index 409
     '           ClO --> O1D + Cl                                                                         ', & ! index 410
     '          NOCl --> NO + Cl                                                                          ', & ! index 411
     '           HCl --> H + Cl                                                                           ', & ! index 412
     '         CH3Cl --> CH3 + Cl                                                                         ', & ! index 413
     '          CCl4 --> CCl3 + Cl                                                                        ', & ! index 414
     '       CH3CCl3 --> CH3CCl2 + Cl                                                                     ', & ! index 415
     '          HCHO --> DUMMY                                                                            ', & ! index 416
     '          MACR --> DUMMY                                                                            ', & ! index 417
     '           MVK --> DUMMY                                                                            ', & ! index 418
     '           ALD --> DUMMY                                                                            ', & ! index 419
     '        NO3Aer --> HNO3                                                                             ' /) ! index up to 420
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_14 = (/ &
     '          HNO3 --> DUMMY                                                                            ', & ! index 421
     '        NO3Aer --> DUMMY                                                                            ', & ! index 422
     '        NO3Aer --> HONO                                                                             ', & ! index 423
     '           BrO --> Br + O3                                                                          ', & ! index 424
     '           Br2 --> 2 Br                                                                             ', & ! index 425
     '          HOBr --> Br + HO                                                                          ', & ! index 426
     '         BrNO2 --> Br + NO2                                                                         ', & ! index 427
     '        BrONO2 --> Br + NO3                                                                         ', & ! index 428
     '        BrONO2 --> BrO + NO2                                                                        ', & ! index 429
     '          BrCl --> Br + Cl                                                                          ', & ! index 430
     '       Br + O3 --> BrO + O2                                                                         ', & ! index 431
     '      Br + HO2 --> HBr + O2                                                                         ', & ! index 432
     '     Br + HCHO --> HCO + HBr                                                                        ', & ! index 433
     '      Br + NO2 --> BrNO2                                                                            ', & ! index 434
     '     BrO + HO2 --> HOBr + O2                                                                        ', & ! index 435
     '      BrO + NO --> Br + NO2                                                                         ', & ! index 436
     '     BrO + NO2 --> BrONO2                                                                           ', & ! index 437
     '         2 BrO --> 2 Br + O2                                                                        ', & ! index 438
     '         2 BrO --> Br2 + O2                                                                         ', & ! index 439
     '      HBr + HO --> Br + H2O                                                                         ', & ! index 440
     '      Br2 + HO --> HOBr + Br                                                                        ', & ! index 441
     '    CH3Br + HO --> CH2Br + H2O                                                                      ', & ! index 442
     '      Br + NO3 --> BrO + NO2                                                                        ', & ! index 443
     '     BrO + NO3 --> BrOO + NO2                                                                       ', & ! index 444
     '     HBr + O3P --> Br + HO                                                                          ', & ! index 445
     '  BrONO2 + O3P --> BrO + NO3                                                                        ', & ! index 446
     '      BrO + HO --> Br + HO2                                                                         ', & ! index 447
     '  CH3SCH3 + Br --> CH3SCH2 + HBr                                                                    ', & ! index 448
     '  CH3SCH3 + Br --> CH32SBr                                                                          ', & ! index 449
     ' CH3SCH3 + BrO --> CH3SOCH3 + Br                                                                    ' /) ! index up to 450
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_15 = (/ &
     '     ClO + BrO --> OClO + Br                                                                        ', & ! index 451
     '     ClO + BrO --> BrCl + O2                                                                        ', & ! index 452
     '    CH3Br + Cl --> CH2Br + HCl                                                                      ', & ! index 453
     '   CH2Br2 + Cl --> CHBr2 + HCl                                                                      ', & ! index 454
     '    CHBr3 + Cl --> CBr3 + HCl                                                                       ', & ! index 455
     '  CH2BrCl + Cl --> CHBrCl + HCl                                                                     ', & ! index 456
     '          BrNO --> Br + NO                                                                          ', & ! index 457
     '          OBrO --> BrO + O3P                                                                        ', & ! index 458
     '         CH3Br --> CH3 + Br                                                                         ', & ! index 459
     '         CHBr3 --> CHBr2 + Br                                                                       ', & ! index 460
     '        CH2Br2 --> CH2Br + Br                                                                       ', & ! index 461
     '       CH2BrCl --> CH2Cl + Br                                                                       ', & ! index 462
     '      Br + ACD --> HBr + ACO3                                                                       ', & ! index 463
     '      ETH + Cl --> HCl + ETHP                                                                       ', & ! index 464
     '      ETE + Cl --> ClETEP                                                                           ', & ! index 465
     '      ACD + Cl --> HCl + ACO3                                                                       ', & ! index 466
     '      MOH + Cl --> HCl + HCHO + HO2                                                                 ', & ! index 467
     '      EOH + Cl --> HCl + ACD + HO2                                                                  ', & ! index 468
     '      HC3 + Cl --> HCl + HC3P                                                                       ', & ! index 469
     '      ALD + Cl --> HCl + RCO3                                                                       ', & ! index 470
     '      ACT + Cl --> HCl + ACTP                                                                       ', & ! index 471
     '      MEK + Cl --> HCl + MEKP                                                                       ', & ! index 472
     '      OP1 + Cl --> HCl + HCHO + HO                                                                  ', & ! index 473
     '     ORA2 + Cl --> ORAP + HCl                                                                       ', & ! index 474
     '      PAN + Cl --> CO + HCl + HCHO + NO2                                                            ', & ! index 475
     '   ClETEP + NO --> HCl + NO2 + ACO3                                                                 ', & ! index 476
     '  ClETEP + HO2 --> HCl + ACO3 + H2O                                                                 ', & ! index 477
     '      2 ClETEP --> 2 HCl + 2 ACO3                                                                   ', & ! index 478
     '  ClETEP + MO2 --> HCl + HCHO + HO2 + ACO3                                                          ', & ! index 479
     '      BEN + Cl --> BENP + HCl                                                                       ' /) ! index up to 480
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_16 = (/ &
     '      TOL + Cl --> BALD + HCl                                                                       ', & ! index 481
     '      XYO + Cl --> XYO2 + HCl                                                                       ', & ! index 482
     '      XYM + Cl --> XY2 + HCl                                                                        ', & ! index 483
     '      XYP + Cl --> XY2 + HCl                                                                        ', & ! index 484
     '    BrNO2 + Br --> Br2 + NO2                                                                        ', & ! index 485
     '   BrONO2 + Br --> Br2 + NO3                                                                        ', & ! index 486
     '   DUMMY + AIR --> DUMMY                                                                            ', & ! index 487
     '          HNO3 --> NO3Aer                                                                           ', & ! index 488
     '          HNO4 --> DUMMY                                                                            ', & ! index 489
     '           HO2 --> DUMMY                                                                            ', & ! index 490
     '          HONO --> DUMMY                                                                            ', & ! index 491
     '          N2O5 --> NO3Aer                                                                           ', & ! index 492
     '           NO2 --> DUMMY                                                                            ', & ! index 493
     '           NO3 --> DUMMY                                                                            ', & ! index 494
     '           HBr --> BrAer                                                                            ', & ! index 495
     '           HCl --> ClAer                                                                            ', & ! index 496
     '  HOCl + ClAer --> Cl2                                                                              ', & ! index 497
     'ClONO2 + ClAer --> DUMMY + Cl2                                                                      ', & ! index 498
     '        ClONO2 --> DUMMY + HOCl                                                                     ', & ! index 499
     '  N2O5 + ClAer --> DUMMY + ClNO2                                                                    ', & ! index 500
     '    ClAer + HO --> 0.5 Cl2                                                                          ', & ! index 501
     '  HOCl + BrAer --> BrCl                                                                             ', & ! index 502
     'ClONO2 + BrAer --> DUMMY + BrCl                                                                     ', & ! index 503
     '  HOBr + BrAer --> Br2                                                                              ', & ! index 504
     '  HOBr + ClAer --> BrCl                                                                             ', & ! index 505
     'BrONO2 + BrAer --> Br2                                                                              ', & ! index 506
     'BrONO2 + ClAer --> BrCl                                                                             ', & ! index 507
     '        BrONO2 --> DUMMY + HOBr                                                                     ', & ! index 508
     '  N2O5 + BrAer --> DUMMY + BrNO2                                                                    ', & ! index 509
     ' Cl2 + 2 BrAer --> 2 BrCl                                                                           ' /) ! index up to 510
  CHARACTER(LEN=100), PARAMETER, DIMENSION(3) :: EQN_NAMES_17 = (/ &
     '           Cl2 --> 2 ClAer                                                                          ', & ! index 511
     '          BrCl --> BrAer + ClAer                                                                    ', & ! index 512
     '        ClONO2 --> ClAer                                                                            ' /) ! index up to 513
  CHARACTER(LEN=100), PARAMETER, DIMENSION(513) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8, EQN_NAMES_9, &
    EQN_NAMES_10, EQN_NAMES_11, EQN_NAMES_12, EQN_NAMES_13, EQN_NAMES_14, &
    EQN_NAMES_15, EQN_NAMES_16, EQN_NAMES_17 /)

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE mech_Monitor
