! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : isoprene_full_v5_nofixedspc_Initialize.f90
! Equation file        : isoprene_full_v5_nofixedspc.def
! Output root filename : isoprene_full_v5_nofixedspc
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE isoprene_full_v5_nofixedspc_Initialize

  USE isoprene_full_v5_nofixedspc_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE isoprene_full_v5_nofixedspc_Global

  USE isoprene_full_v5_nofixedspc_Parameters

  INTEGER :: i
  REAL(kind=dp) :: x

! ~~~ Define scale factor for units
  CFACTOR = 2.500000e+19_dp

! ~~~ Zero C array
  C = 0.0_dp

! ~~~ Set initial species concentrations
  C(366) = (1.0E-8)*CFACTOR
  C(383) = (8.0E-9)*CFACTOR
  C(388) = (1.0E-13)*CFACTOR
  C(389) = (4.0E-11)*CFACTOR
  C(394) = (8.0E-11)*CFACTOR
  C(395) = (2.1E-1)*CFACTOR

! Begin constant rate coefficients
  RCONST(5) = 3.6e-13
  RCONST(6) = 7.5e-13
  RCONST(7) = 7.5e-13
  RCONST(8) = 1.4e-13
  RCONST(9) = 4.9e-13
  RCONST(10) = 6.5e-13
  RCONST(11) = 6.5e-13
  RCONST(12) = 2.1e-13
  RCONST(66) = 1e-14
  RCONST(74) = 1e-14
  RCONST(90) = 6.92e-14
  RCONST(151) = 1e-14
  RCONST(152) = 2700
  RCONST(181) = 1e-14
  RCONST(182) = 2700
  RCONST(260) = 2.9e-11
  RCONST(261) = 1e+07
  RCONST(262) = 4e+09
  RCONST(263) = 8.18e+07
  RCONST(264) = 1000
  RCONST(265) = 1e+07
  RCONST(271) = 1e+08
  RCONST(273) = 1e-14
  RCONST(277) = 1e-14
  RCONST(362) = 1e-14
  RCONST(363) = 183500
  RCONST(365) = 1e-14
  RCONST(366) = 183500
  RCONST(368) = 1e-14
  RCONST(369) = 235800
  RCONST(371) = 1e-14
  RCONST(372) = 235800
  RCONST(379) = 34500
  RCONST(414) = 3e+06
  RCONST(415) = 4e+06
  RCONST(435) = 9e-12
  RCONST(438) = 9e-12
  RCONST(447) = 1e-14
  RCONST(448) = 52000
  RCONST(450) = 1e-14
  RCONST(453) = 2e+06
  RCONST(454) = 3e+06
  RCONST(458) = 2e+06
  RCONST(459) = 4e+06
  RCONST(460) = 10
  RCONST(462) = 10
  RCONST(463) = 1e+06
  RCONST(465) = 7.5e-13
  RCONST(472) = 1e-14
  RCONST(473) = 52000
  RCONST(475) = 1e-14
  RCONST(480) = 2e+06
  RCONST(481) = 3e+06
  RCONST(484) = 2e+06
  RCONST(485) = 4e+06
  RCONST(486) = 10
  RCONST(488) = 10
  RCONST(489) = 1e+06
  RCONST(491) = 6.5e-13
  RCONST(495) = 1e-14
  RCONST(510) = 1e-14
  RCONST(531) = 3.7e-11
  RCONST(532) = 2e-11
  RCONST(542) = 1e-15
  RCONST(543) = 1e-15
  RCONST(546) = 4.31e-12
  RCONST(547) = 1.8e-13
  RCONST(605) = 2.3e-12
  RCONST(606) = 2.3e-12
  RCONST(607) = 2.3e-12
  RCONST(608) = 2.3e-12
  RCONST(612) = 2.3e-12
  RCONST(630) = 1e-14
  RCONST(631) = 92000
  RCONST(634) = 1e-14
  RCONST(635) = 96100
  RCONST(637) = 1e-14
  RCONST(638) = 7730
  RCONST(640) = 1e-14
  RCONST(641) = 92000
  RCONST(644) = 1e-14
  RCONST(645) = 96100
  RCONST(647) = 1e-14
  RCONST(648) = 7730
  RCONST(696) = 4e+06
  RCONST(697) = 4e+06
  RCONST(698) = 2e+06
  RCONST(699) = 2e+06
  RCONST(700) = 3e+06
  RCONST(701) = 3e+06
  RCONST(702) = 2e+06
  RCONST(703) = 2e+06
  RCONST(704) = 3e+06
  RCONST(705) = 3e+06
  RCONST(706) = 4e+06
  RCONST(707) = 4e+06
  RCONST(734) = 1e-14
  RCONST(738) = 1e-14
  RCONST(744) = 1e-14
  RCONST(745) = 207000
  RCONST(761) = 1e-14
  RCONST(769) = 9e-12
  RCONST(775) = 1e-14
  RCONST(783) = 9e-12
  RCONST(788) = 1e-14
  RCONST(789) = 7730
  RCONST(792) = 1e-14
  RCONST(793) = 7730
  RCONST(824) = 1e-14
  RCONST(825) = 7730
  RCONST(832) = 1e-14
  RCONST(833) = 7730
  RCONST(871) = 4e+06
  RCONST(872) = 3e+06
  RCONST(879) = 3e+06
  RCONST(880) = 4e+06
  RCONST(886) = 1000
! End constant rate coefficients

! Begin inlined code from F90_INIT

        TSTART = 0
        TEND = TSTART + 259200
        DT = 60.0
        TEMP = 298

! End inlined code from F90_INIT

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE isoprene_full_v5_nofixedspc_Initialize

