! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : form1985_StoichiomSP.f90
! Equation file        : form1985.kpp
! Output root filename : form1985
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE form1985_StoichiomSP

  USE form1985_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(26) :: CROW_JVRP = (/ &
       1,  3,  5,  6,  8, 10, 11, 12, 13, 15, 17, 19, & ! index 1 - 12
      21, 23, 24, 26, 28, 30, 32, 34, 35, 37, 39, 41, & ! index 13 - 24
      43, 45 /) ! index up to 26

  INTEGER, PARAMETER, DIMENSION(44) :: ICOL_JVRP = (/ &
       6, 12,  9, 11,  5,  7, 11,  5,  7,  5,  9,  9, & ! index 1 - 12
       3,  7,  3,  9,  8, 11,  8, 12,  8, 12,  9,  4, & ! index 13 - 24
      10, 10, 11,  5,  8,  5,  8,  5, 10,  6,  4,  7, & ! index 25 - 36
      11, 12,  8,  9,  8,  9,  8,  9 /) ! index up to 44

  INTEGER, PARAMETER, DIMENSION(44) :: IROW_JVRP = (/ &
       1,  1,  2,  2,  3,  4,  4,  5,  5,  6,  7,  8, & ! index 1 - 12
       9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 15, & ! index 13 - 24
      15, 16, 16, 17, 17, 18, 18, 19, 19, 20, 21, 21, & ! index 25 - 36
      22, 22, 23, 23, 24, 24, 25, 25 /) ! index up to 44



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(26) :: CCOL_STOICM = (/ &
       1,  5,  9, 11, 15, 19, 20, 21, 24, 28, 32, 36, & ! index 1 - 12
      40, 43, 46, 50, 54, 58, 62, 66, 69, 73, 77, 80, & ! index 13 - 24
      84, 88 /) ! index up to 26

  INTEGER, PARAMETER, DIMENSION(87) :: IROW_STOICM = (/ &
       3,  6,  9, 12,  5,  6,  9, 11,  5,  7,  1,  6, & ! index 1 - 12
       7, 11,  1,  5,  7,  9,  5,  9,  5,  9, 12,  2, & ! index 13 - 24
       3,  7,  8,  2,  3,  7,  9,  4,  6,  8, 11,  7, & ! index 25 - 36
       8, 10, 12,  8,  9, 12,  8,  9, 12,  4,  7,  8, & ! index 37 - 48
      10,  6,  7, 10, 11,  4,  5,  8,  9,  1,  5,  7, & ! index 49 - 60
       8,  5,  7,  9, 10,  3,  6,  8,  1,  4,  7,  8, & ! index 61 - 72
       6,  9, 11, 12,  7,  8,  9,  1,  8,  9, 10,  4, & ! index 73 - 84
       8,  9, 12 /) ! index up to 87

  INTEGER, PARAMETER, DIMENSION(87) :: ICOL_STOICM = (/ &
       1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  4,  4, & ! index 1 - 12
       4,  4,  5,  5,  5,  5,  6,  7,  8,  8,  8,  9, & ! index 13 - 24
       9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, & ! index 25 - 36
      12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, & ! index 37 - 48
      15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, & ! index 49 - 60
      18, 19, 19, 19, 19, 20, 20, 20, 21, 21, 21, 21, & ! index 61 - 72
      22, 22, 22, 22, 23, 23, 23, 24, 24, 24, 24, 25, & ! index 73 - 84
      25, 25, 25 /) ! index up to 87

  REAL(kind=dp), PARAMETER, DIMENSION(87) :: STOICM = (/ &
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 1 - 5
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  2.000000e+00_dp, & ! index 6 - 10
       1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 11 - 15
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, & ! index 16 - 20
       1.000000e+00_dp,  -2.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 21 - 25
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 26 - 30
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, & ! index 31 - 35
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, & ! index 36 - 40
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 41 - 45
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 46 - 50
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 51 - 55
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 56 - 60
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 61 - 65
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 66 - 70
       -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 71 - 75
       -1.000000e+00_dp,  2.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 76 - 80
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 81 - 85
       -1.000000e+00_dp,  1.000000e+00_dp /) ! index up to 87


END MODULE form1985_StoichiomSP

