! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : isoprene_reduced_plus_v5_Initialize.f90
! Equation file        : isoprene_reduced_plus_v5.def
! Output root filename : isoprene_reduced_plus_v5
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE isoprene_reduced_plus_v5_Initialize

  USE isoprene_reduced_plus_v5_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE isoprene_reduced_plus_v5_Global

  USE isoprene_reduced_plus_v5_Parameters

  INTEGER :: i
  REAL(kind=dp) :: x

! ~~~ Define scale factor for units
  CFACTOR = 2.500000e+19_dp

! ~~~ Zero C array
  C = 0.0_dp

! ~~~ Set initial species concentrations
  C(100) = (1.0E-8)*CFACTOR
  C(136) = (8.0E-9)*CFACTOR
  C(140) = (8.0E-11)*CFACTOR
  C(144) = (1.0E-13)*CFACTOR
  C(145) = (4.0E-11)*CFACTOR
  C(146) = (2.1E-1)*CFACTOR

! Begin constant rate coefficients
  RCONST(100) = 2.9e-11
  RCONST(107) = 9e-12
  RCONST(110) = 9e-12
  RCONST(133) = 1.3e-17
  RCONST(134) = 1.7e-15
  RCONST(141) = 2.56e-12
  RCONST(142) = 3.71e-12
  RCONST(143) = 1.61e-12
  RCONST(144) = 2.8e-13
  RCONST(145) = 1.18e-12
  RCONST(146) = 1.92e-12
  RCONST(147) = 7.71e-12
  RCONST(148) = 2.3e-12
  RCONST(149) = 2.3e-12
  RCONST(232) = 2.23e-12
  RCONST(234) = 5.77e-11
  RCONST(235) = 5.77e-11
  RCONST(245) = 5.77e-11
  RCONST(251) = 2.91e-11
  RCONST(255) = 1.51e-11
  RCONST(257) = 8.39e-12
  RCONST(266) = 4e-12
  RCONST(268) = 1.34e-12
  RCONST(269) = 4.42e-12
  RCONST(274) = 3.4e-12
  RCONST(277) = 8e-12
  RCONST(279) = 8e-13
  RCONST(281) = 1e-13
  RCONST(283) = 4.5e-13
  RCONST(299) = 5.5e-16
  RCONST(305) = 3e-14
  RCONST(306) = 4e-12
  RCONST(308) = 8e-13
  RCONST(309) = 3.7e-12
  RCONST(314) = 1.2e-12
  RCONST(327) = 1e-11
  RCONST(332) = 1e-11
  RCONST(333) = 2.73e-12
  RCONST(334) = 6.19e-12
  RCONST(337) = 1.12e-12
  RCONST(338) = 1.68e-13
  RCONST(339) = 3.63e-12
  RCONST(342) = 1.12e-14
  RCONST(349) = 1e-11
  RCONST(352) = 2e-12
  RCONST(355) = 2e-12
  RCONST(357) = 3e-12
  RCONST(360) = 1e-11
  RCONST(363) = 1e-11
  RCONST(366) = 3e-12
  RCONST(368) = 3e-12
  RCONST(372) = 1e-12
  RCONST(378) = 2.25e-11
! End constant rate coefficients

! Begin inlined code from F90_INIT

        TSTART = 0
        TEND = TSTART + 259200
        DT = 60.0
        TEMP = 298

! End inlined code from F90_INIT

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE isoprene_reduced_plus_v5_Initialize

