! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
! 
! File                 : RACM_Monitor.f90
! Equation file        : RACM.kpp
! Output root filename : RACM
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE RACM_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(84) :: SPC_NAMES = (/ &
     'SULF                            ','CO2                             ','ORA1                            ', & ! index 1 - 3
     'ORA2                            ','SO2                             ','O1D                             ', & ! index 4 - 6
     'ISHP                            ','HC5                             ','TOL                             ', & ! index 7 - 9
     'XYL                             ','N2O5                            ','HC8                             ', & ! index 10 - 12
     'MAHP                            ','HC3                             ','UDD                             ', & ! index 13 - 15
     'NALD                            ','ETH                             ','CH4                             ', & ! index 16 - 18
     'HNO4                            ','OP1                             ','MPAN                            ', & ! index 19 - 21
     'HACE                            ','HONO                            ','HKET                            ', & ! index 22 - 24
     'O3P                             ','PHO                             ','H2O2                            ', & ! index 25 - 27
     'ADDT                            ','ADDX                            ','ETE                             ', & ! index 28 - 30
     'ADDC                            ','HNO3                            ','PAA                             ', & ! index 31 - 33
     'ISON                            ','SESQ                            ','PAN                             ', & ! index 34 - 36
     'API                             ','CO                              ','LIM                             ', & ! index 37 - 39
     'ISO                             ','MBO                             ','CSL                             ', & ! index 40 - 42
     'DIEN                            ','MACP                            ','TPAN                            ', & ! index 43 - 45
     'GLY                             ','ETEP                            ','OLTP                            ', & ! index 46 - 48
     'MACR                            ','ISOP                            ','APIP                            ', & ! index 49 - 51
     'KET                             ','MGLY                            ','CSLP                            ', & ! index 52 - 54
     'LIMP                            ','HC8P                            ','HC5P                            ', & ! index 55 - 57
     'HCHO                            ','TOLP                            ','XYLP                            ', & ! index 58 - 60
     'OLIP                            ','ONIT                            ','DCB                             ', & ! index 61 - 63
     'XO2                             ','OLT                             ','ALD                             ', & ! index 64 - 66
     'OLI                             ','OLND                            ','OLNN                            ', & ! index 67 - 69
     'ETHP                            ','TCO3                            ','O3                              ', & ! index 70 - 72
     'HC3P                            ','MO2                             ','OP2                             ', & ! index 73 - 75
     'HO2                             ','ACO3                            ','HO                              ', & ! index 76 - 78
     'NO3                             ','KETP                            ','NO                              ', & ! index 79 - 81
     'NO2                             ','H2O                             ','M                               ' /) ! index up to 84

  INTEGER, PARAMETER, DIMENSION(84) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, & ! index 1 - 12
      13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, & ! index 13 - 24
      25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, & ! index 25 - 36
      37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, & ! index 37 - 48
      49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, & ! index 49 - 60
      61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, & ! index 61 - 72
      73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84 /) ! index up to 84

  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=32), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '        NO2 --> O3P + NO                                                                            ', & ! index 1
     '         O3 --> O1D                                                                                 ', & ! index 2
     '         O3 --> O3P                                                                                 ', & ! index 3
     '       HONO --> HO + NO                                                                             ', & ! index 4
     '       HNO3 --> HO + NO2                                                                            ', & ! index 5
     '       HNO4 --> 0.65 HO2 + 0.35 HO + 0.35 NO3 + 0.65 NO2                                            ', & ! index 6
     '        NO3 --> NO                                                                                  ', & ! index 7
     '        NO3 --> O3P + NO2                                                                           ', & ! index 8
     '       H2O2 --> 2 HO                                                                                ', & ! index 9
     '       HCHO --> CO                                                                                  ', & ! index 10
     '       HCHO --> CO + 2 HO2                                                                          ', & ! index 11
     '        ALD --> CO + MO2 + HO2                                                                      ', & ! index 12
     '        OP1 --> HCHO + HO2 + HO                                                                     ', & ! index 13
     '        OP2 --> ALD + HO2 + HO                                                                      ', & ! index 14
     '        PAA --> MO2 + HO                                                                            ', & ! index 15
     '        KET --> ETHP + ACO3                                                                         ', & ! index 16
     '        GLY --> 1.87 CO + 0.13 HCHO                                                                 ', & ! index 17
     '        GLY --> 1.55 CO + 0.45 HCHO + 0.8 HO2                                                       ', & ! index 18
     '       MGLY --> CO + HO2 + ACO3                                                                     ', & ! index 19
     '        DCB --> TCO3 + HO2                                                                          ', & ! index 20
     '       ONIT --> 0.8 KET + 0.2 ALD + HO2 + NO2                                                       ', & ! index 21
     '       MACR --> CO + HCHO + HO2 + ACO3                                                              ', & ! index 22
     '       HKET --> HCHO + HO2 + ACO3                                                                   ', & ! index 23
     '    O3P + M --> O3                                                                                  ', & ! index 24
     '   O3P + O3 --> M                                                                                   ', & ! index 25
     '    O1D + M --> O3P                                                                                 ', & ! index 26
     '  O1D + H2O --> 2 HO                                                                                ', & ! index 27
     '    O3 + HO --> HO2                                                                                 ', & ! index 28
     '   O3 + HO2 --> HO                                                                                  ', & ! index 29
     '   HO2 + HO --> H2O                                                                                 ' /) ! index up to 30
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '  H2O2 + HO --> HO2 + H2O                                                                           ', & ! index 31
     '      2 HO2 --> H2O2                                                                                ', & ! index 32
     '2 HO2 + H2O --> H2O2 + H2O                                                                          ', & ! index 33
     '   O3P + NO --> NO2                                                                                 ', & ! index 34
     '  O3P + NO2 --> NO                                                                                  ', & ! index 35
     '  O3P + NO2 --> NO3                                                                                 ', & ! index 36
     '    HO + NO --> HONO                                                                                ', & ! index 37
     '   HO + NO2 --> HNO3                                                                                ', & ! index 38
     '   HO + NO3 --> HO2 + NO2                                                                           ', & ! index 39
     '   HO2 + NO --> HO + NO2                                                                            ', & ! index 40
     '  HO2 + NO2 --> HNO4                                                                                ', & ! index 41
     '       HNO4 --> HO2 + NO2                                                                           ', & ! index 42
     '  HO2 + NO3 --> 0.3 HNO3 + 0.7 HO + 0.7 NO2                                                         ', & ! index 43
     '  HONO + HO --> NO2 + H2O                                                                           ', & ! index 44
     '  HNO3 + HO --> NO3 + H2O                                                                           ', & ! index 45
     '  HNO4 + HO --> NO2 + H2O                                                                           ', & ! index 46
     '    O3 + NO --> NO2                                                                                 ', & ! index 47
     '   O3 + NO2 --> NO3                                                                                 ', & ! index 48
     '   2 NO + M --> 2 NO2                                                                               ', & ! index 49
     '   NO3 + NO --> 2 NO2                                                                               ', & ! index 50
     '  NO3 + NO2 --> NO + NO2                                                                            ', & ! index 51
     '  NO3 + NO2 --> N2O5                                                                                ', & ! index 52
     '       N2O5 --> NO3 + NO2                                                                           ', & ! index 53
     '      2 NO3 --> 2 NO2                                                                               ', & ! index 54
     '     HO + M --> HO2 + H2O                                                                           ', & ! index 55
     '   SO2 + HO --> SULF + HO2                                                                          ', & ! index 56
     '    CO + HO --> CO2 + HO2                                                                           ', & ! index 57
     '  NALD + HO --> CO + HCHO + NO2                                                                     ', & ! index 58
     '  HACE + HO --> MGLY + HO2                                                                          ', & ! index 59
     '   CH4 + HO --> MO2 + H2O                                                                           ' /) ! index up to 60
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '   ETH + HO --> ETHP + H2O                                                                          ', & ! index 61
     '   HC3 + HO --> 0.036 ORA1 + 0.036 CO + 0.036 GLY + 0.01 HCHO + 0.335 ALD + 0.583 HC3P + 0.3... etc.', & ! index 62
     '   HC5 + HO --> 0.25 KET + 0.75 HC5P + 0.25 HO2 + H2O                                               ', & ! index 63
     '   HC8 + HO --> 0.024 HKET + 0.9511 HC8P + 0.025 ALD + 0.049 HO2 + H2O                              ', & ! index 64
     '   ETE + HO --> ETEP                                                                                ', & ! index 65
     '   OLT + HO --> OLTP                                                                                ', & ! index 66
     '   OLI + HO --> OLIP                                                                                ', & ! index 67
     '  DIEN + HO --> ISOP                                                                                ', & ! index 68
     '   ISO + HO --> ISOP                                                                                ', & ! index 69
     '   API + HO --> APIP                                                                                ', & ! index 70
     '   LIM + HO --> LIMP                                                                                ', & ! index 71
     '   TOL + HO --> 0.9 ADDT + 0.1 XO2 + 0.1 HO2                                                        ', & ! index 72
     '   XYL + HO --> 0.9 ADDX + 0.1 XO2 + 0.1 HO2                                                        ', & ! index 73
     '   CSL + HO --> 0.1 PHO + 0.85 ADDC + 0.05 XO2 + 0.05 HO2                                           ', & ! index 74
     '  HCHO + HO --> CO + HO2 + H2O                                                                      ', & ! index 75
     '   ALD + HO --> ACO3 + H2O                                                                          ', & ! index 76
     '   KET + HO --> KETP + H2O                                                                          ', & ! index 77
     '  HKET + HO --> MGLY + HO2 + H2O                                                                    ', & ! index 78
     '   GLY + HO --> 2 CO + HO2 + H2O                                                                    ', & ! index 79
     '  MGLY + HO --> CO + ACO3 + H2O                                                                     ', & ! index 80
     '  MACR + HO --> MACP                                                                                ', & ! index 81
     '   DCB + HO --> 0.35 UDD + 0.15 GLY + 0.15 MGLY + 0.5 XO2 + 0.5 TCO3 + 0.5 HO2                      ', & ! index 82
     '   UDD + HO --> 0.12 KET + 0.88 ALD + HO2                                                           ', & ! index 83
     '   OP1 + HO --> 0.35 HCHO + 0.65 MO2 + 0.35 HO                                                      ', & ! index 84
     '   OP2 + HO --> 0.41 KET + 0.07 XO2 + 0.08 ALD + 0.44 HC3P + 0.49 HO                                ', & ! index 85
     '   PAA + HO --> 0.35 HCHO + 0.35 XO2 + 0.35 HO2 + 0.65 ACO3                                         ', & ! index 86
     '   PAN + HO --> HCHO + XO2 + NO3 + H2O                                                              ', & ! index 87
     '  TPAN + HO --> 0.6 HKET + 0.4 PAN + 0.4 HCHO + XO2 + 0.4 HO2 + 0.6 NO3                             ', & ! index 88
     '  ONIT + HO --> HC3P + NO2 + H2O                                                                    ', & ! index 89
     ' HCHO + NO3 --> HNO3 + CO + HO2                                                                     ' /) ! index up to 90
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '  ALD + NO3 --> HNO3 + ACO3                                                                         ', & ! index 91
     '  GLY + NO3 --> HNO3 + 2 CO + HO2                                                                   ', & ! index 92
     ' MGLY + NO3 --> HNO3 + CO + ACO3                                                                    ', & ! index 93
     '  MAHP + HO --> MACP                                                                                ', & ! index 94
     '  DCB + NO3 --> 0.5 HNO3 + 0.25 GLY + 0.03 KET + 0.25 MGLY + 0.5 XO2 + 0.25 ALD + 0.5 TCO3 +... etc.', & ! index 95
     '  CSL + NO3 --> PHO + HNO3                                                                          ', & ! index 96
     '  ETE + NO3 --> 0.2 OLND + 0.8 OLNN                                                                 ', & ! index 97
     '  OLT + NO3 --> 0.57 OLND + 0.43 OLNN                                                               ', & ! index 98
     '  OLI + NO3 --> 0.89 OLND + 0.11 OLNN                                                               ', & ! index 99
     ' DIEN + NO3 --> 0.9 MACR + 0.1 OLND + 0.9 OLNN                                                      ', & ! index 100
     '  ISO + NO3 --> ISON                                                                                ', & ! index 101
     '  API + NO3 --> 0.9 OLND + 0.1 OLNN                                                                 ', & ! index 102
     '  LIM + NO3 --> 0.87 OLND + 0.13 OLNN                                                               ', & ! index 103
     ' TPAN + NO3 --> 0.4 PAN + 0.4 HCHO + 0.6 ONIT + XO2 + 0.6 NO3 + 0.4 NO2                             ', & ! index 104
     '   ETE + O3 --> 0.37 ORA1 + 0.43 CO + HCHO + 0.26 HO2 + 0.12 HO                                     ', & ! index 105
     '   OLT + O3 --> 0.14 ORA1 + 0.1 ORA2 + 0.03 ETH + 0.06 CH4 + 0.006 H2O2 + 0.37 CO + 0.03 KET... etc.', & ! index 106
     '   OLI + O3 --> 0.14 ORA2 + 0.06 ETH + 0.07 CH4 + 0.011 H2O2 + 0.3 CO + 0.16 KET + 0.02 HCHO... etc.', & ! index 107
     '  DIEN + O3 --> 0.15 ORA1 + 0.09 O3P + 0.001 H2O2 + 0.36 CO + 0.39 MACR + 0.9 HCHO + 0.13 XO... etc.', & ! index 108
     '   ISO + O3 --> 0.28 ORA1 + 0.09 H2O2 + 0.14 CO + 0.1 MACP + 0.65 MACR + 0.58 HCHO + 0.08 MO... etc.', & ! index 109
     '   API + O3 --> 0.02 H2O2 + 0.14 CO + 0.53 KET + 0.65 ALD + 0.2 ETHP + 0.1 HO2 + 0.85 HO + 0.42 KETP', & ! index 110
     '   LIM + O3 --> 0.01 ORA1 + 0.07 ORA2 + 0.02 H2O2 + 0.14 CO + 0.79 MACR + 0.04 HCHO + 0.46 O... etc.', & ! index 111
     '  MACR + O3 --> 0.45 ORA1 + 0.22 CO + 0.9 MGLY + 0.32 HO2 + 0.1 ACO3 + 0.19 HO                      ', & ! index 112
     '   DCB + O3 --> 0.11 ORA1 + 0.21 ORA2 + 0.11 PAA + 0.66 CO + 0.5 GLY + 0.62 MGLY + 0.16 ALD ... etc.', & ! index 113
     '  TPAN + O3 --> 0.11 ORA1 + 0.3 PAN + 0.13 CO + 0.7 HCHO + 0.08 HO2 + 0.7 ACO3 + 0.036 HO + 0.7 NO2 ', & ! index 114
     '  PHO + NO2 --> 0.1 CSL + ONIT                                                                      ', & ! index 115
     '  PHO + HO2 --> CSL                                                                                 ', & ! index 116
     ' ADDT + NO2 --> HONO + CSL                                                                          ', & ! index 117
     '   ADDT + M --> 0.02 CSL + 0.98 TOLP + 0.02 HO2                                                     ', & ! index 118
     '  ADDT + O3 --> CSL + HO                                                                            ', & ! index 119
     ' ADDX + NO2 --> HONO + CSL                                                                          ' /) ! index up to 120
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '   ADDX + M --> 0.02 CSL + 0.98 XYLP + 0.02 HO2                                                     ', & ! index 121
     '  ADDX + O3 --> CSL + HO                                                                            ', & ! index 122
     ' ADDC + NO2 --> HONO + CSL                                                                          ', & ! index 123
     '   ADDC + M --> 0.02 CSL + 0.98 CSLP + 0.02 HO2                                                     ', & ! index 124
     '  ADDC + O3 --> CSL + HO                                                                            ', & ! index 125
     ' ACO3 + NO2 --> PAN                                                                                 ', & ! index 126
     '        PAN --> ACO3 + NO2                                                                          ', & ! index 127
     ' TCO3 + NO2 --> TPAN                                                                                ', & ! index 128
     '       TPAN --> TCO3 + NO2                                                                          ', & ! index 129
     '   MO2 + NO --> HCHO + HO2 + NO2                                                                    ', & ! index 130
     '  ETHP + NO --> ALD + HO2 + NO2                                                                     ', & ! index 131
     '  HC3P + NO --> 0.063 GLY + 0.623 KET + 0.047 HCHO + 0.059 ONIT + 0.048 XO2 + 0.233 ALD + 0.... etc.', & ! index 132
     '  HC5P + NO --> 0.722 KET + 0.021 HCHO + 0.124 ONIT + 0.334 XO2 + 0.211 ALD + 0.245 ETHP + 0... etc.', & ! index 133
     '  HC8P + NO --> 0.642 KET + 0.261 ONIT + 0.416 XO2 + 0.15 ALD + 0.133 ETHP + 0.606 HO2 + 0.739 NO2  ', & ! index 134
     '  ETEP + NO --> 1.6 HCHO + 0.2 ALD + HO2 + NO2                                                      ', & ! index 135
     '  OLTP + NO --> 0.06 KET + HCHO + 0.94 ALD + HO2 + NO2                                              ', & ! index 136
     '  OLIP + NO --> 0.29 KET + 1.71 ALD + HO2 + NO2                                                     ', & ! index 137
     '  ISOP + NO --> 0.046 ISON + MACR + HCHO + HO2 + NO2                                                ', & ! index 138
     '  APIP + NO --> 0.8 KET + 0.2 ONIT + 0.8 ALD + 0.8 HO2 + 0.8 NO2                                    ', & ! index 139
     '  LIMP + NO --> 0.4 MACR + 0.25 HCHO + 0.35 ONIT + 0.25 OLI + 0.65 HO2 + 0.65 NO2                   ', & ! index 140
     '  TOLP + NO --> 1.2 GLY + 0.65 MGLY + 0.05 ONIT + 0.5 DCB + 0.95 HO2 + 0.95 NO2                     ', & ! index 141
     '  XYLP + NO --> 0.35 GLY + 0.6 MGLY + 0.05 ONIT + 0.95 DCB + 0.95 HO2 + 0.95 NO2                    ', & ! index 142
     '  CSLP + NO --> GLY + MGLY + HO2 + NO2                                                              ', & ! index 143
     '  ACO3 + NO --> MO2 + NO2                                                                           ', & ! index 144
     '  TCO3 + NO --> HCHO + ACO3 + NO2                                                                   ', & ! index 145
     '  KETP + NO --> 0.54 MGLY + 0.16 XO2 + 0.46 ALD + 0.77 HO2 + 0.23 ACO3 + NO2                        ', & ! index 146
     '  OLNN + NO --> ONIT + HO2 + NO2                                                                    ', & ! index 147
     '  OLND + NO --> 0.464 KET + 0.287 HCHO + 1.24 ALD + 2 NO2                                           ', & ! index 148
     '  MO2 + HO2 --> OP1                                                                                 ', & ! index 149
     ' ETHP + HO2 --> OP2                                                                                 ' /) ! index up to 150
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     ' HC3P + HO2 --> OP2                                                                                 ', & ! index 151
     ' HC5P + HO2 --> OP2                                                                                 ', & ! index 152
     ' HC8P + HO2 --> OP2                                                                                 ', & ! index 153
     ' ETEP + HO2 --> OP2                                                                                 ', & ! index 154
     ' OLTP + HO2 --> OP2                                                                                 ', & ! index 155
     ' OLIP + HO2 --> OP2                                                                                 ', & ! index 156
     ' ISOP + HO2 --> ISHP                                                                                ', & ! index 157
     ' APIP + HO2 --> OP2                                                                                 ', & ! index 158
     ' LIMP + HO2 --> OP2                                                                                 ', & ! index 159
     ' TOLP + HO2 --> OP2                                                                                 ', & ! index 160
     ' XYLP + HO2 --> OP2                                                                                 ', & ! index 161
     ' CSLP + HO2 --> OP2                                                                                 ', & ! index 162
     ' HO2 + ACO3 --> PAA                                                                                 ', & ! index 163
     ' HO2 + ACO3 --> ORA2 + O3                                                                           ', & ! index 164
     ' TCO3 + HO2 --> OP2                                                                                 ', & ! index 165
     ' TCO3 + HO2 --> ORA2 + O3                                                                           ', & ! index 166
     ' HO2 + KETP --> OP2                                                                                 ', & ! index 167
     ' OLNN + HO2 --> ONIT                                                                                ', & ! index 168
     ' OLND + HO2 --> ONIT                                                                                ', & ! index 169
     '      2 MO2 --> 1.33 HCHO + 0.66 HO2                                                                ', & ! index 170
     ' ETHP + MO2 --> 0.75 HCHO + 0.75 ALD + HO2                                                          ', & ! index 171
     ' HC3P + MO2 --> 0.119 GLY + 0.018 KET + 0.005 MGLY + 0.81 HCHO + 0.085 XO2 + 0.58 ALD + 0.00... etc.', & ! index 172
     ' HC5P + MO2 --> 0.24 KET + 0.829 HCHO + 0.245 XO2 + 0.523 ALD + 0.014 ETHP + 0.049 MO2 + 0.946 HO2  ', & ! index 173
     ' HC8P + MO2 --> 0.419 KET + 0.753 HCHO + 0.322 XO2 + 0.411 ALD + 0.013 ETHP + 0.993 HO2             ', & ! index 174
     ' ETEP + MO2 --> 1.55 HCHO + 0.35 ALD + HO2                                                          ', & ! index 175
     ' OLTP + MO2 --> 0.081 KET + 1.25 HCHO + 0.669 ALD + HO2                                             ', & ! index 176
     ' OLIP + MO2 --> 0.313 KET + 0.755 HCHO + 0.932 ALD + HO2                                            ', & ! index 177
     ' ISOP + MO2 --> 0.55 MACR + 1.09 HCHO + 0.37 OLT + 0.08 OLI + HO2                                   ', & ! index 178
     ' APIP + MO2 --> KET + HCHO + ALD + 2 HO2                                                            ', & ! index 179
     ' LIMP + MO2 --> 0.6 MACR + 1.4 HCHO + 0.4 OLI + 2 HO2                                               ' /) ! index up to 180
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     ' TOLP + MO2 --> 0.65 GLY + 0.35 MGLY + HCHO + DCB + HO2                                             ', & ! index 181
     ' XYLP + MO2 --> 0.37 GLY + 0.63 MGLY + HCHO + DCB + HO2                                             ', & ! index 182
     ' CSLP + MO2 --> GLY + MGLY + HCHO + 2 HO2                                                           ', & ! index 183
     ' MO2 + ACO3 --> HCHO + MO2 + HO2                                                                    ', & ! index 184
     ' MO2 + ACO3 --> ORA2 + HCHO                                                                         ', & ! index 185
     ' TCO3 + MO2 --> 2 HCHO + HO2 + ACO3                                                                 ', & ! index 186
     ' TCO3 + MO2 --> ORA2 + HCHO                                                                         ', & ! index 187
     ' MO2 + KETP --> 0.3 HKET + 0.4 MGLY + 0.75 HCHO + 0.08 XO2 + 0.3 ALD + 0.88 HO2 + 0.12 ACO3         ', & ! index 188
     ' OLNN + MO2 --> 0.75 HCHO + ONIT + HO2                                                              ', & ! index 189
     ' OLND + MO2 --> 0.149 KET + 0.96 HCHO + 0.5 ONIT + 0.64 ALD + 0.5 HO2 + 0.5 NO2                     ', & ! index 190
     'ETHP + ACO3 --> 0.5 ORA2 + ALD + 0.5 MO2 + 0.5 HO2                                                  ', & ! index 191
     'HC3P + ACO3 --> 0.499 ORA2 + 0.1 GLY + 0.127 KET + 0.004 MGLY + 0.091 HCHO + 0.071 XO2 + 0.7... etc.', & ! index 192
     'HC5P + ACO3 --> 0.495 ORA2 + 0.33 KET + 0.076 HCHO + 0.237 XO2 + 0.677 ALD + 0.018 ETHP + 0.... etc.', & ! index 193
     'HC8P + ACO3 --> 0.495 ORA2 + 0.581 KET + 0.318 XO2 + 0.497 ALD + 0.015 ETHP + 0.507 MO2 + 0.489 HO2 ', & ! index 194
     'ETEP + ACO3 --> 0.5 ORA2 + 0.8 HCHO + 0.6 ALD + 0.5 MO2 + 0.5 HO2                                   ', & ! index 195
     'OLTP + ACO3 --> 0.499 ORA2 + 0.141 KET + 0.501 HCHO + 0.859 ALD + 0.501 MO2 + 0.501 HO2             ', & ! index 196
     'OLIP + ACO3 --> 0.49 ORA2 + 0.569 KET + 0.941 ALD + 0.51 MO2 + 0.51 HO2                             ', & ! index 197
     'ISOP + ACO3 --> 0.494 ORA2 + 0.771 MACR + 0.34 HCHO + 0.229 OLT + 0.506 MO2 + 0.506 HO2             ', & ! index 198
     'APIP + ACO3 --> KET + ALD + MO2 + HO2                                                               ', & ! index 199
     'LIMP + ACO3 --> 0.6 MACR + 0.4 HCHO + 0.4 OLI + MO2 + HO2                                           ', & ! index 200
     'TOLP + ACO3 --> 0.65 GLY + 0.35 MGLY + DCB + MO2 + HO2                                              ', & ! index 201
     'XYLP + ACO3 --> 0.37 GLY + 0.63 MGLY + DCB + MO2 + HO2                                              ', & ! index 202
     'CSLP + ACO3 --> GLY + MGLY + MO2 + HO2                                                              ', & ! index 203
     '     2 ACO3 --> 2 MO2                                                                               ', & ! index 204
     'TCO3 + ACO3 --> HCHO + MO2 + ACO3                                                                   ', & ! index 205
     'ACO3 + KETP --> 0.5 ORA2 + 0.11 KET + 0.54 MGLY + 0.08 XO2 + 0.35 ALD + 0.5 MO2 + 0.38 HO2 +... etc.', & ! index 206
     'OLNN + ACO3 --> 0.5 ORA2 + ONIT + 0.5 MO2 + 0.5 HO2                                                 ', & ! index 207
     'OLND + ACO3 --> 0.484 ORA2 + 0.167 KET + 0.207 HCHO + 0.484 ONIT + 0.65 ALD + 0.516 MO2 + 0.516 NO2 ', & ! index 208
     '     2 OLNN --> 2 ONIT + HO2                                                                        ', & ! index 209
     'OLND + OLNN --> 0.149 KET + 0.202 HCHO + 1.5 ONIT + 0.64 ALD + 0.5 HO2 + 0.5 NO2                    ' /) ! index up to 210
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_7 = (/ &
     '     2 OLND --> 0.285 KET + 0.504 HCHO + ONIT + 1.21 ALD + NO2                                      ', & ! index 211
     '  MO2 + NO3 --> HCHO + HO2 + NO2                                                                    ', & ! index 212
     ' ETHP + NO3 --> ALD + HO2 + NO2                                                                     ', & ! index 213
     ' HC3P + NO3 --> 0.063 GLY + 0.67 KET + 0.048 HCHO + 0.051 XO2 + 0.243 ALD + 0.053 ETHP + 0.1... etc.', & ! index 214
     ' HC5P + NO3 --> 0.828 KET + 0.021 HCHO + 0.391 XO2 + 0.239 ALD + 0.262 ETHP + 0.04 MO2 + 0.6... etc.', & ! index 215
     ' HC8P + NO3 --> 0.88 KET + 0.587 XO2 + 0.187 ALD + 0.155 ETHP + 0.845 HO2 + NO2                     ', & ! index 216
     ' ETEP + NO3 --> 1.6 HCHO + 0.2 ALD + HO2 + NO2                                                      ', & ! index 217
     ' OLTP + NO3 --> 0.06 KET + HCHO + 0.94 ALD + HO2 + NO2                                              ', & ! index 218
     ' OLIP + NO3 --> 0.29 KET + 1.71 ALD + HO2 + NO2                                                     ', & ! index 219
     '  MPAN + HO --> HACE + NO2                                                                          ', & ! index 220
     ' APIP + NO3 --> KET + ALD + HO2 + NO2                                                               ', & ! index 221
     ' LIMP + NO3 --> 0.6 MACR + 0.4 HCHO + 0.4 OLI + HO2 + NO2                                           ', & ! index 222
     ' TOLP + NO3 --> 1.3 GLY + 0.7 MGLY + 0.5 DCB + HO2 + NO2                                            ', & ! index 223
     ' XYLP + NO3 --> 0.74 GLY + 1.26 MGLY + DCB + HO2 + NO2                                              ', & ! index 224
     ' CSLP + NO3 --> GLY + MGLY + HO2 + NO2                                                              ', & ! index 225
     ' ACO3 + NO3 --> MO2 + NO2                                                                           ', & ! index 226
     ' TCO3 + NO3 --> HCHO + ACO3 + NO2                                                                   ', & ! index 227
     ' NO3 + KETP --> 0.54 MGLY + 0.16 XO2 + 0.46 ALD + 0.77 HO2 + 0.23 ACO3 + NO2                        ', & ! index 228
     ' OLNN + NO3 --> ONIT + HO2 + NO2                                                                    ', & ! index 229
     ' OLND + NO3 --> 0.469 KET + 0.28 HCHO + 1.24 ALD + 2 NO2                                            ', & ! index 230
     '  XO2 + HO2 --> OP2                                                                                 ', & ! index 231
     '  XO2 + MO2 --> HCHO + HO2                                                                          ', & ! index 232
     ' XO2 + ACO3 --> MO2                                                                                 ', & ! index 233
     '      2 XO2 --> M                                                                                   ', & ! index 234
     '   XO2 + NO --> NO2                                                                                 ', & ! index 235
     '  XO2 + NO3 --> NO2                                                                                 ', & ! index 236
     '     2 ISOP --> 2 MACR + HCHO + HO2                                                                 ', & ! index 237
     '  ISHP + HO --> MACR + HO                                                                           ', & ! index 238
     '  ISON + HO --> NALD + HACE                                                                         ', & ! index 239
     '  MACP + NO --> 0.25 HACE + 0.25 CO + 0.5 MGLY + 0.75 HCHO + 0.75 HO2 + 0.25 ACO3 + NO2             ' /) ! index up to 240
  CHARACTER(LEN=100), PARAMETER, DIMENSION(10) :: EQN_NAMES_8 = (/ &
     ' MACP + HO2 --> MAHP                                                                                ', & ! index 241
     '     2 MACP --> HACE + 0.5 CO + MGLY + 0.5 HCHO + HO2                                               ', & ! index 242
     ' MACP + NO2 --> MPAN                                                                                ', & ! index 243
     '       MPAN --> MACP + NO2                                                                          ', & ! index 244
     '  SESQ + HO --> 0.05 ORA1 + 0.36 KET + 0.3 HCHO + 0.19 OLIP                                         ', & ! index 245
     '  SESQ + O3 --> 0.039 ORA1 + 0.053 ORA2 + 0.23 KET + 0.51 HCHO + 0.85 ALD + 0.63 HO                 ', & ! index 246
     ' SESQ + NO3 --> 0.9 MACR + 0.1 OLND + 0.9 OLNN                                                      ', & ! index 247
     '   MBO + HO --> OLIP                                                                                ', & ! index 248
     '  MBO + NO3 --> 0.89 OLND + 0.11 OLNN                                                               ', & ! index 249
     '   MBO + O3 --> 0.14 ORA2 + 0.06 ETH + 0.07 CH4 + 0.011 H2O2 + 0.3 CO + 0.16 KET + 0.02 HCHO... etc.' /) ! index up to 250
  CHARACTER(LEN=100), PARAMETER, DIMENSION(250) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6, EQN_NAMES_7, EQN_NAMES_8 /)

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE RACM_Monitor
