! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Stoichiometric Chemical Model File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : Hg_Stoichiom.F90
! Equation file        : Hg.kpp
! Output root filename : Hg
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE Hg_Stoichiom

  USE Hg_Parameters
  USE Hg_StoichiomSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! ReactantProd - Reactant Products in each equation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      ARP       - Reactant product in each equation
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE ReactantProd ( V, F, ARP )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! ARP - Reactant product in each equation
  REAL(kind=dp) :: ARP(NREACT)


! Reactant Products in each equation are useful in the
!     stoichiometric formulation of mass action law
  ARP(1) = V(30)*F(1)
  ARP(2) = V(32)
  ARP(3) = V(32)*F(1)
  ARP(4) = V(32)*F(4)
  ARP(5) = V(32)*F(4)
  ARP(6) = V(32)*F(7)
  ARP(7) = V(32)*F(9)
  ARP(8) = V(32)*F(8)
  ARP(9) = V(32)*F(3)
  ARP(10) = V(32)*F(1)
  ARP(11) = V(22)*F(11)
  ARP(12) = V(22)*F(10)
  ARP(13) = V(32)*F(6)
  ARP(14) = V(30)*F(2)
  ARP(15) = V(27)*F(2)
  ARP(16) = V(27)*F(4)
  ARP(17) = V(27)*F(4)
  ARP(18) = V(27)*F(7)
  ARP(19) = V(27)*F(9)
  ARP(20) = V(27)*F(8)
  ARP(21) = V(27)*F(1)
  ARP(22) = V(27)*F(3)
  ARP(23) = V(27)*F(6)
  ARP(24) = V(24)*F(11)
  ARP(25) = V(24)*F(10)
  ARP(26) = V(30)*F(3)
  ARP(27) = V(29)
  ARP(28) = V(29)*F(4)
  ARP(29) = V(29)*F(7)
  ARP(30) = V(29)*F(9)
  ARP(31) = V(29)*F(8)
  ARP(32) = V(29)*F(1)
  ARP(33) = V(29)*F(3)
  ARP(34) = V(29)*F(6)
  ARP(35) = V(19)*F(11)
  ARP(36) = V(19)*F(10)
  ARP(37) = V(16)
  ARP(38) = V(23)
  ARP(39) = V(31)
  ARP(40) = V(14)
  ARP(41) = V(13)
  ARP(42) = V(18)
  ARP(43) = V(17)
  ARP(44) = V(25)
  ARP(45) = V(26)
  ARP(46) = V(9)
  ARP(47) = V(8)
  ARP(48) = V(10)
  ARP(49) = V(1)
  ARP(50) = V(15)
  ARP(51) = V(21)
  ARP(52) = V(20)
  ARP(53) = V(12)
  ARP(54) = V(11)
  ARP(55) = V(16)
  ARP(56) = V(23)
  ARP(57) = V(31)
  ARP(58) = V(14)
  ARP(59) = V(13)
  ARP(60) = V(18)
  ARP(61) = V(17)
  ARP(62) = V(25)
  ARP(63) = V(26)
  ARP(64) = V(9)
  ARP(65) = V(8)
  ARP(66) = V(10)
  ARP(67) = V(15)
  ARP(68) = V(21)
  ARP(69) = V(20)
  ARP(70) = V(12)
  ARP(71) = V(11)
  ARP(72) = F(4)
  ARP(73) = F(8)
  ARP(74) = F(9)
  ARP(75) = V(32)
  ARP(76) = V(16)
  ARP(77) = V(23)
  ARP(78) = V(31)
  ARP(79) = V(18)
  ARP(80) = V(14)
  ARP(81) = V(13)
  ARP(82) = V(17)
  ARP(83) = V(25)
  ARP(84) = V(26)
  ARP(85) = V(10)
  ARP(86) = V(9)
  ARP(87) = V(8)
  ARP(88) = V(29)
  ARP(89) = V(15)
  ARP(90) = V(21)
  ARP(91) = V(20)
  ARP(92) = V(12)
  ARP(93) = V(11)
  ARP(94) = V(28)
      
END SUBROUTINE ReactantProd

! End of ReactantProd function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacReactantProd - Jacobian of Reactant Products vector
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacReactantProd ( V, F, JVRP )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! JVRP - d ARP(1:NREACT)/d VAR (1:NVAR)
  REAL(kind=dp) :: JVRP(NJVRP)


! Reactant Products in each equation are useful in the
!    stoichiometric formulation of mass action law
! Below we compute the Jacobian of the Reactant Products vector
!    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)

! JVRP(1) = dARP(1)/dV(30)
  JVRP(1) = F(1)
! JVRP(2) = dARP(2)/dV(32)
  JVRP(2) = 1
! JVRP(3) = dARP(3)/dV(32)
  JVRP(3) = F(1)
! JVRP(4) = dARP(4)/dV(32)
  JVRP(4) = F(4)
! JVRP(5) = dARP(5)/dV(32)
  JVRP(5) = F(4)
! JVRP(6) = dARP(6)/dV(32)
  JVRP(6) = F(7)
! JVRP(7) = dARP(7)/dV(32)
  JVRP(7) = F(9)
! JVRP(8) = dARP(8)/dV(32)
  JVRP(8) = F(8)
! JVRP(9) = dARP(9)/dV(32)
  JVRP(9) = F(3)
! JVRP(10) = dARP(10)/dV(32)
  JVRP(10) = F(1)
! JVRP(11) = dARP(11)/dV(22)
  JVRP(11) = F(11)
! JVRP(12) = dARP(12)/dV(22)
  JVRP(12) = F(10)
! JVRP(13) = dARP(13)/dV(32)
  JVRP(13) = F(6)
! JVRP(14) = dARP(14)/dV(30)
  JVRP(14) = F(2)
! JVRP(15) = dARP(15)/dV(27)
  JVRP(15) = F(2)
! JVRP(16) = dARP(16)/dV(27)
  JVRP(16) = F(4)
! JVRP(17) = dARP(17)/dV(27)
  JVRP(17) = F(4)
! JVRP(18) = dARP(18)/dV(27)
  JVRP(18) = F(7)
! JVRP(19) = dARP(19)/dV(27)
  JVRP(19) = F(9)
! JVRP(20) = dARP(20)/dV(27)
  JVRP(20) = F(8)
! JVRP(21) = dARP(21)/dV(27)
  JVRP(21) = F(1)
! JVRP(22) = dARP(22)/dV(27)
  JVRP(22) = F(3)
! JVRP(23) = dARP(23)/dV(27)
  JVRP(23) = F(6)
! JVRP(24) = dARP(24)/dV(24)
  JVRP(24) = F(11)
! JVRP(25) = dARP(25)/dV(24)
  JVRP(25) = F(10)
! JVRP(26) = dARP(26)/dV(30)
  JVRP(26) = F(3)
! JVRP(27) = dARP(27)/dV(29)
  JVRP(27) = 1
! JVRP(28) = dARP(28)/dV(29)
  JVRP(28) = F(4)
! JVRP(29) = dARP(29)/dV(29)
  JVRP(29) = F(7)
! JVRP(30) = dARP(30)/dV(29)
  JVRP(30) = F(9)
! JVRP(31) = dARP(31)/dV(29)
  JVRP(31) = F(8)
! JVRP(32) = dARP(32)/dV(29)
  JVRP(32) = F(1)
! JVRP(33) = dARP(33)/dV(29)
  JVRP(33) = F(3)
! JVRP(34) = dARP(34)/dV(29)
  JVRP(34) = F(6)
! JVRP(35) = dARP(35)/dV(19)
  JVRP(35) = F(11)
! JVRP(36) = dARP(36)/dV(19)
  JVRP(36) = F(10)
! JVRP(37) = dARP(37)/dV(16)
  JVRP(37) = 1
! JVRP(38) = dARP(38)/dV(23)
  JVRP(38) = 1
! JVRP(39) = dARP(39)/dV(31)
  JVRP(39) = 1
! JVRP(40) = dARP(40)/dV(14)
  JVRP(40) = 1
! JVRP(41) = dARP(41)/dV(13)
  JVRP(41) = 1
! JVRP(42) = dARP(42)/dV(18)
  JVRP(42) = 1
! JVRP(43) = dARP(43)/dV(17)
  JVRP(43) = 1
! JVRP(44) = dARP(44)/dV(25)
  JVRP(44) = 1
! JVRP(45) = dARP(45)/dV(26)
  JVRP(45) = 1
! JVRP(46) = dARP(46)/dV(9)
  JVRP(46) = 1
! JVRP(47) = dARP(47)/dV(8)
  JVRP(47) = 1
! JVRP(48) = dARP(48)/dV(10)
  JVRP(48) = 1
! JVRP(49) = dARP(49)/dV(1)
  JVRP(49) = 1
! JVRP(50) = dARP(50)/dV(15)
  JVRP(50) = 1
! JVRP(51) = dARP(51)/dV(21)
  JVRP(51) = 1
! JVRP(52) = dARP(52)/dV(20)
  JVRP(52) = 1
! JVRP(53) = dARP(53)/dV(12)
  JVRP(53) = 1
! JVRP(54) = dARP(54)/dV(11)
  JVRP(54) = 1
! JVRP(55) = dARP(55)/dV(16)
  JVRP(55) = 1
! JVRP(56) = dARP(56)/dV(23)
  JVRP(56) = 1
! JVRP(57) = dARP(57)/dV(31)
  JVRP(57) = 1
! JVRP(58) = dARP(58)/dV(14)
  JVRP(58) = 1
! JVRP(59) = dARP(59)/dV(13)
  JVRP(59) = 1
! JVRP(60) = dARP(60)/dV(18)
  JVRP(60) = 1
! JVRP(61) = dARP(61)/dV(17)
  JVRP(61) = 1
! JVRP(62) = dARP(62)/dV(25)
  JVRP(62) = 1
! JVRP(63) = dARP(63)/dV(26)
  JVRP(63) = 1
! JVRP(64) = dARP(64)/dV(9)
  JVRP(64) = 1
! JVRP(65) = dARP(65)/dV(8)
  JVRP(65) = 1
! JVRP(66) = dARP(66)/dV(10)
  JVRP(66) = 1
! JVRP(67) = dARP(67)/dV(15)
  JVRP(67) = 1
! JVRP(68) = dARP(68)/dV(21)
  JVRP(68) = 1
! JVRP(69) = dARP(69)/dV(20)
  JVRP(69) = 1
! JVRP(70) = dARP(70)/dV(12)
  JVRP(70) = 1
! JVRP(71) = dARP(71)/dV(11)
  JVRP(71) = 1
! JVRP(72) = dARP(75)/dV(32)
  JVRP(72) = 1
! JVRP(73) = dARP(76)/dV(16)
  JVRP(73) = 1
! JVRP(74) = dARP(77)/dV(23)
  JVRP(74) = 1
! JVRP(75) = dARP(78)/dV(31)
  JVRP(75) = 1
! JVRP(76) = dARP(79)/dV(18)
  JVRP(76) = 1
! JVRP(77) = dARP(80)/dV(14)
  JVRP(77) = 1
! JVRP(78) = dARP(81)/dV(13)
  JVRP(78) = 1
! JVRP(79) = dARP(82)/dV(17)
  JVRP(79) = 1
! JVRP(80) = dARP(83)/dV(25)
  JVRP(80) = 1
! JVRP(81) = dARP(84)/dV(26)
  JVRP(81) = 1
! JVRP(82) = dARP(85)/dV(10)
  JVRP(82) = 1
! JVRP(83) = dARP(86)/dV(9)
  JVRP(83) = 1
! JVRP(84) = dARP(87)/dV(8)
  JVRP(84) = 1
! JVRP(85) = dARP(88)/dV(29)
  JVRP(85) = 1
! JVRP(86) = dARP(89)/dV(15)
  JVRP(86) = 1
! JVRP(87) = dARP(90)/dV(21)
  JVRP(87) = 1
! JVRP(88) = dARP(91)/dV(20)
  JVRP(88) = 1
! JVRP(89) = dARP(92)/dV(12)
  JVRP(89) = 1
! JVRP(90) = dARP(93)/dV(11)
  JVRP(90) = 1
! JVRP(91) = dARP(94)/dV(28)
  JVRP(91) = 1
      
END SUBROUTINE JacReactantProd

! End of JacReactantProd function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! Begin Derivative w.r.t. Rate Coefficients

! ------------------------------------------------------------------------------
! Subroutine for the derivative of Fun with respect to rate coefficients
! -----------------------------------------------------------------------------

      SUBROUTINE  dFun_dRcoeff( V, F, NCOEFF, JCOEFF, DFDR )
       
      USE Hg_Parameters
      USE Hg_StoichiomSP
      IMPLICIT NONE 

! V - Concentrations of variable/radical/fixed species            
      REAL(kind=dp) V(NVAR), F(NFIX)
! NCOEFF - the number of rate coefficients with respect to which we differentiate
      INTEGER NCOEFF       
! JCOEFF - a vector of integers containing the indices of reactions (rate
!          coefficients) with respect to which we differentiate
      INTEGER JCOEFF(NCOEFF)       
! DFDR  - a matrix containg derivative values; specifically, 
!         column j contains d Fun(1:NVAR) / d RCT( JCOEFF(j) )
!         for each 1 <= j <= NCOEFF
!         This matrix is stored in a column-wise linearized format
      REAL(kind=dp) DFDR(NVAR*NCOEFF)

! Local vector with reactant products
      REAL(kind=dp) A_RPROD(NREACT)
      REAL(kind=dp) aj
      INTEGER i,j,k
      
! Compute the reactant products of all reactions     
      CALL ReactantProd ( V, F, A_RPROD )

! Compute the derivatives by multiplying column JCOEFF(j) of the stoichiometric matrix with A_RPROD       
      DO j=1,NCOEFF
!                  Initialize the j-th column of derivative matrix to zero       
         DO i=1,NVAR
           DFDR(i+NVAR*(j-1)) = 0.0_dp 
         END DO
!                  Column JCOEFF(j) in the stoichiometric matrix times the
!                  reactant product  of the JCOEFF(j)-th reaction      
!                  give the j-th column of the derivative matrix   
         aj = A_RPROD(JCOEFF(j))
         DO k=CCOL_STOICM(JCOEFF(j)),CCOL_STOICM(JCOEFF(j)+1)-1
           DFDR(IROW_STOICM(k)+NVAR*(j-1)) = STOICM(k)*aj
         END DO
      END DO
      
      END SUBROUTINE  dFun_dRcoeff

! End Derivative w.r.t. Rate Coefficients


! Begin Jacobian Derivative w.r.t. Rate Coefficients

! ------------------------------------------------------------------------------
! Subroutine for the derivative of Jac with respect to rate coefficients
! Times a user vector
! -----------------------------------------------------------------------------

      SUBROUTINE  dJac_dRcoeff( V, F, U, NCOEFF, JCOEFF, DJDR )
       
      USE Hg_Parameters
      USE Hg_StoichiomSP
      IMPLICIT NONE 

! V - Concentrations of variable/fixed species            
      REAL(kind=dp) V(NVAR), F(NFIX)
! U - User-supplied Vector           
      REAL(kind=dp) U(NVAR)
! NCOEFF - the number of rate coefficients with respect to which we differentiate
      INTEGER NCOEFF       
! JCOEFF - a vector of integers containing the indices of reactions (rate
!          coefficients) with respect to which we differentiate
      INTEGER JCOEFF(NCOEFF)       
! DFDR  - a matrix containg derivative values; specifically, 
!         column j contains d Jac(1:NVAR) / d RCT( JCOEFF(j) ) * U
!                     for each 1 <= j <= NCOEFF
!         This matrix is stored in a column-wise linearized format
      REAL(kind=dp) DJDR(NVAR*NCOEFF)

! Local vector for Jacobian of reactant products
      REAL(kind=dp) JV_RPROD(NJVRP)
      REAL(kind=dp) aj
      INTEGER i,j,k
      
! Compute the Jacobian of all reactant products   
      CALL JacReactantProd( V, F, JV_RPROD )

! Compute the derivatives by multiplying column JCOEFF(j) of the stoichiometric matrix with A_PROD       
      DO j=1,NCOEFF
!                  Initialize the j-th column of derivative matrix to zero       
         DO i=1,NVAR
           DJDR(i+NVAR*(j-1)) = 0.0_dp
         END DO
!                  Column JCOEFF(j) in the stoichiometric matrix times the
!                  ( Gradient of reactant product of the JCOEFF(j)-th reaction X user vector )    
!                  give the j-th column of the derivative matrix   
!
!          Row JCOEFF(j) of JV_RPROD times the user vector
         aj = 0.0_dp
         DO k=CROW_JVRP(JCOEFF(j)),CROW_JVRP(JCOEFF(j)+1)-1
             aj = aj + JV_RPROD(k)*U(ICOL_JVRP(k))
         END DO
!          Column JCOEFF(j) of Stoichiom. matrix times aj         
         DO k=CCOL_STOICM(JCOEFF(j)),CCOL_STOICM(JCOEFF(j)+1)-1
           DJDR(IROW_STOICM(k)+NVAR*(j-1)) = STOICM(k)*aj
         END DO
      END DO
      
      END SUBROUTINE  dJac_dRcoeff

! End Jacobian Derivative w.r.t. Rate Coefficients


END MODULE Hg_Stoichiom

