! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
! 
! File                 : pollu_JacobianSP.f90
! Equation file        : pollu.kpp
! Output root filename : pollu
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE pollu_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(95) :: LU_IROW = (/ &
       1,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4, & ! index 1 - 12
       4,  5,  5,  6,  6,  7,  7,  7,  7,  7,  8,  8, & ! index 13 - 24
       9,  9,  9, 10, 10, 10, 11, 11, 11, 12, 12, 12, & ! index 25 - 36
      12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, & ! index 37 - 48
      15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, & ! index 49 - 60
      16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, & ! index 61 - 72
      18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, & ! index 73 - 84
      19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20 /) ! index up to 95

  INTEGER, PARAMETER, DIMENSION(95) :: LU_ICOL = (/ &
       1,  8, 13, 20,  2, 17, 20,  3,  6, 20,  4, 15, & ! index 1 - 12
      18,  5, 14,  6, 20,  5,  7, 12, 14, 17,  8, 20, & ! index 13 - 24
       9, 15, 17, 10, 18, 19, 11, 12, 17, 11, 12, 14, & ! index 25 - 36
      17, 10, 13, 18, 19, 20,  7, 12, 14, 17, 18,  8, & ! index 37 - 48
       9, 15, 17, 18, 20,  6,  8, 10, 13, 16, 18, 19, & ! index 49 - 60
      20,  9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 12, & ! index 61 - 72
      14, 15, 16, 17, 18, 19, 20,  8, 15, 17, 18, 19, & ! index 73 - 84
      20,  5,  6,  8, 13, 14, 16, 17, 18, 19, 20 /) ! index up to 95

  INTEGER, PARAMETER, DIMENSION(21) :: LU_CROW = (/ &
       1,  5,  8, 11, 14, 16, 18, 23, 25, 28, 31, 34, & ! index 1 - 12
      38, 43, 48, 54, 62, 72, 80, 86, 96 /) ! index up to 21

  INTEGER, PARAMETER, DIMENSION(21) :: LU_DIAG = (/ &
       1,  5,  8, 11, 14, 16, 19, 23, 25, 28, 31, 35, & ! index 1 - 12
      39, 45, 50, 58, 68, 77, 84, 95, 96 /) ! index up to 21


END MODULE pollu_JacobianSP

