! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : jam_Initialize.f90
! Equation file        : jam.kpp
! Output root filename : jam
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE jam_Initialize

  USE jam_Parameters, ONLY: dp, NVAR, NFIX
  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialize - function to initialize concentrations
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Initialize ( )


  USE jam_Global

  USE jam_Parameters

  INTEGER :: i
  REAL(kind=dp) :: x

! ~~~ Define scale factor for units
  CFACTOR = 1.000000e+00_dp

! ~~~ Zero C array
  C = 0.0_dp

! ~~~ Set initial species concentrations

! Begin constant rate coefficients
  RCONST(9) = 7.2e-11
  RCONST(10) = 1.6e-12
  RCONST(11) = 6.9e-12
  RCONST(15) = 1.8e-12
  RCONST(23) = 1.8e-12
  RCONST(24) = 5e-11
  RCONST(36) = 1e-11
  RCONST(37) = 2.2e-11
  RCONST(38) = 3.5e-12
  RCONST(62) = 4e-13
  RCONST(76) = 1e-12
  RCONST(79) = 2e-13
  RCONST(81) = 7.6e-14
  RCONST(90) = 4e-14
  RCONST(94) = 1e-11
  RCONST(95) = 1e-14
  RCONST(98) = 2.5e-12
  RCONST(99) = 1e-11
  RCONST(103) = 1e-11
  RCONST(104) = 1e-11
  RCONST(106) = 4e-12
  RCONST(107) = 2.73e-12
  RCONST(108) = 6.19e-12
  RCONST(109) = 1e-11
  RCONST(110) = 1e-11
  RCONST(113) = 4e-12
  RCONST(114) = 1.23e-11
  RCONST(115) = 1.58e-11
  RCONST(125) = 1e-11
  RCONST(128) = 2.5e-12
  RCONST(130) = 8.3e-13
  RCONST(131) = 1e-11
  RCONST(133) = 3e-12
  RCONST(139) = 1e-11
  RCONST(142) = 2.5e-12
  RCONST(144) = 1e-12
  RCONST(145) = 1e-11
  RCONST(146) = 7e-12
  RCONST(147) = 1.3e-13
  RCONST(148) = 5.4e-11
  RCONST(153) = 1e-12
  RCONST(154) = 1e-11
  RCONST(158) = 1e-12
  RCONST(159) = 1e-11
  RCONST(163) = 1e-11
  RCONST(164) = 1e-11
  RCONST(167) = 4e-12
  RCONST(169) = 9.2e-14
  RCONST(170) = 1e-11
  RCONST(173) = 2.5e-12
  RCONST(176) = 1.8e-11
  RCONST(177) = 1.8e-11
  RCONST(179) = 3.2e-11
  RCONST(180) = 1.51e-11
  RCONST(181) = 1.87e-11
  RCONST(184) = 1e-12
  RCONST(185) = 1e-11
  RCONST(189) = 2.5e-12
  RCONST(190) = 5.6e-12
  RCONST(191) = 5e-11
  RCONST(192) = 4.5e-12
  RCONST(193) = 2.45e-11
  RCONST(195) = 1e-11
  RCONST(196) = 1e-11
  RCONST(199) = 4e-12
  RCONST(200) = 1e-12
  RCONST(204) = 1e-12
  RCONST(205) = 1e-11
  RCONST(209) = 1e-12
  RCONST(210) = 1e-11
  RCONST(211) = 3.5e-12
  RCONST(216) = 1e-17
  RCONST(221) = 1e-12
  RCONST(222) = 1e-11
  RCONST(224) = 5e-12
  RCONST(225) = 2e-12
  RCONST(229) = 2.5e-12
  RCONST(230) = 2.4e-12
  RCONST(231) = 1e-11
  RCONST(235) = 1.54e-10
  RCONST(236) = 9.3e-11
  RCONST(237) = 6e-11
  RCONST(238) = 1.5e-11
  RCONST(239) = 1.76e-11
  RCONST(243) = 4e-12
  RCONST(244) = 1.04e-11
  RCONST(247) = 2.3e-12
  RCONST(251) = 2.5e-12
  RCONST(252) = 8e-13
  RCONST(253) = 1e-11
  RCONST(254) = 7.5e-11
  RCONST(255) = 3.85e-11
  RCONST(256) = 1.36e-11
  RCONST(260) = 2.5e-12
  RCONST(261) = 2.9e-12
  RCONST(262) = 1e-11
  RCONST(263) = 1.18e-10
  RCONST(264) = 7.38e-11
  RCONST(265) = 6.1e-11
  RCONST(268) = 2.5e-12
  RCONST(269) = 1.3e-12
  RCONST(270) = 1e-11
  RCONST(271) = 1.03e-10
  RCONST(272) = 4.16e-11
  RCONST(273) = 2.4e-17
  RCONST(278) = 1e-12
  RCONST(279) = 1e-11
  RCONST(280) = 2.65e-11
  RCONST(281) = 4.52e-11
  RCONST(282) = 2.4e-17
  RCONST(285) = 2.5e-12
  RCONST(287) = 1e-12
  RCONST(288) = 1e-11
  RCONST(289) = 3.16e-11
  RCONST(291) = 1e-11
  RCONST(292) = 1e-11
  RCONST(295) = 4e-12
  RCONST(297) = 2.52e-11
  RCONST(298) = 2.88e-11
  RCONST(300) = 2.52e-11
  RCONST(301) = 3.81e-11
  RCONST(302) = 1e-12
  RCONST(303) = 1e-11
  RCONST(305) = 2.5e-12
  RCONST(307) = 9.7e-12
  RCONST(310) = 1e-11
  RCONST(313) = 1.4e-11
  RCONST(316) = 1e-12
  RCONST(317) = 1e-11
  RCONST(318) = 1e-12
  RCONST(321) = 2.4e-12
  RCONST(322) = 1e-12
  RCONST(323) = 1e-11
  RCONST(327) = 1e-12
  RCONST(328) = 1e-11
  RCONST(329) = 5.2e-11
  RCONST(330) = 4.72e-11
  RCONST(334) = 2.5e-12
  RCONST(335) = 8e-13
  RCONST(336) = 1e-11
  RCONST(340) = 2.5e-12
  RCONST(341) = 8e-13
  RCONST(342) = 1e-11
  RCONST(344) = 2.104e-11
  RCONST(346) = 1.515e-11
  RCONST(347) = 8.916e-12
  RCONST(350) = 3.8e-12
  RCONST(353) = 1e-12
  RCONST(354) = 1e-11
  RCONST(356) = 2.1e-12
  RCONST(357) = 2.8e-13
  RCONST(359) = 2.3e-12
  RCONST(361) = 1e-12
  RCONST(362) = 1e-11
  RCONST(366) = 1e-12
  RCONST(367) = 1e-11
  RCONST(369) = 1e-10
  RCONST(370) = 9.9e-11
  RCONST(371) = 2.1e-12
  RCONST(372) = 2.8e-13
  RCONST(375) = 2.3e-12
  RCONST(376) = 1e-12
  RCONST(377) = 1e-11
  RCONST(380) = 4.7e-11
  RCONST(381) = 1.4e-11
  RCONST(384) = 1e-12
  RCONST(385) = 1e-11
  RCONST(389) = 1e-12
  RCONST(390) = 1e-11
  RCONST(397) = 1e-12
  RCONST(398) = 1e-11
  RCONST(399) = 1.7e-11
  RCONST(400) = 8.4e-11
  RCONST(401) = 3.2e-11
  RCONST(404) = 1e-12
  RCONST(405) = 1e-11
  RCONST(409) = 1e-12
  RCONST(410) = 1e-11
  RCONST(415) = 2.1e-10
  RCONST(416) = 2e-10
  RCONST(420) = 4.7e-16
  RCONST(421) = 1.2e-14
  RCONST(423) = 2.5e-12
  RCONST(424) = 1.1e-11
  RCONST(425) = 1.2e-11
  RCONST(426) = 1.9e-11
  RCONST(430) = 1e-11
  RCONST(431) = 3.3e-11
  RCONST(432) = 5.7e-11
  RCONST(433) = 1e-12
  RCONST(434) = 3.5e-12
  RCONST(438) = 1e-11
  RCONST(439) = 2.3e-11
  RCONST(440) = 3.4e-11
  RCONST(444) = 1e-11
  RCONST(445) = 2.4e-12
  RCONST(446) = 3.5e-12
  RCONST(447) = 1e-11
  RCONST(450) = 1.2e-10
  RCONST(451) = 2.02e-10
  RCONST(452) = 1.204e-10
  RCONST(453) = 1.5e-10
  RCONST(454) = 9.75e-11
  RCONST(455) = 1.5e-11
  RCONST(456) = 7.2e-11
  RCONST(457) = 1.794e-10
  RCONST(458) = 1.628e-10
  RCONST(459) = 2.84e-10
  RCONST(460) = 1.674e-10
  RCONST(461) = 9.6e-11
  RCONST(462) = 4.1e-11
  RCONST(463) = 1.012e-10
  RCONST(464) = 1.2e-10
  RCONST(465) = 4.49e-10
  RCONST(466) = 2.57e-10
  RCONST(467) = 2.14e-11
  RCONST(468) = 1.9e-10
  RCONST(469) = 1.31e-10
  RCONST(470) = 3.5e-11
  RCONST(471) = 9e-12
  RCONST(472) = 1.2e-10
  RCONST(473) = 1.5e-10
  RCONST(474) = 1.2e-10
  RCONST(494) = 1.7e-13
  RCONST(518) = 5.805e-11
  RCONST(520) = 1.4e-11
  RCONST(530) = 1.6e-10
  RCONST(532) = 5.9e-11
  RCONST(533) = 8e-11
  RCONST(534) = 7.6e-11
  RCONST(535) = 3.441e-11
  RCONST(536) = 1.4e-10
  RCONST(538) = 5.4e-11
  RCONST(539) = 1.935e-10
  RCONST(549) = 3.3e-10
  RCONST(551) = 4.4e-13
  RCONST(552) = 1e-10
  RCONST(554) = 3e-13
  RCONST(555) = 5e-11
! End constant rate coefficients

! Begin inlined code from F90_INIT

  ! start of code from messy_mecca_kpp.kpp
  rtol(:) = 1E-2_dp ! relative tolerance
  atol(:) = 1E1_dp  ! absolute tolerance
  IF ((ind_OH  >0).AND.(ind_OH  <=NVAR)) atol(ind_OH)  = 1._dp
  IF ((ind_NO3 >0).AND.(ind_NO3 <=NVAR)) atol(ind_NO3) = 1._dp
  IF ((ind_Cl  >0).AND.(ind_Cl  <=NVAR)) atol(ind_Cl)  = 1._dp
  IF ((ind_Br  >0).AND.(ind_Br  <=NVAR)) atol(ind_Br)  = 1._dp
  IF ((ind_O1D >0).AND.(ind_O1D <=NVAR)) atol(ind_O1D) = 1._dp
  ! end of code from messy_mecca_kpp.kpp

! End inlined code from F90_INIT

      
END SUBROUTINE Initialize

! End of Initialize function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE jam_Initialize

