! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
! 
! File                 : jam_Rates.f90
! Equation file        : jam.kpp
! Output root filename : jam
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE jam_Rates

  USE jam_Parameters
  USE jam_Global
  IMPLICIT NONE
  INTEGER, PARAMETER :: ASSOC = 1, DISSOC = 2

  PRIVATE :: ARR_abc_dp, ARR_abc_sp
  INTERFACE ARR_abc
     MODULE PROCEDURE ARR_abc_dp
     MODULE PROCEDURE ARR_abc_sp
  END INTERFACE ARR_abc

  PRIVATE :: ARR_ab_dp, ARR_ab_sp
  INTERFACE ARR_ab
     MODULE PROCEDURE ARR_ab_dp
     MODULE PROCEDURE ARR_ab_sp
  END INTERFACE ARR_ab

  PRIVATE :: ARR_ac_dp, ARR_ac_sp
  INTERFACE ARR_ac
     MODULE PROCEDURE ARR_ac_dp
     MODULE PROCEDURE ARR_ac_sp
  END INTERFACE ARR_ac

  PRIVATE :: EP2_dp, EP2_sp
  INTERFACE EP2
     MODULE PROCEDURE EP2_dp
     MODULE PROCEDURE EP2_sp
  END INTERFACE EP2

  PRIVATE :: EP3_dp, EP3_sp
  INTERFACE EP3
     MODULE PROCEDURE EP3_dp
     MODULE PROCEDURE EP3_sp
  END INTERFACE EP3

  PRIVATE :: FALL_dp, FALL_sp
  INTERFACE FALL
     MODULE PROCEDURE FALL_dp
     MODULE PROCEDURE FALL_sp
  END INTERFACE FALL

  PRIVATE :: k3rd_jpl_dp, k3rd_jpl_sp
  INTERFACE k3rd_jpl
     MODULE PROCEDURE k3rd_jpl_dp
     MODULE PROCEDURE k3rd_jpl_sp
  END INTERFACE k3rd_jpl

  PRIVATE :: k3rd_jpl_activation_dp, k3rd_jpl_activation_sp
  INTERFACE  k3rd_jpl_activation
     MODULE PROCEDURE  k3rd_jpl_activation_dp
     MODULE PROCEDURE  k3rd_jpl_activation_sp
  END INTERFACE  k3rd_jpl_activation

  PRIVATE :: k3rd_iupac_dp, k3rd_iupac_sp
  INTERFACE k3rd_iupac
     MODULE PROCEDURE k3rd_iupac_dp
     MODULE PROCEDURE k3rd_iupac_sp
  END INTERFACE k3rd_iupac

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!
!  NOTE: For computational efficiency, we have created duplicate rate law
!  routines here that take either all single precision or all double precision
!  arguments.  Explicit casts to DBLE are skipped in the functions that take
!  all double precision arguments (as this removes unneeded computations).
!
!  These functions are overloaded by INTERFACE statements, which are located
!  in file UserRateLawsInterfaces.f90.  The UserRateLawsInterfaces.f90 file
!  will be in-lined into the top of the jam_Rates module.
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  FUNCTION ARR_abc_dp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_abc_dp

  FUNCTION ARR_abc_sp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_abc_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ab_dp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP)
  END FUNCTION ARR_ab_dp

  FUNCTION ARR_ab_sp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP)
  END FUNCTION ARR_ab_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ac_dp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = a0 * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_ac_dp

  FUNCTION ARR_ac_sp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_ac_sp

  !---------------------------------------------------------------------------

  FUNCTION EP2_dp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-c0/temp)
    k2 = a2 * EXP(-c2/temp)
    k3 = a3 * EXP(-c3/temp)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + k3/(1.0_dp + k3/k2)
  END FUNCTION EP2_dp

  FUNCTION EP2_sp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = DBLE(a0) * EXP(-DBLE(c0)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k3 = DBLE(a3) * EXP(-DBLE(c3)/TEMP)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + K3/(1.0_dp + k3/k2)
  END FUNCTION EP2_sp

  !---------------------------------------------------------------------------

  FUNCTION EP3_dp( a1, c1, a2, c2) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = a1 * EXP(-c1/TEMP)
    k2 = a2 * EXP(-c2/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_dp

  FUNCTION EP3_sp( a1, c1, a2, c2 ) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = DBLE(a1) * EXP(-DBLE(c1)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_sp

  !---------------------------------------------------------------------------

  FUNCTION FALL_dp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**c0
    k1 = a1 * EXP(-b1/TEMP) * (TEMP/300.0_dp)**c1
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * cf**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_dp

  FUNCTION FALL_sp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
    k1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * DBLE(cf)**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_sp

  !---------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) three-body reaction formula:
  
  REAL(dp) FUNCTION k3rd_jpl_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(dp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_dp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_dp

  REAL(kind=dp) FUNCTION k3rd_jpl_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(sp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_sp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_sp

  ! --------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) termolecular chemical activation reaction:

  FUNCTION k3rd_jpl_activation_dp(cair,k0_298K,n,kinf_298K,m,A,B) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), DIMENSION(2) :: k3rd_jpl_activation_dp
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: A         ! for k_int
    REAL(dp), INTENT(IN) :: B         ! for k_int
    REAL(dp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_dp(ASSOC)  = k_f
    k3rd_jpl_activation_dp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_dp

  FUNCTION k3rd_jpl_activation_sp(cair,k0_298K,n,kinf_298K,m,A,B) ! sp args
    INTRINSIC :: LOG10
    REAL(kind=dp), DIMENSION(2) :: k3rd_jpl_activation_sp
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: A         ! for k_int
    REAL(sp), INTENT(IN) :: B         ! for k_int
    REAL(sp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_sp(ASSOC)  = k_f
    k3rd_jpl_activation_sp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_sp

  ! --------------------------------------------------------------------------

  ! IUPAC (iupac.pole-ether.fr) three-body reaction formula:

  REAL(dp) FUNCTION k3rd_iupac_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(dp)             :: nu        ! N
    REAL(dp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_dp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_dp

  REAL(kind=dp) FUNCTION k3rd_iupac_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC :: LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(sp)             :: nu        ! N
    REAL(sp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_sp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_sp

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin inlined code from F90_RATES


! End inlined code from F90_RATES

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
    USE jam_Parameters
    USE jam_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


SUBROUTINE Update_RCONST ( YIN )

! Begin inlined code from F90_RCONST_USE


! End inlined code from F90_RCONST_USE

! YIN - Optional input concentrations of variable species
  REAL(kind=dp), OPTIONAL :: YIN(NVAR)

! Y - Concentrations of species (local)
  REAL(kind=dp) :: Y(NSPEC)

! Ensure local Y array is filled with variable and constant concentrations
  Y(1:NSPEC) = C(1:NSPEC)

! Update local Y array if variable concentrations are provided
  if (present(YIN)) Y(1:NVAR) = YIN(1:NVAR)



! Begin inlined code from F90_RCONST


  ! start of USE statements from messy_mecca_kpp.kpp
  USE messy_main_constants_mem  ! atm2Pa, N_A, R_gas
  USE messy_cmn_photol_mem      ! IP_MAX, ip_*, jname
  USE messy_main_tools_kinetics ! ELEMENTAL rate coefficient functions
  ! end of USE statements from messy_mecca_kpp.kpp

  ! start of executable statements
  ! define some rate constants here if the expressions are too long
  ! for kpp or if they are used more than once
  kHO2_HO2     = (3.0E-13*EXP(460./temp)+2.1E-33*EXP(920./temp)*cair)* &
                 (1.+1.4E-21*EXP(2200./temp)*C(ind_H2O))
  kNO2NO3      = k_3rd(TEMP,cair,2.000e-30,4.4,1.400e-12,0.7,0.6)
  kN2O5        = kNO2NO3 * 3.333e26 * EXP(-10991./TEMP)
  kHNO3_OH     = 2.4E-14*EXP(460./temp) + 1./ &
                 ( 1./(6.5E-34*EXP(1335./temp)*cair) + &
                 1./(2.7E-17*EXP(2199./temp)) )
  kNO2HO2      = k_3rd(TEMP,cair,2.000e-31,3.4,2.900e-12,1.1,0.6)
  kHNO4        = kNO2HO2 * EXP(-10900./TEMP) / 2.1e-27
  ! CO + OH start
  kCO_OH_inf   = 2.1e+09 * (TEMP/ 300.)**(6.1)
  kCO_OH_o     = 1.5e-13 * (TEMP/ 300.)**(0.6)
  kCO_OH_term1 = kCO_OH_o / ( (kCO_OH_inf / cair) )
  kCO_OH_term2 = kCO_OH_o / (1. + kCO_OH_term1)
  kCO_OH_term1 = LOG10( kCO_OH_term1 )
  kCO_OH_term1 = 1. / (1. + kCO_OH_term1*kCO_OH_term1)
  kCO_OH       = kCO_OH_term2 * (0.6)**kCO_OH_term1
  ! CO + OH end
  kNO2CH3O2    = k_3rd(TEMP,cair,1.000e-30,4.8,7.200e-12,2.1,0.6)
  kCH3O2NO2    = kNO2CH3O2 * EXP(-11234./TEMP) / 9.5e-29
  k_CH3CO3_NO2 = k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6)
  kPAN         = k_CH3CO3_NO2 * 1.111e28 * EXP(-14000./TEMP)
  k_MACO3_NO2  = k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.3)
  kMPAN        = k_MACO3_NO2 * 1.111e28 * EXP(-14000./TEMP)
  kClOClO      = k_3rd(TEMP,cair,1.600e-32,4.5,3.000e-12,2.,0.6)
  kCl2O2       = kClOClO / (1.3e-27 * EXP(8744./TEMP))

! End inlined code from F90_RCONST

! <G0O3P_O2>:
  RCONST(1) = (6.e-34*(300./TEMP)**2.4*cair)
! <G0O3P_O3>:
  RCONST(2) = (8.000e-12*EXP(-2060./TEMP))
! <G0O3P_O3P>:
  RCONST(3) = (4.23e-28*(TEMP)**(-2)*cair)
! <G0O1D_N2>:
  RCONST(4) = (2.150e-11*EXP(110./TEMP))
! <G0O1D_O2_ab>:
  RCONST(5) = (3.135e-11*EXP(55./TEMP)+1.650e-12*EXP(55./TEMP))
! <G0O1D_H2O>:
  RCONST(6) = (1.630e-10*EXP(60./TEMP))
! <G0H_O2>:
  RCONST(7) = (k_3rd(TEMP,cair,4.400e-32,1.3,7.500e-11,-0.2,0.6))
! <G0H_O3>:
  RCONST(8) = (1.400e-10*EXP(-470./TEMP))
! <G0H_HO2_a>:
! RCONST(9) = constant rate coefficient
! <G0H_HO2_b>:
! RCONST(10) = constant rate coefficient
! <G0H_HO2_c>:
! RCONST(11) = constant rate coefficient
! <G0H2_O3P>:
  RCONST(12) = (1.600e-11*EXP(-4570./TEMP))
! <G0H2_OH>:
  RCONST(13) = (2.800e-12*EXP(-1800./TEMP))
! <G0OH_O3P>:
  RCONST(14) = (1.800e-11*EXP(180./TEMP))
! <G0OH_OH_a>:
! RCONST(15) = constant rate coefficient
! <G0OH_OH_b>:
  RCONST(16) = (k_3rd(TEMP,cair,6.900e-31,1.,2.600e-11,0.,0.6))
! <G0OH_O3>:
  RCONST(17) = (1.700e-12*EXP(-940./TEMP))
! <G0HO2_O3P>:
  RCONST(18) = (3.000e-11*EXP(200./TEMP))
! <G0HO2_OH>:
  RCONST(19) = (4.800e-11*EXP(250./TEMP))
! <G0HO2_O3>:
  RCONST(20) = (2.03e-16*EXP(693.0/TEMP)*(TEMP/300.0)**4.57)
! <G0HO2_HO2>:
  RCONST(21) = (kHO2_HO2)
! <G0H2O2_O3P>:
  RCONST(22) = (1.400e-12*EXP(-2000./TEMP))
! <G0H2O2_OH>:
! RCONST(23) = constant rate coefficient
! <G0N_OH>:
! RCONST(24) = constant rate coefficient
! <G0N_O2>:
  RCONST(25) = (1.500e-11*EXP(-3600./TEMP))
! <G0N_NO>:
  RCONST(26) = (2.100e-11*EXP(100./TEMP))
! <G0N_NO2>:
  RCONST(27) = (5.800e-12*EXP(220./TEMP))
! <G0NO_O3P>:
  RCONST(28) = (k_3rd(TEMP,cair,9.000e-32,1.5,3.000e-11,0.,0.6))
! <G0NO_O3>:
  RCONST(29) = (3.000e-12*EXP(-1500./TEMP))
! <G0NO_HO2>:
  RCONST(30) = (3.300e-12*EXP(270./TEMP))
! <G0NO2_O3P_a>:
  RCONST(31) = (5.100e-12*EXP(210./TEMP))
! <G0NO2_O3P_b>:
  RCONST(32) = (k_3rd(TEMP,cair,2.500e-31,1.8,2.200e-11,0.7,0.6))
! <G0NO2_O3>:
  RCONST(33) = (1.200e-13*EXP(-2450./TEMP))
! <G0NO2_H>:
  RCONST(34) = (4.000e-10*EXP(-340./TEMP))
! <G0NO2_OH>:
  RCONST(35) = (k_3rd(TEMP,cair,1.800e-30,3.,2.800e-11,0.,0.6))
! <G0NO3_O3P>:
! RCONST(36) = constant rate coefficient
! <G0NO3_OH>:
! RCONST(37) = constant rate coefficient
! <G0NO3_HO2>:
! RCONST(38) = constant rate coefficient
! <G0NO3_NO>:
  RCONST(39) = (1.500e-11*EXP(170./TEMP))
! <G0HNO3_OH>:
  RCONST(40) = (kHNO3_OH)
! <G0NO_OH>:
  RCONST(41) = (k_3rd(TEMP,cair,7.000e-31,2.6,3.600e-11,0.1,0.6))
! <G0HONO_OH>:
  RCONST(42) = (1.800e-11*EXP(-390./TEMP))
! <G0NO2_HO2>:
  RCONST(43) = (kNO2HO2)
! <G0HNO4_OH>:
  RCONST(44) = (1.300e-12*EXP(380./TEMP))
! <G0HNO4>:
  RCONST(45) = (kHNO4)
! <G0NO2_NO3>:
  RCONST(46) = (kNO2NO3)
! <G0N2O5_a>:
  RCONST(47) = (kN2O5)
! <G0NH3_OH>:
  RCONST(48) = (1.700e-12*EXP(-710./TEMP))
! <G0CO_OH_a>:
  RCONST(49) = (kCO_OH)
! <G0CO_OH_b>:
  RCONST(50) = (k_3rd(TEMP,cair,5.900e-33,1.4,1.100e-12,-1.3,0.6))
! <G0CH4_OH>:
  RCONST(51) = (2.450e-12*EXP(-1775./TEMP))
! <G0CH3OH_OH>:
  RCONST(52) = (2.900e-12*EXP(-345./TEMP))
! <G0CH3O2_NO>:
  RCONST(53) = (1.960e-12*EXP(403./TEMP))
! <G0CH3O2_HO2>:
  RCONST(54) = (3.800e-13*EXP(730./TEMP))
! <G0CH3O2_CH3O2_a>:
  RCONST(55) = (7.400e-13*EXP(-520./TEMP))
! <G0CH3O2_CH3O2_b>:
  RCONST(56) = (2.330e-14*EXP(678./TEMP))
! <G0HCHO_O3P>:
  RCONST(57) = (3.400e-11*EXP(-1600./TEMP))
! <G0HCHO_OH>:
  RCONST(58) = (5.500e-12*EXP(125./TEMP))
! <G0HCHO_HO2>:
  RCONST(59) = (9.700e-15*EXP(625./TEMP))
! <G0HCHO_NO3>:
  RCONST(60) = (6.000e-13*EXP(-2058./TEMP))
! <G0CH3OOH_OH>:
  RCONST(61) = (3.800e-12*EXP(200./TEMP))
! <G0HCOOH_OH>:
! RCONST(62) = constant rate coefficient
! <G0HOCH2OO>:
  RCONST(63) = (2.400e+12*EXP(-7000./TEMP))
! <G0HOCH2OO_NO>:
  RCONST(64) = (2.600e-12*EXP(265./TEMP))
! <G0HOCH2OO_HO2>:
  RCONST(65) = (7.500e-13*EXP(700./TEMP))
! <G0HCN_OH>:
  RCONST(66) = (1.200e-13*EXP(-400./TEMP))
! <G0CH3O2_NO2>:
  RCONST(67) = (kNO2CH3O2)
! <G0CH3O2NO2>:
  RCONST(68) = (kCH3O2NO2)
! <G0C2H2_OH>:
  RCONST(69) = (k_3rd(TEMP,cair,5.500e-30,0.,8.300e-13,-2.,0.6))
! <G0C2H4_OH>:
  RCONST(70) = (k_3rd(TEMP,cair,1.000e-28,4.5,7.500e-12,0.85,0.6))
! <G0C2H4_O3>:
  RCONST(71) = (9.100e-15*EXP(-2580./TEMP))
! <G0C2H6_OH>:
  RCONST(72) = (7.660e-12*EXP(-1020./TEMP))
! <G0C2H5OH_OH>:
  RCONST(73) = (3.350e-12*EXP(0./TEMP))
! <G0CH3CHO_OH>:
  RCONST(74) = (4.630e-12*EXP(350./TEMP))
! <G0CH3CHO_NO3>:
  RCONST(75) = (1.400e-12*EXP(-1900./TEMP))
! <G0CH3CO3H_OH>:
! RCONST(76) = constant rate coefficient
! <G0C2H5O2_NO>:
  RCONST(77) = (2.620e-12*EXP(373./TEMP))
! <G0C2H5O2_HO2>:
  RCONST(78) = (7.400e-13*EXP(700./TEMP))
! <G0C2H5O2_CH3O2>:
! RCONST(79) = constant rate coefficient
! <G0C2H5O2_CH3CO3>:
  RCONST(80) = (1.800e-12*EXP(500./TEMP))
! <G0C2H5O2_C2H5O2>:
! RCONST(81) = constant rate coefficient
! <G0C2H5OOH_OH>:
  RCONST(82) = (3.800e-12*EXP(200./TEMP))
! <G0CH3CO3_NO>:
  RCONST(83) = (7.500e-12*EXP(290./TEMP))
! <G0CH3CO3_NO2>:
  RCONST(84) = (k_CH3CO3_NO2)
! <G0CH3CO3_HO2>:
  RCONST(85) = (5.200e-13*EXP(980./TEMP))
! <G0CH3CO3_CH3O2>:
  RCONST(86) = (2.000e-12*EXP(500./TEMP))
! <G0CH3CO3_CH3CO3>:
  RCONST(87) = (2.900e-12*EXP(500./TEMP))
! <G0CH3CO2H_OH>:
  RCONST(88) = (3.150e-14*EXP(920./TEMP))
! <G0PAN>:
  RCONST(89) = (kPAN)
! <G0PAN_OH>:
! RCONST(90) = constant rate coefficient
! <G0HOCH2CH2O2_NO>:
  RCONST(91) = (4.200e-12*EXP(180./TEMP))
! <G0HOCH2CH2O2_HO2>:
  RCONST(92) = (7.500e-13*EXP(700./TEMP))
! <G0HOCH2CH2O2_CH3O2>:
  RCONST(93) = (4.000e-12*EXP(1000./TEMP))
! <G0HOCH2CH2O2_CH3CO3>:
! RCONST(94) = constant rate coefficient
! <G0HOCH2CH2O_O2>:
! RCONST(95) = constant rate coefficient
! <G0HOCH2CH2O>:
  RCONST(96) = (1.600e+11*EXP(-4150./TEMP))
! <G0GLYOX_OH>:
  RCONST(97) = (3.100e-12*EXP(340./TEMP))
! <G0GLYOX_NO3>:
! RCONST(98) = constant rate coefficient
! <G0HOCH2CHO_OH>:
! RCONST(99) = constant rate coefficient
! <G0HOCH2CHO_NO3>:
  RCONST(100) = (1.440e-12*EXP(-1862./TEMP))
! <G0HOCH2CO3_NO2>:
  RCONST(101) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6))
! <G0HOCH2CO3_HO2>:
  RCONST(102) = (4.300e-13*EXP(1040./TEMP))
! <G0HOCH2CO3_CH3O2>:
! RCONST(103) = constant rate coefficient
! <G0HOCH2CO3_CH3CO3>:
! RCONST(104) = constant rate coefficient
! <G0HOCH2CO3_NO>:
  RCONST(105) = (8.100e-12*EXP(270./TEMP))
! <G0HOCH2CO3_NO3>:
! RCONST(106) = constant rate coefficient
! <G0HOCH2CO2H_OH>:
! RCONST(107) = constant rate coefficient
! <G0HOCH2CO3H_OH>:
! RCONST(108) = constant rate coefficient
! <G0HCOCO3_CH3O2>:
! RCONST(109) = constant rate coefficient
! <G0HCOCO3_CH3CO3>:
! RCONST(110) = constant rate coefficient
! <G0HCOCO3_HO2>:
  RCONST(111) = (4.300e-13*EXP(1040./TEMP))
! <G0HCOCO3_NO>:
  RCONST(112) = (8.100e-12*EXP(270./TEMP))
! <G0HCOCO3_NO3>:
! RCONST(113) = constant rate coefficient
! <G0HCOCO2H_OH>:
! RCONST(114) = constant rate coefficient
! <G0HCOCO3H_OH>:
! RCONST(115) = constant rate coefficient
! <G0CH3CN_OH>:
  RCONST(116) = (7.800e-13*EXP(-1050./TEMP))
! <G0C3H6_OH>:
  RCONST(117) = (k_3rd(TEMP,cair,8.000e-27,3.5,3.000e-11,0.,0.5))
! <G0C3H6_O3>:
  RCONST(118) = (5.500e-15*EXP(-1880./TEMP))
! <G0C3H6_NO3>:
  RCONST(119) = (4.600e-13*EXP(-1156./TEMP))
! <G0C3H8_OH>:
  RCONST(120) = (7.600e-12*EXP(-585./TEMP))
! <G0CH3COCH3_OH>:
  RCONST(121) = (1.33e-13+3.82e-11*EXP(-2000./TEMP))
! <G0C3H7O2_NO>:
  RCONST(122) = (2.900e-12*EXP(350./TEMP))
! <G0C3H7O2_HO2>:
  RCONST(123) = (7.500e-13*EXP(700./TEMP))
! <G0C3H7O2_CH3O2>:
  RCONST(124) = (3.750e-13*EXP(-40./TEMP))
! <G0C3H7O2_CH3CO3>:
! RCONST(125) = constant rate coefficient
! <G0C3H7OOH_OH>:
  RCONST(126) = (3.800e-12*EXP(200./TEMP))
! <G0HYPROPO2_NO>:
  RCONST(127) = (4.200e-12*EXP(180./TEMP))
! <G0HYPROPO2_NO3>:
! RCONST(128) = constant rate coefficient
! <G0HYPROPO2_HO2>:
  RCONST(129) = (7.500e-13*EXP(700./TEMP))
! <G0HYPROPO2_CH3O2>:
! RCONST(130) = constant rate coefficient
! <G0HYPROPO2_CH3CO3>:
! RCONST(131) = constant rate coefficient
! <G0HYPROPO2H_OH>:
  RCONST(132) = (3.800e-12*EXP(200./TEMP))
! <G0ACETOL_OH>:
! RCONST(133) = constant rate coefficient
! <G0MGLYOX_OH>:
  RCONST(134) = (8.400e-13*EXP(830./TEMP))
! <G0MGLYOX_NO3>:
  RCONST(135) = (1.400e-12*EXP(-1860./TEMP))
! <G0CH3COCH2O2_NO>:
  RCONST(136) = (2.900e-12*EXP(300./TEMP))
! <G0CH3COCH2O2_HO2>:
  RCONST(137) = (8.600e-13*EXP(700./TEMP))
! <G0CH3COCH2O2_CH3O2>:
  RCONST(138) = (7.100e-13*EXP(500./TEMP))
! <G0CH3COCH2O2_CH3CO3>:
! RCONST(139) = constant rate coefficient
! <G0HYPERACET_OH>:
  RCONST(140) = (3.800e-12*EXP(200./TEMP))
! <G0PRONO3BO2_NO>:
  RCONST(141) = (2.540e-12*EXP(360./TEMP))
! <G0PRONO3BO2_NO3>:
! RCONST(142) = constant rate coefficient
! <G0PRONO3BO2_HO2>:
  RCONST(143) = (1.320e-12*EXP(360./TEMP))
! <G0PRONO3BO2_CH3O2>:
! RCONST(144) = constant rate coefficient
! <G0PRONO3BO2_CH3CO3>:
! RCONST(145) = constant rate coefficient
! <G0PR2O2HNO3_OH>:
! RCONST(146) = constant rate coefficient
! <G0NOA_OH>:
! RCONST(147) = constant rate coefficient
! <G0BIGENE_OH>:
! RCONST(148) = constant rate coefficient
! <G0MEK_OH>:
  RCONST(149) = (2.300e-12*EXP(-170./TEMP))
! <G0LMEKO2_NO_a>:
  RCONST(150) = (4.032e-12*EXP(180./TEMP))
! <G0LMEKO2_NO_b>:
  RCONST(151) = (1.680e-13*EXP(180./TEMP))
! <G0LMEKO2_HO2>:
  RCONST(152) = (7.500e-13*EXP(700./TEMP))
! <G0LMEKO2_CH3O2>:
! RCONST(153) = constant rate coefficient
! <G0LMEKO2_CH3CO3>:
! RCONST(154) = constant rate coefficient
! <G0LMEKOOH_OH>:
  RCONST(155) = (3.800e-12*EXP(200./TEMP))
! <G0ENEO2_NO>:
  RCONST(156) = (4.200e-12*EXP(180./TEMP))
! <G0ENEO2_HO2>:
  RCONST(157) = (7.500e-13*EXP(700./TEMP))
! <G0ENEO2_CH3O2>:
! RCONST(158) = constant rate coefficient
! <G0ENEO2_CH3CO3>:
! RCONST(159) = constant rate coefficient
! <G0MACR_OH>:
  RCONST(160) = (1.860e-11*EXP(175./TEMP))
! <G0MACR_O3>:
  RCONST(161) = (1.360e-15*EXP(-2112./TEMP))
! <G0MACR_NO3>:
  RCONST(162) = (2.880e-12*EXP(-1862./TEMP))
! <G0MACO3_CH3O2>:
! RCONST(163) = constant rate coefficient
! <G0MACO3_CH3CO3>:
! RCONST(164) = constant rate coefficient
! <G0MACO3_HO2>:
  RCONST(165) = (4.300e-13*EXP(1040./TEMP))
! <G0MACO3_NO>:
  RCONST(166) = (8.700e-12*EXP(290./TEMP))
! <G0MACO3_NO3>:
! RCONST(167) = constant rate coefficient
! <G0MACO3_NO2>:
  RCONST(168) = (k_MACO3_NO2)
! <G0MACRO2_CH3O2>:
! RCONST(169) = constant rate coefficient
! <G0MACRO2_CH3CO3>:
! RCONST(170) = constant rate coefficient
! <G0MACRO2_NO_a>:
  RCONST(171) = (2.464e-12*EXP(360./TEMP))
! <G0MACRO2_NO_b>:
  RCONST(172) = (7.620e-14*EXP(360./TEMP))
! <G0MACRO2_NO3>:
! RCONST(173) = constant rate coefficient
! <G0MACRO2_HO2>:
  RCONST(174) = (1.820e-13*EXP(1300./TEMP))
! <G0MACRO2>:
  RCONST(175) = (2.900e+07*EXP(-5297./TEMP))
! <G0MACROOH_OH>:
! RCONST(176) = constant rate coefficient
! <G0MACROH_OH>:
! RCONST(177) = constant rate coefficient
! <G0MPAN>:
  RCONST(178) = (kMPAN)
! <G0MPAN_OH>:
! RCONST(179) = constant rate coefficient
! <G0MACO2H_OH>:
! RCONST(180) = constant rate coefficient
! <G0MACO3H_OH>:
! RCONST(181) = constant rate coefficient
! <G0MVK_OH>:
  RCONST(182) = (4.130e-12*EXP(452./TEMP))
! <G0MVK_O3>:
  RCONST(183) = (7.510e-16*EXP(-1521./TEMP))
! <G0LHMVKABO2_CH3O2>:
! RCONST(184) = constant rate coefficient
! <G0LHMVKABO2_CH3CO3>:
! RCONST(185) = constant rate coefficient
! <G0LHMVKABO2_HO2>:
  RCONST(186) = (1.820e-13*EXP(1300./TEMP))
! <G0LHMVKABO2_NO_a>:
  RCONST(187) = (2.438e-12*EXP(360./TEMP))
! <G0LHMVKABO2_NO_b>:
  RCONST(188) = (1.020e-13*EXP(360./TEMP))
! <G0LHMVKABO2_NO3>:
! RCONST(189) = constant rate coefficient
! <G0MVKN_OH>:
! RCONST(190) = constant rate coefficient
! <G0MACRNO3_OH>:
! RCONST(191) = constant rate coefficient
! <G0LHMVKABOOH_OH>:
! RCONST(192) = constant rate coefficient
! <G0CO2H3CHO_OH>:
! RCONST(193) = constant rate coefficient
! <G0CO2H3CHO_NO3>:
  RCONST(194) = (5.760e-12*EXP(-1862./TEMP))
! <G0CO2H3CO3_CH3O2>:
! RCONST(195) = constant rate coefficient
! <G0CO2H3CO3_CH3CO3>:
! RCONST(196) = constant rate coefficient
! <G0CO2H3CO3_HO2>:
  RCONST(197) = (4.300e-13*EXP(1040./TEMP))
! <G0CO2H3CO3_NO>:
  RCONST(198) = (8.100e-12*EXP(270./TEMP))
! <G0CO2H3CO3_NO3>:
! RCONST(199) = constant rate coefficient
! <G0CO2H3CO3H_OH>:
! RCONST(200) = constant rate coefficient
! <G0MALO2_NO2>:
  RCONST(201) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6))
! <G0MALO2_NO>:
  RCONST(202) = (7.500e-12*EXP(290./TEMP))
! <G0MALO2_HO2>:
  RCONST(203) = (4.300e-13*EXP(1040./TEMP))
! <G0MALO2_CH3O2>:
! RCONST(204) = constant rate coefficient
! <G0MALO2_CH3CO3>:
! RCONST(205) = constant rate coefficient
! <G0MDIALO2_HO2>:
  RCONST(206) = (4.300e-13*EXP(1040./TEMP))
! <G0MDIALO2_NO>:
  RCONST(207) = (7.500e-12*EXP(290./TEMP))
! <G0MDIALO2_NO2>:
  RCONST(208) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6))
! <G0MDIALO2_CH3O2>:
! RCONST(209) = constant rate coefficient
! <G0MDIALO2_CH3CO3>:
! RCONST(210) = constant rate coefficient
! <G0BIGALKANE_OH>:
! RCONST(211) = constant rate coefficient
! <G0C5H8_OH>:
  RCONST(212) = (2.700e-11*EXP(390./TEMP))
! <G0C5H8_O3>:
  RCONST(213) = (7.860e-15*EXP(-1913./TEMP))
! <G0C5H8_NO3>:
  RCONST(214) = (3.030e-12*EXP(-446./TEMP))
! <G0MBO_OH>:
  RCONST(215) = (8.100e-12*EXP(610./TEMP))
! <G0MBO_O3>:
! RCONST(216) = constant rate coefficient
! <G0MBO_NO3>:
  RCONST(217) = (4.600e-14*EXP(-400./TEMP))
! <G0ALKO2_NO_a>:
  RCONST(218) = (3.780e-12*EXP(180./TEMP))
! <G0ALKO2_NO_b>:
  RCONST(219) = (4.200e-13*EXP(180./TEMP))
! <G0ALKO2_HO2>:
  RCONST(220) = (7.500e-13*EXP(700./TEMP))
! <G0ALKO2_CH3O2>:
! RCONST(221) = constant rate coefficient
! <G0ALKO2_CH3CO3>:
! RCONST(222) = constant rate coefficient
! <G0ALKOOH_OH>:
  RCONST(223) = (3.800e-12*EXP(200./TEMP))
! <G0ALKOH_OH>:
! RCONST(224) = constant rate coefficient
! <G0ALKNO3_OH>:
! RCONST(225) = constant rate coefficient
! <G0LISOPACO2_HO2>:
  RCONST(226) = (2.050e-13*EXP(1300./TEMP))
! <G0LISOPACO2_NO_a>:
  RCONST(227) = (2.235e-12*EXP(360./TEMP))
! <G0LISOPACO2_NO_b>:
  RCONST(228) = (3.050e-13*EXP(360./TEMP))
! <G0LISOPACO2_NO3>:
! RCONST(229) = constant rate coefficient
! <G0LISOPACO2_CH3O2>:
! RCONST(230) = constant rate coefficient
! <G0LISOPACO2_CH3CO3>:
! RCONST(231) = constant rate coefficient
! <G0LISOPACO2>:
  RCONST(232) = (4.100e+08*EXP(-7700./TEMP))
! <G0ISOPBO2>:
  RCONST(233) = (4.100e+08*EXP(-7700./TEMP))
! <G0ISOPDO2>:
  RCONST(234) = (4.100e+08*EXP(-7700./TEMP))
! <G0LISOPACOOH_OH>:
! RCONST(235) = constant rate coefficient
! <G0ISOPAOH_OH>:
! RCONST(236) = constant rate coefficient
! <G0LISOPACNO3_OH>:
! RCONST(237) = constant rate coefficient
! <G0LIEPOX_OH>:
! RCONST(238) = constant rate coefficient
! <G0LIECHO_OH>:
! RCONST(239) = constant rate coefficient
! <G0LIECHO_NO3>:
  RCONST(240) = (1.050e-11*EXP(-1860./TEMP))
! <G0LIECO3_HO2>:
  RCONST(241) = (5.200e-13*EXP(980./TEMP))
! <G0LIECO3_NO>:
  RCONST(242) = (7.500e-12*EXP(290./TEMP))
! <G0LIECO3_NO3>:
! RCONST(243) = constant rate coefficient
! <G0LIECO3H_OH>:
! RCONST(244) = constant rate coefficient
! <G0IEC1O2_HO2>:
  RCONST(245) = (2.050e-13*EXP(1300./TEMP))
! <G0IEC1O2_NO>:
  RCONST(246) = (2.700e-12*EXP(360./TEMP))
! <G0IEC1O2_NO3>:
! RCONST(247) = constant rate coefficient
! <G0ISOPBO2_HO2>:
  RCONST(248) = (2.050e-13*EXP(1300./TEMP))
! <G0ISOPBO2_NO_a>:
  RCONST(249) = (2.235e-12*EXP(360./TEMP))
! <G0ISOPBO2_NO_b>:
  RCONST(250) = (3.050e-13*EXP(360./TEMP))
! <G0ISOPBO2_NO3>:
! RCONST(251) = constant rate coefficient
! <G0ISOPBO2_CH3O2>:
! RCONST(252) = constant rate coefficient
! <G0ISOPBO2_CH3CO3>:
! RCONST(253) = constant rate coefficient
! <G0ISOPBOOH_OH>:
! RCONST(254) = constant rate coefficient
! <G0ISOPBOH_OH>:
! RCONST(255) = constant rate coefficient
! <G0ISOPBNO3_OH>:
! RCONST(256) = constant rate coefficient
! <G0ISOPDO2_HO2>:
  RCONST(257) = (2.050e-13*EXP(1300./TEMP))
! <G0ISOPDO2_NO_a>:
  RCONST(258) = (2.235e-12*EXP(360./TEMP))
! <G0ISOPDO2_NO_b>:
  RCONST(259) = (3.050e-13*EXP(360./TEMP))
! <G0ISOPDO2_NO3>:
! RCONST(260) = constant rate coefficient
! <G0ISOPDO2_CH3O2>:
! RCONST(261) = constant rate coefficient
! <G0ISOPDO2_CH3CO3>:
! RCONST(262) = constant rate coefficient
! <G0ISOPDOOH_OH>:
! RCONST(263) = constant rate coefficient
! <G0ISOPDOH_OH>:
! RCONST(264) = constant rate coefficient
! <G0ISOPDNO3_OH>:
! RCONST(265) = constant rate coefficient
! <G0NISOPO2_HO2>:
  RCONST(266) = (2.050e-13*EXP(1300./TEMP))
! <G0NISOPO2_NO>:
  RCONST(267) = (2.540e-12*EXP(360./TEMP))
! <G0NISOPO2_NO3>:
! RCONST(268) = constant rate coefficient
! <G0NISOPO2_CH3O2>:
! RCONST(269) = constant rate coefficient
! <G0NISOPO2_CH3CO3>:
! RCONST(270) = constant rate coefficient
! <G0NISOPOOH_OH>:
! RCONST(271) = constant rate coefficient
! <G0NC4CHO_OH>:
! RCONST(272) = constant rate coefficient
! <G0NC4CHO_O3>:
! RCONST(273) = constant rate coefficient
! <G0NC4CHO_NO3>:
  RCONST(274) = (6.120e-12*EXP(-1862./TEMP))
! <G0LNISO3_HO2>:
  RCONST(275) = (1.930e-13*EXP(1300./TEMP))
! <G0LNISO3_NO>:
  RCONST(276) = (4.270e-12*EXP(360./TEMP))
! <G0LNISO3_NO3>:
  RCONST(277) = (3.302e-12*EXP(360./TEMP))
! <G0LNISO3_CH3O2>:
! RCONST(278) = constant rate coefficient
! <G0LNISO3_CH3CO3>:
! RCONST(279) = constant rate coefficient
! <G0LNISOOH_OH>:
! RCONST(280) = constant rate coefficient
! <G0LHC4ACCHO_OH>:
! RCONST(281) = constant rate coefficient
! <G0LHC4ACCHO_O3>:
! RCONST(282) = constant rate coefficient
! <G0LHC4ACCHO_NO3>:
  RCONST(283) = (6.120e-12*EXP(-1862./TEMP))
! <G0LC578O2_NO>:
  RCONST(284) = (2.540e-12*EXP(360./TEMP))
! <G0LC578O2_NO3>:
! RCONST(285) = constant rate coefficient
! <G0LC578O2_HO2>:
  RCONST(286) = (2.050e-13*EXP(1300./TEMP))
! <G0LC578O2_CH3O2>:
! RCONST(287) = constant rate coefficient
! <G0LC578O2_CH3CO3>:
! RCONST(288) = constant rate coefficient
! <G0LC578OOH_OH>:
! RCONST(289) = constant rate coefficient
! <G0LHC4ACCO3>:
  RCONST(290) = (4.100e+08*EXP(-7700./TEMP))
! <G0LHC4ACCO3_CH3O2>:
! RCONST(291) = constant rate coefficient
! <G0LHC4ACCO3_CH3CO3>:
! RCONST(292) = constant rate coefficient
! <G0LHC4ACCO3_HO2>:
  RCONST(293) = (4.300e-13*EXP(1040./TEMP))
! <G0LHC4ACCO3_NO>:
  RCONST(294) = (8.100e-12*EXP(270./TEMP))
! <G0LHC4ACCO3_NO3>:
! RCONST(295) = constant rate coefficient
! <G0LHC4ACCO3_NO2>:
  RCONST(296) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.3))
! <G0LHC4ACCO2H_OH>:
! RCONST(297) = constant rate coefficient
! <G0LHC4ACCO3H_OH>:
! RCONST(298) = constant rate coefficient
! <G0LC5PAN1719>:
  RCONST(299) = (kPAN)
! <G0LC5PAN1719_OH>:
! RCONST(300) = constant rate coefficient
! <G0HCOC5_OH>:
! RCONST(301) = constant rate coefficient
! <G0C59O2_CH3O2>:
! RCONST(302) = constant rate coefficient
! <G0C59O2_CH3CO3>:
! RCONST(303) = constant rate coefficient
! <G0C59O2_NO>:
  RCONST(304) = (2.540e-12*EXP(360./TEMP))
! <G0C59O2_NO3>:
! RCONST(305) = constant rate coefficient
! <G0C59O2_HO2>:
  RCONST(306) = (2.050e-13*EXP(1300./TEMP))
! <G0C59OOH_OH>:
! RCONST(307) = constant rate coefficient
! <G0MBOO2_NO>:
  RCONST(308) = (2.600e-12*EXP(365./TEMP))
! <G0MBOO2_CH3O2>:
  RCONST(309) = (3.750e-13*EXP(-40./TEMP))
! <G0MBOO2_CH3CO3>:
! RCONST(310) = constant rate coefficient
! <G0MBOO2_HO2>:
  RCONST(311) = (7.500e-13*EXP(700./TEMP))
! <G0MBOOOH_OH>:
  RCONST(312) = (3.800e-12*EXP(200./TEMP))
! <G0IBUTALOH_OH>:
! RCONST(313) = constant rate coefficient
! <G0IPRHOCO3_NO>:
  RCONST(314) = (2.600e-12*EXP(365./TEMP))
! <G0IPRHOCO3_HO2>:
  RCONST(315) = (4.300e-13*EXP(1040./TEMP))
! <G0IPRHOCO3_CH3O2>:
! RCONST(316) = constant rate coefficient
! <G0IPRHOCO3_CH3CO3>:
! RCONST(317) = constant rate coefficient
! <G0IPRHOCO3H_OH>:
! RCONST(318) = constant rate coefficient
! <G0MBONO3O2_HO2>:
  RCONST(319) = (4.300e-13*EXP(1040./TEMP))
! <G0MBONO3O2_NO>:
  RCONST(320) = (2.600e-12*EXP(365./TEMP))
! <G0MBONO3O2_NO3>:
! RCONST(321) = constant rate coefficient
! <G0MBONO3O2_CH3O2>:
! RCONST(322) = constant rate coefficient
! <G0MBONO3O2_CH3CO3>:
! RCONST(323) = constant rate coefficient
! <G0DICARBO2_HO2>:
  RCONST(324) = (4.300e-13*EXP(1040./TEMP))
! <G0DICARBO2_NO>:
  RCONST(325) = (7.500e-12*EXP(290./TEMP))
! <G0DICARBO2_NO2>:
  RCONST(326) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6))
! <G0DICARBO2_CH3O2>:
! RCONST(327) = constant rate coefficient
! <G0DICARBO2_CH3CO3>:
! RCONST(328) = constant rate coefficient
! <G0HPALD_OH>:
! RCONST(329) = constant rate coefficient
! <G0PACALD_OH>:
! RCONST(330) = constant rate coefficient
! <G0LISOPOOHO2_HO2>:
  RCONST(331) = (2.050e-13*EXP(1300./TEMP))
! <G0LISOPOOHO2_NO_a>:
  RCONST(332) = (2.540e-12*EXP(360./TEMP))
! <G0LISOPOOHO2_NO_b>:
  RCONST(333) = (3.050e-13*EXP(360./TEMP))
! <G0LISOPOOHO2_NO3>:
! RCONST(334) = constant rate coefficient
! <G0LISOPOOHO2_CH3O2>:
! RCONST(335) = constant rate coefficient
! <G0LISOPOOHO2_CH3CO3>:
! RCONST(336) = constant rate coefficient
! <G0LISOPNO3O2_HO2>:
  RCONST(337) = (2.050e-13*EXP(1300./TEMP))
! <G0LISOPNO3O2_NO_a>:
  RCONST(338) = (2.235e-12*EXP(360./TEMP))
! <G0LISOPNO3O2_NO_b>:
  RCONST(339) = (3.050e-13*EXP(360./TEMP))
! <G0LISOPNO3O2_NO3>:
! RCONST(340) = constant rate coefficient
! <G0LISOPNO3O2_CH3O2>:
! RCONST(341) = constant rate coefficient
! <G0LISOPNO3O2_CH3CO3>:
! RCONST(342) = constant rate coefficient
! <G0LISOPOOHOOH_OH_a>:
  RCONST(343) = (7.600e-12*EXP(200./TEMP))
! <G0LISOPOOHOOH_OH_b>:
! RCONST(344) = constant rate coefficient
! <G0LISOPNO3OOH_OH_a>:
  RCONST(345) = (3.800e-12*EXP(200./TEMP))
! <G0LISOPNO3OOH_OH_b>:
! RCONST(346) = constant rate coefficient
! <G0LISOPNO3NO3_OH>:
! RCONST(347) = constant rate coefficient
! <G0BENZENE_OH>:
  RCONST(348) = (2.300e-12*EXP(-193./TEMP))
! <G0PHENOL_OH>:
  RCONST(349) = (4.700e-13*EXP(1220./TEMP))
! <G0PHENOL_NO3>:
! RCONST(350) = constant rate coefficient
! <G0PHENO2_NO>:
  RCONST(351) = (2.600e-12*EXP(365./TEMP))
! <G0PHENO2_HO2>:
  RCONST(352) = (7.500e-13*EXP(700./TEMP))
! <G0PHENO2_CH3O2>:
! RCONST(353) = constant rate coefficient
! <G0PHENO2_CH3CO3>:
! RCONST(354) = constant rate coefficient
! <G0PHENOOH_OH>:
  RCONST(355) = (3.800e-12*EXP(200./TEMP))
! <G0C6H5O_NO2>:
! RCONST(356) = constant rate coefficient
! <G0C6H5O_O3>:
! RCONST(357) = constant rate coefficient
! <G0C6H5O2_NO>:
  RCONST(358) = (2.600e-12*EXP(365./TEMP))
! <G0C6H5O2_NO3>:
! RCONST(359) = constant rate coefficient
! <G0C6H5O2_HO2>:
  RCONST(360) = (7.500e-13*EXP(700./TEMP))
! <G0C6H5O2_CH3O2>:
! RCONST(361) = constant rate coefficient
! <G0C6H5O2_CH3CO3>:
! RCONST(362) = constant rate coefficient
! <G0C6H5OOH_OH>:
  RCONST(363) = (3.800e-12*EXP(200./TEMP))
! <G0BENZO2_NO>:
  RCONST(364) = (2.600e-12*EXP(365./TEMP))
! <G0BENZO2_HO2>:
  RCONST(365) = (7.500e-13*EXP(700./TEMP))
! <G0BENZO2_CH3O2>:
! RCONST(366) = constant rate coefficient
! <G0BENZO2_CH3CO3>:
! RCONST(367) = constant rate coefficient
! <G0BENZOOH_OH>:
  RCONST(368) = (3.800e-12*EXP(200./TEMP))
! <G0CATECHOL_OH>:
! RCONST(369) = constant rate coefficient
! <G0CATECHOL_NO3>:
! RCONST(370) = constant rate coefficient
! <G0CATEC1O_NO2>:
! RCONST(371) = constant rate coefficient
! <G0CATEC1O_O3>:
! RCONST(372) = constant rate coefficient
! <G0CATEC1O2_HO2>:
  RCONST(373) = (7.500e-13*EXP(700./TEMP))
! <G0CATEC1O2_NO>:
  RCONST(374) = (2.600e-12*EXP(365./TEMP))
! <G0CATEC1O2_NO3>:
! RCONST(375) = constant rate coefficient
! <G0CATEC1O2_CH3O2>:
! RCONST(376) = constant rate coefficient
! <G0CATEC1O2_CH3CO3>:
! RCONST(377) = constant rate coefficient
! <G0CATEC1OOH_OH>:
  RCONST(378) = (1.900e-12*EXP(190./TEMP))
! <G0TOLUENE_OH>:
  RCONST(379) = (1.700e-12*EXP(352./TEMP))
! <G0CRESOL_OH>:
! RCONST(380) = constant rate coefficient
! <G0CRESOL_NO3>:
! RCONST(381) = constant rate coefficient
! <G0TOLO2_HO2>:
  RCONST(382) = (7.500e-13*EXP(700./TEMP))
! <G0TOLO2_NO>:
  RCONST(383) = (2.600e-12*EXP(365./TEMP))
! <G0TOLO2_CH3O2>:
! RCONST(384) = constant rate coefficient
! <G0TOLO2_CH3CO3>:
! RCONST(385) = constant rate coefficient
! <G0TOLOOH_OH>:
  RCONST(386) = (3.800e-12*EXP(200./TEMP))
! <G0BZOO_HO2>:
  RCONST(387) = (7.500e-13*EXP(700./TEMP))
! <G0BZOO_NO>:
  RCONST(388) = (2.600e-12*EXP(365./TEMP))
! <G0BZOO_CH3O2>:
! RCONST(389) = constant rate coefficient
! <G0BZOO_CH3CO3>:
! RCONST(390) = constant rate coefficient
! <G0BZOOH_OH>:
  RCONST(391) = (3.800e-12*EXP(200./TEMP))
! <G0BZALD_OH>:
  RCONST(392) = (5.900e-12*EXP(225./TEMP))
! <G0ACBZO2_NO2>:
  RCONST(393) = (k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6))
! <G0PBZNIT>:
  RCONST(394) = (kPAN)
! <G0ACBZO2_NO>:
  RCONST(395) = (7.500e-12*EXP(290./TEMP))
! <G0ACBZO2_HO2>:
  RCONST(396) = (4.300e-13*EXP(1040./TEMP))
! <G0ACBZO2_CH3O2>:
! RCONST(397) = constant rate coefficient
! <G0ACBZO2_CH3CO3>:
! RCONST(398) = constant rate coefficient
! <G0LXYL_OH>:
! RCONST(399) = constant rate coefficient
! <G0XYLOL_OH>:
! RCONST(400) = constant rate coefficient
! <G0XYLOL_NO3>:
! RCONST(401) = constant rate coefficient
! <G0XYLOLO2_NO>:
  RCONST(402) = (2.600e-12*EXP(365./TEMP))
! <G0XYLOLO2_HO2>:
  RCONST(403) = (7.500e-13*EXP(700./TEMP))
! <G0XYLOLO2_CH3O2>:
! RCONST(404) = constant rate coefficient
! <G0XYLOLO2_CH3CO3>:
! RCONST(405) = constant rate coefficient
! <G0XYLOLOOH_OH>:
  RCONST(406) = (3.800e-12*EXP(200./TEMP))
! <G0XYLENO2_HO2>:
  RCONST(407) = (7.500e-13*EXP(700./TEMP))
! <G0XYLENO2_NO>:
  RCONST(408) = (2.600e-12*EXP(365./TEMP))
! <G0XYLENO2_CH3O2>:
! RCONST(409) = constant rate coefficient
! <G0XYLENO2_CH3CO3>:
! RCONST(410) = constant rate coefficient
! <G0XYLENOOH_OH>:
  RCONST(411) = (3.800e-12*EXP(200./TEMP))
! <G0APINENE_OH>:
  RCONST(412) = (1.200e-11*EXP(440./TEMP))
! <G0BPINENE_OH>:
  RCONST(413) = (1.600e-11*EXP(470./TEMP))
! <G0LIMON_OH>:
  RCONST(414) = (4.200e-11*EXP(400./TEMP))
! <G0MYRC_OH>:
! RCONST(415) = constant rate coefficient
! <G0BCARY_OH>:
! RCONST(416) = constant rate coefficient
! <G0APINENE_O3>:
  RCONST(417) = (6.300e-16*EXP(-580./TEMP))
! <G0BPINENE_O3>:
  RCONST(418) = (1.700e-15*EXP(-1300./TEMP))
! <G0LIMON_O3>:
  RCONST(419) = (3.000e-15*EXP(-780./TEMP))
! <G0MYRC_O3>:
! RCONST(420) = constant rate coefficient
! <G0BCARY_O3>:
! RCONST(421) = constant rate coefficient
! <G0APINENE_NO3>:
  RCONST(422) = (1.200e-12*EXP(490./TEMP))
! <G0BPINENE_NO3>:
! RCONST(423) = constant rate coefficient
! <G0LIMON_NO3>:
! RCONST(424) = constant rate coefficient
! <G0MYRC_NO3>:
! RCONST(425) = constant rate coefficient
! <G0BCARY_NO3>:
! RCONST(426) = constant rate coefficient
! <G0TERPO2_NO>:
  RCONST(427) = (4.200e-12*EXP(180./TEMP))
! <G0TERPO2_HO2>:
  RCONST(428) = (7.500e-13*EXP(700./TEMP))
! <G0TERPO2_CH3O2>:
  RCONST(429) = (2.000e-12*EXP(500./TEMP))
! <G0TERPO2_CH3CO3>:
! RCONST(430) = constant rate coefficient
! <G0TERPOOH_OH>:
! RCONST(431) = constant rate coefficient
! <G0TERPROD1_OH>:
! RCONST(432) = constant rate coefficient
! <G0TERPROD1_NO3>:
! RCONST(433) = constant rate coefficient
! <G0TERPNO3_OH>:
! RCONST(434) = constant rate coefficient
! <G0TERP2O2_NO>:
  RCONST(435) = (4.200e-12*EXP(180./TEMP))
! <G0TERP2O2_HO2>:
  RCONST(436) = (7.500e-13*EXP(700./TEMP))
! <G0TERP2O2_CH3O2>:
  RCONST(437) = (2.000e-12*EXP(500./TEMP))
! <G0TERP2O2_CH3CO3>:
! RCONST(438) = constant rate coefficient
! <G0TERP2OOH_OH>:
! RCONST(439) = constant rate coefficient
! <G0TERPROD2_OH>:
! RCONST(440) = constant rate coefficient
! <G0NTERPO2_NO>:
  RCONST(441) = (4.200e-12*EXP(180./TEMP))
! <G0NTERPO2_HO2>:
  RCONST(442) = (7.500e-13*EXP(700./TEMP))
! <G0NTERPO2_CH3O2>:
  RCONST(443) = (2.000e-12*EXP(500./TEMP))
! <G0NTERPO2_CH3CO3>:
! RCONST(444) = constant rate coefficient
! <G0NTERPO2_NO3>:
! RCONST(445) = constant rate coefficient
! <G0NTERPNO3_OH>:
! RCONST(446) = constant rate coefficient
! <G0ELVOC_OH>:
! RCONST(447) = constant rate coefficient
! <G0O1D_N2O_a>:
  RCONST(448) = (7.250e-11*EXP(20./TEMP))
! <G0O1D_N2O_b>:
  RCONST(449) = (4.630e-11*EXP(20./TEMP))
! <G0O1D_O3>:
! RCONST(450) = constant rate coefficient
! <G0O1D_CFCl3>:
! RCONST(451) = constant rate coefficient
! <G0O1D_CF2Cl2>:
! RCONST(452) = constant rate coefficient
! <G0O1D_CFC113>:
! RCONST(453) = constant rate coefficient
! <G0O1D_CFC114>:
! RCONST(454) = constant rate coefficient
! <G0O1D_CFC115>:
! RCONST(455) = constant rate coefficient
! <G0O1D_HCFC22>:
! RCONST(456) = constant rate coefficient
! <G0O1D_HCFC141B>:
! RCONST(457) = constant rate coefficient
! <G0O1D_HCFC142B>:
! RCONST(458) = constant rate coefficient
! <G0O1D_CCl4>:
! RCONST(459) = constant rate coefficient
! <G0O1D_CH3Br>:
! RCONST(460) = constant rate coefficient
! <G0O1D_CF2ClBr>:
! RCONST(461) = constant rate coefficient
! <G0O1D_CF3Br>:
! RCONST(462) = constant rate coefficient
! <G0O1D_H1202>:
! RCONST(463) = constant rate coefficient
! <G0O1D_H2402>:
! RCONST(464) = constant rate coefficient
! <G0O1D_CHBr3>:
! RCONST(465) = constant rate coefficient
! <G0O1D_CH2Br2>:
! RCONST(466) = constant rate coefficient
! <G0O1D_COF2>:
! RCONST(467) = constant rate coefficient
! <G0O1D_COFCL>:
! RCONST(468) = constant rate coefficient
! <G0O1D_CH4_a>:
! RCONST(469) = constant rate coefficient
! <G0O1D_CH4_b>:
! RCONST(470) = constant rate coefficient
! <G0O1D_CH4_c>:
! RCONST(471) = constant rate coefficient
! <G0O1D_H2>:
! RCONST(472) = constant rate coefficient
! <G0O1D_HCl>:
! RCONST(473) = constant rate coefficient
! <G0O1D_HBr>:
! RCONST(474) = constant rate coefficient
! <G0O1D_HCN>:
  RCONST(475) = (7.700e-11*EXP(100./TEMP))
! <G0Cl_O3>:
  RCONST(476) = (2.300e-11*EXP(-200./TEMP))
! <G0Cl_H2>:
  RCONST(477) = (3.050e-11*EXP(-2270./TEMP))
! <G0Cl_H2O2>:
  RCONST(478) = (1.100e-11*EXP(-980./TEMP))
! <G0Cl_HO2_a>:
  RCONST(479) = (1.400e-11*EXP(270./TEMP))
! <G0Cl_HO2_b>:
  RCONST(480) = (3.600e-11*EXP(-375./TEMP))
! <G0Cl2O2>:
  RCONST(481) = (kCl2O2)
! <G0ClO_O3P>:
  RCONST(482) = (2.800e-11*EXP(85./TEMP))
! <G0ClO_OH_a>:
  RCONST(483) = (7.400e-12*EXP(270./TEMP))
! <G0ClO_OH_b>:
  RCONST(484) = (6.000e-13*EXP(230./TEMP))
! <G0ClO_HO2>:
  RCONST(485) = (2.600e-12*EXP(290./TEMP))
! <G0ClO_NO>:
  RCONST(486) = (6.400e-12*EXP(290./TEMP))
! <G0ClO_NO2>:
  RCONST(487) = (k_3rd(TEMP,cair,1.800e-31,3.4,1.500e-11,1.9,0.6))
! <G0ClO_ClO_a>:
  RCONST(488) = (3.000e-11*EXP(-2450./TEMP))
! <G0ClO_ClO_b>:
  RCONST(489) = (1.000e-12*EXP(-1590./TEMP))
! <G0ClO_ClO_c>:
  RCONST(490) = (3.500e-13*EXP(-1370./TEMP))
! <G0ClO_ClO_d>:
  RCONST(491) = (kClOClO)
! <G0HCl_OH>:
  RCONST(492) = (1.800e-12*EXP(-250./TEMP))
! <G0HCl_O3P>:
  RCONST(493) = (1.000e-11*EXP(-3300./TEMP))
! <G0HOCl_O3P>:
! RCONST(494) = constant rate coefficient
! <G0HOCl_Cl>:
  RCONST(495) = (3.400e-12*EXP(-130./TEMP))
! <G0HOCl_OH>:
  RCONST(496) = (3.000e-12*EXP(-500./TEMP))
! <G0ClNO3_O3P>:
  RCONST(497) = (3.600e-12*EXP(-840./TEMP))
! <G0ClNO3_OH>:
  RCONST(498) = (1.200e-12*EXP(-330./TEMP))
! <G0ClNO3_Cl>:
  RCONST(499) = (6.500e-12*EXP(135./TEMP))
! <G0Br_O3>:
  RCONST(500) = (1.600e-11*EXP(-780./TEMP))
! <G0Br_HO2>:
  RCONST(501) = (4.800e-12*EXP(-310./TEMP))
! <G0Br_NO2>:
  RCONST(502) = (k_3rd(TEMP,cair,4.200e-31,2.4,2.700e-11,0.,0.6))
! <G0BrONO>:
  RCONST(503) = (1.648e+11*EXP(-7399./TEMP))
! <G0BrO_O3P>:
  RCONST(504) = (1.900e-11*EXP(230./TEMP))
! <G0BrO_OH>:
  RCONST(505) = (1.700e-11*EXP(250./TEMP))
! <G0BrO_HO2>:
  RCONST(506) = (4.500e-12*EXP(460./TEMP))
! <G0BrO_NO>:
  RCONST(507) = (8.800e-12*EXP(260./TEMP))
! <G0BrO_NO2>:
  RCONST(508) = (k_3rd(TEMP,cair,5.200e-31,3.2,6.900e-12,2.9,0.6))
! <G0BrO_ClO_a>:
  RCONST(509) = (9.500e-13*EXP(550./TEMP))
! <G0BrO_ClO_b>:
  RCONST(510) = (2.300e-12*EXP(260./TEMP))
! <G0BrO_ClO_c>:
  RCONST(511) = (4.100e-13*EXP(290./TEMP))
! <G0BrO_BrO_a>:
  RCONST(512) = (2.400e-12*EXP(40./TEMP))
! <G0BrO_BrO_b>:
  RCONST(513) = (2.800e-14*EXP(860./TEMP))
! <G0HBr_OH>:
  RCONST(514) = (5.500e-12*EXP(200./TEMP))
! <G0HBr_O3P>:
  RCONST(515) = (5.800e-12*EXP(-1500./TEMP))
! <G0HOBr_O3P>:
  RCONST(516) = (1.200e-10*EXP(-430./TEMP))
! <G0BrNO3_O3P>:
  RCONST(517) = (1.900e-11*EXP(215./TEMP))
! <G0BrNO3_Br>:
! RCONST(518) = constant rate coefficient
! <G0Br2_OH>:
  RCONST(519) = (2.100e-11*EXP(240./TEMP))
! <G0F_H2O>:
! RCONST(520) = constant rate coefficient
! <G0F_H2>:
  RCONST(521) = (1.400e-10*EXP(-500./TEMP))
! <G0F_CH4>:
  RCONST(522) = (1.600e-10*EXP(-260./TEMP))
! <G0F_HNO3>:
  RCONST(523) = (6.000e-12*EXP(400./TEMP))
! <G0Cl_HCHO>:
  RCONST(524) = (8.100e-11*EXP(-30./TEMP))
! <G0Cl_CH4>:
  RCONST(525) = (7.300e-12*EXP(-1280./TEMP))
! <G0Cl_CH3CN>:
  RCONST(526) = (1.600e-11*EXP(-2140./TEMP))
! <G0Cl_C2H2>:
  RCONST(527) = (k_3rd(TEMP,cair,5.200e-30,2.4,2.200e-10,0.7,0.6))
! <G0Cl_C2H4>:
  RCONST(528) = (k_3rd(TEMP,cair,1.600e-29,3.3,3.100e-10,1.,0.6))
! <G0Cl_C2H6>:
  RCONST(529) = (7.200e-11*EXP(-70./TEMP))
! <G0Cl_CH3O2>:
! RCONST(530) = constant rate coefficient
! <G0Cl_CH3OH>:
  RCONST(531) = (7.100e-11*EXP(-75./TEMP))
! <G0Cl_CH3OOH>:
! RCONST(532) = constant rate coefficient
! <G0Cl_CH3CHO>:
! RCONST(533) = constant rate coefficient
! <G0Cl_HOCH2CHO>:
! RCONST(534) = constant rate coefficient
! <G0Cl_GLYOX>:
! RCONST(535) = constant rate coefficient
! <G0Cl_C3H8>:
! RCONST(536) = constant rate coefficient
! <G0Cl_CH3COCH3>:
  RCONST(537) = (1.500e-11*EXP(-590./TEMP))
! <G0Cl_ACETOL>:
! RCONST(538) = constant rate coefficient
! <G0Cl_BIGALKANE>:
! RCONST(539) = constant rate coefficient
! <G0Cl_MEK>:
  RCONST(540) = (3.800e-11*EXP(16./TEMP))
! <G0ClO_CH3O2>:
  RCONST(541) = (3.300e-12*EXP(-115./TEMP))
! <G0Br_HCHO>:
  RCONST(542) = (1.700e-11*EXP(-800./TEMP))
! <G0Br_CH3CHO>:
  RCONST(543) = (1.800e-11*EXP(-460./TEMP))
! <G0BrO_CH3O2>:
  RCONST(544) = (2.420e-14*EXP(1617./TEMP))
! <G0SO2_OH>:
  RCONST(545) = (k_3rd(TEMP,cair,3.300e-31,4.3,1.600e-12,0.,0.6))
! <G0DMS_OH_a>:
  RCONST(546) = (1.130e-11*EXP(-253./TEMP))
! <G0DMS_OH_b>:
  RCONST(547) = (8.2e-39*EXP(5376./TEMP)*0.21*cair/(1.+1.05e-5*EXP(3644./TEMP)*0.21))
! <G0DMS_NO3>:
  RCONST(548) = (1.900e-13*EXP(520./TEMP))
! <G0DMS_Cl>:
! RCONST(549) = constant rate coefficient
! <G0DMS_Br>:
  RCONST(550) = (9.000e-11*EXP(-2386./TEMP))
! <G0DMS_BrO>:
! RCONST(551) = constant rate coefficient
! <G0DMSO_OH>:
! RCONST(552) = constant rate coefficient
! <G0CH3SO2>:
  RCONST(553) = (1.800e+13*EXP(-8661./TEMP))
! <G0CH3SO2_O3>:
! RCONST(554) = constant rate coefficient
! <G0CH3SO3_HO2>:
! RCONST(555) = constant rate coefficient
! <G0CH3Br_OH>:
  RCONST(556) = (2.350e-12*EXP(-1300./TEMP))
! <G0CH3Br_Cl>:
  RCONST(557) = (1.400e-11*EXP(-1030./TEMP))
! <G0CH2Br2_OH>:
  RCONST(558) = (2.000e-12*EXP(-840./TEMP))
! <G0CHBr3_OH>:
  RCONST(559) = (1.350e-12*EXP(-600./TEMP))
! <G0CH2Br2_Cl>:
  RCONST(560) = (6.300e-12*EXP(-800./TEMP))
! <G0CHBr3_Cl>:
  RCONST(561) = (4.850e-12*EXP(-850./TEMP))
! <G0CH3Cl_Cl>:
  RCONST(562) = (2.170e-11*EXP(-1130./TEMP))
! <G0CH3Cl_OH>:
  RCONST(563) = (2.400e-12*EXP(-1250./TEMP))
! <G0CH3CCl3_OH>:
  RCONST(564) = (1.640e-12*EXP(-1520./TEMP))
! <G0HCFC22_OH>:
  RCONST(565) = (1.050e-12*EXP(-1600./TEMP))
! <G0HCFC141B_OH>:
  RCONST(566) = (1.250e-12*EXP(-1600./TEMP))
! <G0HCFC142B_OH>:
  RCONST(567) = (1.300e-12*EXP(-1770./TEMP))
! <G0HNO3>:
  RCONST(568) = (khet_Tr(iht_HNO3))
! <G0N2O5_b>:
  RCONST(569) = (khet_Tr(iht_N2O5))
! <G0N2O5_cde>:
  RCONST(570) = (khet_St(ihs_N2O5_H2O))
! <G0ClNO3_abc>:
  RCONST(571) = (khet_St(ihs_ClNO3_H2O))
! <G0BrNO3_abc>:
  RCONST(572) = (khet_St(ihs_BrNO3_H2O))
! <G0ClNO3_HCl_abc>:
  RCONST(573) = (khet_St(ihs_ClNO3_HCl))
! <G0HOCl_HCl_abc>:
  RCONST(574) = (khet_St(ihs_HOCl_HCl))
! <G0HOBr_HCl_ab>:
  RCONST(575) = (khet_St(ihs_HOBr_HCl))
! <J0O3_a>:
  RCONST(576) = (jx(ip_O1D))
! <J0O3_b>:
  RCONST(577) = (jx(ip_O3P))
! <J0H2O2>:
  RCONST(578) = (jx(ip_H2O2))
! <J0N2O>:
  RCONST(579) = (jx(ip_N2O))
! <J0NO>:
  RCONST(580) = (jx(ip_NO))
! <J0NO2>:
  RCONST(581) = (jx(ip_NO2))
! <J0NO3_a>:
  RCONST(582) = (jx(ip_NO2O))
! <J0NO3_b>:
  RCONST(583) = (jx(ip_NOO2))
! <J0HNO3>:
  RCONST(584) = (jx(ip_HNO3))
! <J0HONO>:
  RCONST(585) = (jx(ip_HONO))
! <J0HO2NO2_a>:
  RCONST(586) = (.333*jx(ip_HNO4))
! <J0HO2NO2_b>:
  RCONST(587) = (.667*jx(ip_HNO4))
! <J0N2O5_a>:
  RCONST(588) = (jx(ip_N2O5))
! <J0CO2>:
  RCONST(589) = (jx(ip_CO2))
! <J0CH4_a>:
  RCONST(590) = (0.42*jx(ip_CH4))
! <J0CH4_b>:
  RCONST(591) = (0.48*jx(ip_CH4))
! <J0CH2O_a>:
  RCONST(592) = (jx(ip_CHOH))
! <J0CH2O_b>:
  RCONST(593) = (jx(ip_COH2))
! <J0CH3OOH>:
  RCONST(594) = (jx(ip_CH3OOH))
! <J0CH3O2NO2_a>:
  RCONST(595) = (.333*jx(ip_CH3O2NO2))
! <J0CH3O2NO2_b>:
  RCONST(596) = (.667*jx(ip_CH3O2NO2))
! <J0CH3CHO>:
  RCONST(597) = (jx(ip_CH3CHO))
! <J0CH3COOOH>:
  RCONST(598) = (.28*jx(ip_H2O2))
! <J0C2H5OOH>:
  RCONST(599) = (jx(ip_CH3OOH))
! <J0PAN>:
  RCONST(600) = (jx(ip_PAN))
! <J0EOOH>:
  RCONST(601) = (jx(ip_CH3OOH))
! <J0GLYOXAL>:
  RCONST(602) = (jx(ip_GLYOX))
! <J0GLYALD>:
  RCONST(603) = (jx(ip_HOCH2CHO))
! <J0HOCH2CO3H>:
  RCONST(604) = (0.28*jx(ip_H2O2))
! <J0HCOCO2H>:
  RCONST(605) = (jx(ip_GLYOX))
! <J0HCOCO3H>:
  RCONST(606) = (2.*jx(ip_CH3OOH))
! <J0CH3COCH3>:
  RCONST(607) = (jx(ip_CH3COCH3))
! <J0C3H7OOH>:
  RCONST(608) = (jx(ip_CH3OOH))
! <J0POOH>:
  RCONST(609) = (jx(ip_CH3OOH))
! <J0HYAC>:
  RCONST(610) = (0.65*0.11*jx(ip_CHOH))
! <J0CH3COCHO>:
  RCONST(611) = (jx(ip_GLYOX))
! <J0ROOH>:
  RCONST(612) = (jx(ip_CH3OOH))
! <J0PR2O2HNO3>:
  RCONST(613) = (jx(ip_CH3OOH))
! <J0NOA>:
  RCONST(614) = (0.33*jx(ip_GLYOX))
! <J0MEK>:
  RCONST(615) = (jx(ip_CH3COCH3))
! <J0MEKOOH>:
  RCONST(616) = (jx(ip_CH3OOH))
! <J0MEKNO3>:
  RCONST(617) = (0.33*jx(ip_GLYOX))
! <J0MACR_a>:
  RCONST(618) = (jx(ip_MACR))
! <J0MACROOH>:
  RCONST(619) = (jx(ip_CH3OOH))
! <J0MACROH>:
  RCONST(620) = (0.65*0.11*jx(ip_CHOH))
! <J0MPAN>:
  RCONST(621) = (jx(ip_PAN))
! <J0MACO3H>:
  RCONST(622) = (jx(ip_CH3OOH))
! <J0MVK>:
  RCONST(623) = (jx(ip_MVK))
! <J0LHMVKABOOH>:
  RCONST(624) = (jx(ip_CH3OOH))
! <J0MVKN>:
  RCONST(625) = (0.5*jx(ip_GLYOX))
! <J0MACRNO3>:
  RCONST(626) = (3.5*jx(ip_GLYOX))
! <J0CO2H3CHO>:
  RCONST(627) = (2.*0.65*0.11*jx(ip_CHOH))
! <J0CO2H3CO3H>:
  RCONST(628) = (2.*0.65*0.11*jx(ip_CHOH))
! <J0BIACETOH>:
  RCONST(629) = (jx(ip_GLYOX))
! <J0ALKOOH>:
  RCONST(630) = (jx(ip_CH3OOH))
! <J0ALKNO3>:
  RCONST(631) = (jx(ip_HNO3))
! <J0LISOPACOOH>:
  RCONST(632) = (jx(ip_CH3OOH))
! <J0LISOPACNO3>:
  RCONST(633) = (jx(ip_HNO3))
! <J0HPALD>:
  RCONST(634) = (500.*jx(ip_MACR))
! <J0PACALD>:
  RCONST(635) = (1000.*jx(ip_MACR))
! <J0LIECHO>:
  RCONST(636) = (jx(ip_GLYOX))
! <J0LIECO3H>:
  RCONST(637) = (jx(ip_CH3OOH))
! <J0ISOPBOOH>:
  RCONST(638) = (jx(ip_CH3OOH))
! <J0ISOPBNO3_a>:
  RCONST(639) = (jx(ip_PAN))
! <J0ISOPDOOH>:
  RCONST(640) = (jx(ip_CH3OOH))
! <J0ISOPDNO3>:
  RCONST(641) = (jx(ip_PAN))
! <J0NISOPOOH>:
  RCONST(642) = (jx(ip_CH3OOH))
! <J0NC4CHO>:
  RCONST(643) = (5.6*jx(ip_GLYOX))
! <J0LNISOOH>:
  RCONST(644) = (jx(ip_CH3OOH))
! <J0LHC4ACCHO>:
  RCONST(645) = (jx(ip_GLYOX))
! <J0LC578OOH>:
  RCONST(646) = (2.*jx(ip_CH3OOH))
! <J0LHC4ACCO3H>:
  RCONST(647) = (2.*jx(ip_CH3OOH))
! <J0HCOC5>:
  RCONST(648) = (jx(ip_GLYOX))
! <J0C59OOH>:
  RCONST(649) = (2.*jx(ip_CH3OOH))
! <J0LISOPOOHOOH>:
  RCONST(650) = (2.*jx(ip_CH3OOH))
! <J0LISOPNO3OOH>:
  RCONST(651) = (jx(ip_CH3OOH))
! <J0LISOPNO3NO3>:
  RCONST(652) = (2.*jx(ip_PAN))
! <J0MBOOOH>:
  RCONST(653) = (jx(ip_CH3OOH))
! <J0IBUTALOH>:
  RCONST(654) = (jx(ip_HOCH2CHO))
! <J0IBUTALOHOOH>:
  RCONST(655) = (0.28*jx(ip_H2O2))
! <J0BEPOMUC>:
  RCONST(656) = (4.*jx(ip_MACR))
! <J0BIGALD1>:
  RCONST(657) = (.14*jx(ip_NO2))
! <J0TOLOOH>:
  RCONST(658) = (jx(ip_CH3OOH))
! <J0TEPOMUC>:
  RCONST(659) = (4.*jx(ip_MACR))
! <J0CATEC1OOH>:
  RCONST(660) = (jx(ip_CH3OOH))
! <J0BIGALD2>:
  RCONST(661) = (.20*jx(ip_NO2))
! <J0BIGALD3>:
  RCONST(662) = (.20*jx(ip_NO2))
! <J0BIGALD4>:
  RCONST(663) = (.006*jx(ip_NO2))
! <J0TERPOOH>:
  RCONST(664) = (jx(ip_CH3OOH))
! <J0TERPROD1>:
  RCONST(665) = (jx(ip_CH3CHO))
! <J0TERP2OOH>:
  RCONST(666) = (jx(ip_CH3OOH))
! <J0TERPROD2>:
  RCONST(667) = (jx(ip_CH3CHO))
! <J0ISOPBNO3_b>:
  RCONST(668) = (jx(ip_PAN))
! <J0NTERPNO3>:
  RCONST(669) = (jx(ip_CH3OOH))
! <J0ELVOC>:
  RCONST(670) = (3.*jx(ip_CH3OOH))
! <J0O2_a>:
  RCONST(671) = (jx(ip_O3PO1D))
! <J0O2_b>:
  RCONST(672) = (jx(ip_O2))
! <J0H2O_a>:
  RCONST(673) = (jx(ip_H2O))
! <J0H2O_b>:
  RCONST(674) = (jx(ip_H2O1D))
! <J0CL2>:
  RCONST(675) = (jx(ip_Cl2))
! <J0CL2O2>:
  RCONST(676) = (jx(ip_Cl2O2))
! <J0HCL>:
  RCONST(677) = (jx(ip_HCl))
! <J0HOCL>:
  RCONST(678) = (jx(ip_HOCl))
! <J0CLONO2_a>:
  RCONST(679) = (jx(ip_ClNO3))
! <J0CLONO2_b>:
  RCONST(680) = (jx(ip_ClONO2))
! <J0OCLO>:
  RCONST(681) = (jx(ip_OClO))
! <J0BrO>:
  RCONST(682) = (jx(ip_BrO))
! <J0HOBr>:
  RCONST(683) = (jx(ip_HOBr))
! <J0BrONO_a>:
  RCONST(684) = (0.5*jx(ip_BrNO2))
! <J0BrONO_b>:
  RCONST(685) = (0.5*jx(ip_BrNO2))
! <J0BrNO2>:
  RCONST(686) = (0.15*jx(ip_BrNO2))
! <J0BrONO2_a>:
  RCONST(687) = (0.85*jx(ip_BrNO3))
! <J0BrONO2_b>:
  RCONST(688) = (0.15*jx(ip_BrNO3))
! <J0Br2>:
  RCONST(689) = (jx(ip_BrO))
! <J0BrCL>:
  RCONST(690) = (jx(ip_BrCl))
! <J0SF6>:
  RCONST(691) = (jx(ip_SF6))
! <J0CH3Br>:
  RCONST(692) = (jx(ip_CH3Br))
! <J0CH2Br2>:
  RCONST(693) = (jx(ip_CH2Br2))
! <J0CHBr3>:
  RCONST(694) = (jx(ip_CHBr3))
! <J0CH3CL>:
  RCONST(695) = (jx(ip_CH3Cl))
! <J0CH3CCL3>:
  RCONST(696) = (jx(ip_CH3CCl3))
! <J0CF3Br>:
  RCONST(697) = (jx(ip_CF3Br))
! <J0CF2CLBr>:
  RCONST(698) = (jx(ip_CF2ClBr))
! <J0CCL4>:
  RCONST(699) = (jx(ip_CCl4))
! <J0CFCl3>:
  RCONST(700) = (jx(ip_CFCl3))
! <J0CF2Cl2>:
  RCONST(701) = (jx(ip_CF2Cl2))
! <J0CFC113>:
  RCONST(702) = (jx(ip_F113))

END SUBROUTINE UPDATE_RCONST
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


! Begin inlined code from F90_RCONST_USE


! End inlined code from F90_RCONST_USE


! Begin inlined code from F90_RCONST


  ! start of USE statements from messy_mecca_kpp.kpp
  USE messy_main_constants_mem  ! atm2Pa, N_A, R_gas
  USE messy_cmn_photol_mem      ! IP_MAX, ip_*, jname
  USE messy_main_tools_kinetics ! ELEMENTAL rate coefficient functions
  ! end of USE statements from messy_mecca_kpp.kpp

  ! start of executable statements
  ! define some rate constants here if the expressions are too long
  ! for kpp or if they are used more than once
  kHO2_HO2     = (3.0E-13*EXP(460./temp)+2.1E-33*EXP(920./temp)*cair)* &
                 (1.+1.4E-21*EXP(2200./temp)*C(ind_H2O))
  kNO2NO3      = k_3rd(TEMP,cair,2.000e-30,4.4,1.400e-12,0.7,0.6)
  kN2O5        = kNO2NO3 * 3.333e26 * EXP(-10991./TEMP)
  kHNO3_OH     = 2.4E-14*EXP(460./temp) + 1./ &
                 ( 1./(6.5E-34*EXP(1335./temp)*cair) + &
                 1./(2.7E-17*EXP(2199./temp)) )
  kNO2HO2      = k_3rd(TEMP,cair,2.000e-31,3.4,2.900e-12,1.1,0.6)
  kHNO4        = kNO2HO2 * EXP(-10900./TEMP) / 2.1e-27
  ! CO + OH start
  kCO_OH_inf   = 2.1e+09 * (TEMP/ 300.)**(6.1)
  kCO_OH_o     = 1.5e-13 * (TEMP/ 300.)**(0.6)
  kCO_OH_term1 = kCO_OH_o / ( (kCO_OH_inf / cair) )
  kCO_OH_term2 = kCO_OH_o / (1. + kCO_OH_term1)
  kCO_OH_term1 = LOG10( kCO_OH_term1 )
  kCO_OH_term1 = 1. / (1. + kCO_OH_term1*kCO_OH_term1)
  kCO_OH       = kCO_OH_term2 * (0.6)**kCO_OH_term1
  ! CO + OH end
  kNO2CH3O2    = k_3rd(TEMP,cair,1.000e-30,4.8,7.200e-12,2.1,0.6)
  kCH3O2NO2    = kNO2CH3O2 * EXP(-11234./TEMP) / 9.5e-29
  k_CH3CO3_NO2 = k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.6)
  kPAN         = k_CH3CO3_NO2 * 1.111e28 * EXP(-14000./TEMP)
  k_MACO3_NO2  = k_3rd(TEMP,cair,2.700e-28,7.1,1.200e-11,0.9,0.3)
  kMPAN        = k_MACO3_NO2 * 1.111e28 * EXP(-14000./TEMP)
  kClOClO      = k_3rd(TEMP,cair,1.600e-32,4.5,3.000e-12,2.,0.6)
  kCl2O2       = kClOClO / (1.3e-27 * EXP(8744./TEMP))

! End inlined code from F90_RCONST

  RCONST(576) = (jx(ip_O1D))
  RCONST(577) = (jx(ip_O3P))
  RCONST(578) = (jx(ip_H2O2))
  RCONST(579) = (jx(ip_N2O))
  RCONST(580) = (jx(ip_NO))
  RCONST(581) = (jx(ip_NO2))
  RCONST(582) = (jx(ip_NO2O))
  RCONST(583) = (jx(ip_NOO2))
  RCONST(584) = (jx(ip_HNO3))
  RCONST(585) = (jx(ip_HONO))
  RCONST(586) = (.333*jx(ip_HNO4))
  RCONST(587) = (.667*jx(ip_HNO4))
  RCONST(588) = (jx(ip_N2O5))
  RCONST(589) = (jx(ip_CO2))
  RCONST(590) = (0.42*jx(ip_CH4))
  RCONST(591) = (0.48*jx(ip_CH4))
  RCONST(592) = (jx(ip_CHOH))
  RCONST(593) = (jx(ip_COH2))
  RCONST(594) = (jx(ip_CH3OOH))
  RCONST(595) = (.333*jx(ip_CH3O2NO2))
  RCONST(596) = (.667*jx(ip_CH3O2NO2))
  RCONST(597) = (jx(ip_CH3CHO))
  RCONST(598) = (.28*jx(ip_H2O2))
  RCONST(599) = (jx(ip_CH3OOH))
  RCONST(600) = (jx(ip_PAN))
  RCONST(601) = (jx(ip_CH3OOH))
  RCONST(602) = (jx(ip_GLYOX))
  RCONST(603) = (jx(ip_HOCH2CHO))
  RCONST(604) = (0.28*jx(ip_H2O2))
  RCONST(605) = (jx(ip_GLYOX))
  RCONST(606) = (2.*jx(ip_CH3OOH))
  RCONST(607) = (jx(ip_CH3COCH3))
  RCONST(608) = (jx(ip_CH3OOH))
  RCONST(609) = (jx(ip_CH3OOH))
  RCONST(610) = (0.65*0.11*jx(ip_CHOH))
  RCONST(611) = (jx(ip_GLYOX))
  RCONST(612) = (jx(ip_CH3OOH))
  RCONST(613) = (jx(ip_CH3OOH))
  RCONST(614) = (0.33*jx(ip_GLYOX))
  RCONST(615) = (jx(ip_CH3COCH3))
  RCONST(616) = (jx(ip_CH3OOH))
  RCONST(617) = (0.33*jx(ip_GLYOX))
  RCONST(618) = (jx(ip_MACR))
  RCONST(619) = (jx(ip_CH3OOH))
  RCONST(620) = (0.65*0.11*jx(ip_CHOH))
  RCONST(621) = (jx(ip_PAN))
  RCONST(622) = (jx(ip_CH3OOH))
  RCONST(623) = (jx(ip_MVK))
  RCONST(624) = (jx(ip_CH3OOH))
  RCONST(625) = (0.5*jx(ip_GLYOX))
  RCONST(626) = (3.5*jx(ip_GLYOX))
  RCONST(627) = (2.*0.65*0.11*jx(ip_CHOH))
  RCONST(628) = (2.*0.65*0.11*jx(ip_CHOH))
  RCONST(629) = (jx(ip_GLYOX))
  RCONST(630) = (jx(ip_CH3OOH))
  RCONST(631) = (jx(ip_HNO3))
  RCONST(632) = (jx(ip_CH3OOH))
  RCONST(633) = (jx(ip_HNO3))
  RCONST(634) = (500.*jx(ip_MACR))
  RCONST(635) = (1000.*jx(ip_MACR))
  RCONST(636) = (jx(ip_GLYOX))
  RCONST(637) = (jx(ip_CH3OOH))
  RCONST(638) = (jx(ip_CH3OOH))
  RCONST(639) = (jx(ip_PAN))
  RCONST(640) = (jx(ip_CH3OOH))
  RCONST(641) = (jx(ip_PAN))
  RCONST(642) = (jx(ip_CH3OOH))
  RCONST(643) = (5.6*jx(ip_GLYOX))
  RCONST(644) = (jx(ip_CH3OOH))
  RCONST(645) = (jx(ip_GLYOX))
  RCONST(646) = (2.*jx(ip_CH3OOH))
  RCONST(647) = (2.*jx(ip_CH3OOH))
  RCONST(648) = (jx(ip_GLYOX))
  RCONST(649) = (2.*jx(ip_CH3OOH))
  RCONST(650) = (2.*jx(ip_CH3OOH))
  RCONST(651) = (jx(ip_CH3OOH))
  RCONST(652) = (2.*jx(ip_PAN))
  RCONST(653) = (jx(ip_CH3OOH))
  RCONST(654) = (jx(ip_HOCH2CHO))
  RCONST(655) = (0.28*jx(ip_H2O2))
  RCONST(656) = (4.*jx(ip_MACR))
  RCONST(657) = (.14*jx(ip_NO2))
  RCONST(658) = (jx(ip_CH3OOH))
  RCONST(659) = (4.*jx(ip_MACR))
  RCONST(660) = (jx(ip_CH3OOH))
  RCONST(661) = (.20*jx(ip_NO2))
  RCONST(662) = (.20*jx(ip_NO2))
  RCONST(663) = (.006*jx(ip_NO2))
  RCONST(664) = (jx(ip_CH3OOH))
  RCONST(665) = (jx(ip_CH3CHO))
  RCONST(666) = (jx(ip_CH3OOH))
  RCONST(667) = (jx(ip_CH3CHO))
  RCONST(668) = (jx(ip_PAN))
  RCONST(669) = (jx(ip_CH3OOH))
  RCONST(670) = (3.*jx(ip_CH3OOH))
  RCONST(671) = (jx(ip_O3PO1D))
  RCONST(672) = (jx(ip_O2))
  RCONST(673) = (jx(ip_H2O))
  RCONST(674) = (jx(ip_H2O1D))
  RCONST(675) = (jx(ip_Cl2))
  RCONST(676) = (jx(ip_Cl2O2))
  RCONST(677) = (jx(ip_HCl))
  RCONST(678) = (jx(ip_HOCl))
  RCONST(679) = (jx(ip_ClNO3))
  RCONST(680) = (jx(ip_ClONO2))
  RCONST(681) = (jx(ip_OClO))
  RCONST(682) = (jx(ip_BrO))
  RCONST(683) = (jx(ip_HOBr))
  RCONST(684) = (0.5*jx(ip_BrNO2))
  RCONST(685) = (0.5*jx(ip_BrNO2))
  RCONST(686) = (0.15*jx(ip_BrNO2))
  RCONST(687) = (0.85*jx(ip_BrNO3))
  RCONST(688) = (0.15*jx(ip_BrNO3))
  RCONST(689) = (jx(ip_BrO))
  RCONST(690) = (jx(ip_BrCl))
  RCONST(691) = (jx(ip_SF6))
  RCONST(692) = (jx(ip_CH3Br))
  RCONST(693) = (jx(ip_CH2Br2))
  RCONST(694) = (jx(ip_CHBr3))
  RCONST(695) = (jx(ip_CH3Cl))
  RCONST(696) = (jx(ip_CH3CCl3))
  RCONST(697) = (jx(ip_CF3Br))
  RCONST(698) = (jx(ip_CF2ClBr))
  RCONST(699) = (jx(ip_CCl4))
  RCONST(700) = (jx(ip_CFCl3))
  RCONST(701) = (jx(ip_CF2Cl2))
  RCONST(702) = (jx(ip_F113))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE jam_Rates

