! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : small_strato_Monitor.f90
! Equation file        : small_strato.kpp
! Output root filename : small_strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE small_strato_Monitor


  CHARACTER(LEN=32), PARAMETER, DIMENSION(7) :: SPC_NAMES = (/ &
     'O1D                             ','O                               ','O3                              ', & ! index 1 - 3
     'NO                              ','NO2                             ','M                               ', & ! index 4 - 6
     'O2                              ' /) ! index up to 7

  INTEGER, PARAMETER, DIMENSION(7) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7 /) ! index up to 7

  INTEGER, PARAMETER, DIMENSION(6) :: MONITOR = (/ &
       1,  2,  3,  4,  5,  7 /) ! index up to 6

  CHARACTER(LEN=32), PARAMETER, DIMENSION(1) :: SMASS = (/ &
     'N                               ' /) ! index up to 1

  CHARACTER(LEN=100), PARAMETER, DIMENSION(10) :: EQN_NAMES = (/ &
     '      O2 --> 2 O                                                                                    ', & ! index 1
     '  O + O2 --> O3                                                                                     ', & ! index 2
     '      O3 --> O + O2                                                                                 ', & ! index 3
     '  O + O3 --> 2 O2                                                                                   ', & ! index 4
     '      O3 --> O1D + O2                                                                               ', & ! index 5
     ' O1D + M --> O + M                                                                                  ', & ! index 6
     'O1D + O3 --> 2 O2                                                                                   ', & ! index 7
     ' O3 + NO --> NO2 + O2                                                                               ', & ! index 8
     ' O + NO2 --> NO + O2                                                                                ', & ! index 9
     '     NO2 --> O + NO                                                                                 ' /) ! index up to 10

  CHARACTER(LEN=32), DIMENSION(1) :: FAM_NAMES
! Begin inlined code from F90_DATA

! End inlined code from F90_DATA


END MODULE small_strato_Monitor
