! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-3.4.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
!        P.O. Sturm,  Univ. of Southern California, Los Angeles, CA, USA
! 
! File                 : small_strato_StoichiomSP.f90
! Equation file        : small_strato.kpp
! Output root filename : small_strato
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE small_strato_StoichiomSP

  USE small_strato_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(11) :: CROW_JVRP = (/ &
       1,  1,  2,  3,  5,  6,  7,  9, 11, 13, 14 /) ! index up to 11

  INTEGER, PARAMETER, DIMENSION(13) :: ICOL_JVRP = (/ &
       2,  3,  2,  3,  3,  1,  1,  3,  3,  4,  2,  5, & ! index 1 - 12
       5 /) ! index up to 13

  INTEGER, PARAMETER, DIMENSION(13) :: IROW_JVRP = (/ &
       2,  3,  4,  4,  5,  6,  7,  7,  8,  8,  9,  9, & ! index 1 - 12
      10 /) ! index up to 13



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(11) :: CCOL_STOICM = (/ &
       1,  2,  4,  6,  8, 10, 12, 14, 17, 20, 23 /) ! index up to 11

  INTEGER, PARAMETER, DIMENSION(22) :: IROW_STOICM = (/ &
       2,  2,  3,  2,  3,  2,  3,  1,  3,  1,  2,  1, & ! index 1 - 12
       3,  3,  4,  5,  2,  4,  5,  2,  4,  5 /) ! index up to 22

  INTEGER, PARAMETER, DIMENSION(22) :: ICOL_STOICM = (/ &
       1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7, & ! index 1 - 12
       7,  8,  8,  8,  9,  9,  9, 10, 10, 10 /) ! index up to 22

  REAL(kind=dp), PARAMETER, DIMENSION(22) :: STOICM = (/ &
       2.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp, & ! index 1 - 5
       -1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, & ! index 6 - 10
       1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp,  -1.000000e+00_dp, & ! index 11 - 15
       1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp, & ! index 16 - 20
       1.000000e+00_dp,  -1.000000e+00_dp /) ! index up to 22


END MODULE small_strato_StoichiomSP

