! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : superfast_JacobianSP.f90
! Equation file        : superfast.kpp
! Output root filename : superfast
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE superfast_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(90) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  4,  4, & ! index 1 - 12
       4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  6, & ! index 13 - 24
       6,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  9, & ! index 25 - 36
       9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11, & ! index 37 - 48
      11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, & ! index 49 - 60
      12, 12, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, & ! index 61 - 72
      14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, & ! index 73 - 84
      15, 15, 15, 15, 15, 15 /) ! index up to 90

  INTEGER, PARAMETER, DIMENSION(90) :: LU_ICOL = (/ &
       1, 10, 15,  2,  5,  6, 14, 15,  3, 15,  4,  7, & ! index 1 - 12
       8, 14, 15,  5,  6, 11, 15,  3,  5,  6, 11, 14, & ! index 13 - 24
      15,  7, 14, 15,  7,  8,  9, 12, 13, 14, 15,  9, & ! index 25 - 36
      11, 13, 15, 10, 11, 12, 13, 14, 15,  4,  5,  6, & ! index 37 - 48
       7,  8,  9, 11, 12, 13, 14, 15, 10, 11, 12, 13, & ! index 49 - 60
      14, 15,  7,  9, 11, 12, 13, 14, 15,  6,  7, 10, & ! index 61 - 72
      11, 12, 13, 14, 15,  3,  4,  5,  6,  7,  8,  9, & ! index 73 - 84
      10, 11, 12, 13, 14, 15 /) ! index up to 90

  INTEGER, PARAMETER, DIMENSION(16) :: LU_CROW = (/ &
       1,  4,  9, 11, 16, 20, 26, 29, 36, 40, 46, 57, & ! index 1 - 12
      63, 70, 78, 91 /) ! index up to 16

  INTEGER, PARAMETER, DIMENSION(16) :: LU_DIAG = (/ &
       1,  4,  9, 11, 16, 22, 26, 30, 36, 40, 52, 59, & ! index 1 - 12
      67, 76, 90, 91 /) ! index up to 16


END MODULE superfast_JacobianSP

